/** Global channels (extra 2): security-corner, oncall-handoff, it-help, people-team, finance-close, ask-pmo, product-launches, customer-stories. Contract: ./chat-dsl.ts */
import type { GlobalChannelDef } from './chat-dsl';

export const GLOBAL_E2: GlobalChannelDef[] = [
  {
    name: 'security-corner',
    topic: 'Security questions, advisories and tips. Report phishing here or to security@.',
    size: 5,
    cast: ['tomas'],
    castWeight: 0.15,
    depts: ['Security', 'IT & Infrastructure', 'Engineering'],
    mix: [['sec', 10], ['generic:question', 2], ['generic:access', 2], ['generic:risk', 1], ['generic:ack', 1]],
    pools: {
      sec: [
        ["A: Is this email legit? 'Your mailbox is full, click to verify.'", "B: Not legit. Don't click. Forward it to the report button and delete it.", "A: Reported, thanks.", "B: Three others reported it too. We've blocked the sender domain. ~rx:👍"],
        ["A: **Security tip of the month** 🔐\n\nTurn on passkeys wherever they're offered. They can't be phished, and they're faster than passwords. Guide: {wiki}.", "B: Switched mine last week, sign-ins are so smooth. ~rx:🔐|👍"],
        ["A: Advisory: critical vulnerability published for a popular logging library (CVE-2026-4{n}1).", "B: Are we affected?", "A: Scanning now. {n2} services use it, patches in progress. I'll post status at {time}.", "A: Update: all production services patched, two dev environments remain. ~rx:🙏"],
        ["A: Reminder that sharing the QR code for your MFA enrolment in chat is the same as sharing your password.", "B: Deleted my screenshot just now. 🙈"],
        ["A: Can I use a personal USB stick for a workshop?", "B: Only encrypted devices from the approved list. Borrow one from IT.", "A: Thanks, collecting one."],
        ["A: SSO for {tool} is live. Please sign in with your company account, not the old password.", "B: Was the old one disabled?", "A: On {date}. ~r"],
        ["A: Pen test summary is available: {wiki}. Highs are fixed, mediums are scheduled.", "B: Thanks for the transparency. ~rx:👍"],
        ["A: Reminder: lost laptop? Report within 1 hour so we can wipe it.", "B: Pinning. ~rx:👍 ~pin:Lost device procedure"],
        ["A: Why do I need to rotate this secret every 90 days?", "B: To limit exposure if it leaked without us knowing. Automation will do it for you from next quarter.", "A: Fair, thanks."],
        ["A: Phishing simulation result: {pct} clicked, {pct2} reported. Thanks to the reporters!", "B: Reporting rate beat the target. ~rx:🎉"],
        ["A: Is a shared inbox allowed to use a shared password?", "B: No. Use delegated access instead. IT can set it up.", "A: On it."],
        ["A: Device compliance: {n} laptops still need an OS update.", "B: Updates are mandatory by {date}. Reminder emails going out. ~rx:👍"],
      ],
    },
  },
  {
    name: 'oncall-handoff',
    topic: 'Weekly on-call handoff notes and follow-ups.',
    size: 4,
    depts: ['Engineering', 'IT & Infrastructure', 'Security', 'Data & Analytics'],
    mix: [['handoff', 10], ['generic:incident', 3], ['generic:ooo', 1], ['generic:ack', 1]],
    pools: {
      handoff: [
        ["A: **On-call handoff, week {n}**\n- Pages: {n2} (3 actionable)\n- Incidents: {ticket} (disk full on the queue broker, resolved)\n- Follow-ups: tune the disk alert threshold, add a runbook for broker cleanup\n- Upcoming: DB maintenance {day} 02:00 UTC\n- Noisy alerts: `checkout-latency` flaps at night, ignore until {task} lands", "B: Taking over. Thanks for the clean handoff! ~rx:🙏|👍"],
        ["A: **Handoff**\nQuiet week, 2 pages, both false alarms from a certificate check. Action: raised the threshold. Nothing pending.", "B: Love a quiet week. ~rx:🙌"],
        ["A: Who's primary this week? I need to swap my Thursday shift.", "B: I can cover Thursday, swap Saturday?", "A: Deal. Updating the rota."],
        ["A: **Handoff**\nBig week: one P1 ({ticket}) on {day}, postmortem scheduled. Follow-ups:\n- Add synthetic check for the login flow\n- Review autoscaling limits\nPlease read the timeline before your first shift.", "B: Read it. Thanks. Will own the autoscaling item."],
        ["A: Alert noise is unreal. {n} pages overnight, none actionable.", "B: Filing a task to silence the flapping alert and fix the underlying check.", "A: Thanks, I'm too tired to be polite."],
        ["A: Runbook gap: the queue backlog procedure doesn't mention the consumer restart.", "B: Added, PR {pr}. ~rx:👍"],
        ["A: Reminder: postmortem action items are due {date}. {n} still open.", "B: Closing mine today."],
        ["A: First time on-call and I'm nervous.", "B: You've got this. Shadow me tomorrow, I'll walk you through the dashboards.", "C: And call anytime. Nobody's mad at a question at 3am. ~rx:💪"],
      ],
    },
  },
  {
    name: 'it-help',
    topic: 'Laptops, VPN, licences and access. Include your ticket number.',
    size: 9,
    cast: ['kenji'],
    castWeight: 0.05,
    depts: ['IT & Infrastructure'],
    mix: [['help', 10], ['generic:access', 3], ['generic:question', 2], ['generic:thanks', 1], ['generic:ack', 1]],
    pools: {
      help: [
        ["A: VPN keeps dropping every 10 minutes on the home Wi-Fi.", "B: Try switching to the UDP profile in the client settings. Ticket {ticket} for tracking.", "A: That helped, stable for an hour. Thanks!"],
        ["A: Laptop won't wake from sleep after the update.", "B: Hold the power button for 15 seconds, then boot. If it repeats, bring it to the desk for a swap.", "A: It woke up. Will watch it."],
        ["A: I need Figma access for the design review.", "B: Added you to the group, give it 10 minutes and sign out/in. ~r", "A: Works, thank you!"],
        ["A: How do I reset my MFA? Got a new phone.", "B: 1. Open the self-service portal\n2. Choose 'Replace device'\n3. Scan the new code\nStuck? DM me with your ticket.", "A: Worked on the first try. ~rx:🙏"],
        ["A: Printer on level 3 says 'offline'.", "B: Power cycled it, back online. If it recurs, it's the network switch, ticket raised."],
        ["A: Is Zoom down?", "B: Not on our side. Check the status page: reported issue in {region}. Using the backup bridge for now."],
        ["A: Can I get a second monitor?", "B: Yes, standard request. Submit in the portal and I'll deliver Thursday.", "A: Submitted, thanks."],
        ["A: Shared drive says 'access denied' for the finance folder.", "B: Needs approval from the folder owner. I've pinged them, ticket {ticket}.", "A: Great."],
        ["A: Battery is swelling a bit on my laptop.", "B: Stop using it now and bring it to IT. Safety first. We'll swap it today.", "A: On my way."],
        ["A: Conference room AV not working.", "B: Cable's loose, re-seated. Try now.", "A: Works, thanks!"],
        ["A: Software request: need a licence for a PDF editor.", "B: Approved list has two options: pick one in the catalogue and your manager approves.", "A: Done."],
        ["A: Wi-Fi in the kitchen is slow at lunch.", "B: Known: too many video calls. We're adding an access point next week. ~rx:🙏"],
      ],
    },
  },
  {
    name: 'people-team',
    topic: 'People Ops questions, hiring updates and programmes.',
    size: 4,
    cast: ['amara'],
    castWeight: 0.2,
    depts: ['People Operations', 'Transformation Office', 'Legal & Compliance'],
    mix: [['hr', 10], ['generic:question', 2], ['generic:birthday', 2], ['generic:ack', 1]],
    pools: {
      hr: [
        ["A: Q: How many days of parental leave do I get?", "B: 26 weeks at full pay for the primary carer, 8 for the secondary. Details in {wiki}.", "A: Thanks, that's clear."],
        ["A: **Hiring update** 📣\nWe've filled {n} of {n2} open roles this quarter. Interviews are on for engineering and customer success. Referral bonuses are {usd}.", "B: Is the referral link in the wiki?", "A: Yes, {wiki}. ~r"],
        ["A: Performance cycle opens {date}. Self-reviews are due the week after, manager reviews the week after that.", "B: Is calibration changing?", "A: No change, guide is here: {wiki}. ~r"],
        ["A: Can I carry over unused PTO?", "B: Up to 5 days into the next year. The rest expires on {date}.", "A: Booking a long weekend."],
        ["A: Onboarding cohort starts Monday. Buddies assigned, laptops delivered. Welcome kit is in the post.", "B: Slack intros are ready. ~rx:👋"],
        ["A: Learning stipend: can I use it for a course in another city?", "B: Yes, with receipts. Travel isn't covered.", "A: Fine, thanks."],
        ["A: Culture survey results are in: {pct} engagement, up {pct2}. Biggest improvement: manager feedback.", "B: Lowest score: career growth. We'll share the action plan. ~rx:📈"],
        ["A: Internal mobility board refreshed: {n} roles open. Talk to your manager before applying.", "B: Great, bookmarking. ~rx:🙌"],
        ["A: Remote-work policy FAQ updated: {wiki}", "B: Thanks for the quick turnaround. ~rx:👍"],
        ["A: Reminder: wellbeing day is {date}. Please don't schedule meetings.", "B: Calendar blocked. ~rx:🧘"],
      ],
    },
  },
  {
    name: 'finance-close',
    topic: 'Month-end close checklist, cutoffs and reconciliations.',
    size: 5,
    cast: ['ravi'],
    castWeight: 0.1,
    depts: ['Finance', 'Supply Chain', 'Sales Operations', 'Transformation Office'],
    mix: [['close', 10], ['generic:question', 2], ['generic:status', 2], ['generic:ack', 1]],
    pools: {
      close: [
        ["A: **Close calendar, BD{n}**\n- Sub-ledger cutoff 6pm ET\n- Accruals due BD2\n- Intercompany matched BD3\n- Flash report BD4\nPlease confirm your owners in the tracker: {tracker}", "B: AP confirmed. ~rx:👍"],
        ["A: Question on accruals: do we accrue for the invoice we haven't received?", "B: Yes, if goods were received by month-end. Use the GR/IR report.", "A: Thanks, posting."],
        ["A: Intercompany difference of {usd} between UK and DE.", "B: FX timing. Revalued DE at month-end rate, difference is now zero.", "A: Great. Locked."],
        ["A: Late invoice from {cust}: dated the 28th, received today.", "B: Accrue it in the prior month with a note. Backup attached to the journal.", "A: Ok."],
        ["A: Flash report ready: revenue {usd}, opex {usd2}. Variances in {wiki}.", "B: Explaining the cloud variance in my commentary. ~rx:🙏"],
        ["A: Cutoff is 6pm ET. Journals after that roll into next month.", "B: Understood. Posting now."],
        ["A: Audit PBC request: bank confirmations for Q{n}.", "B: Pulling them today."],
        ["A: Expense reports older than 60 days will be rejected from {date}.", "B: Noted, reminding the teams."],
        ["A: Close retro: we finished BD4, one day ahead. Biggest win: automated reconciliations.", "B: Great job all. ~rx:🎉"],
        ["A: Who owns the prepaid schedule?", "B: Me, sending the update by noon."],
      ],
    },
  },
  {
    name: 'ask-pmo',
    topic: 'Questions for the PMO: intake, templates, governance and reporting.',
    size: 7,
    depts: [],
    mix: [['pmo', 10], ['generic:question', 2], ['generic:status', 1], ['generic:docs', 1]],
    pools: {
      pmo: [
        ["A: How do I start a new project in Atlas?", "M: Create it from the Projects page, pick the template that matches your delivery model and add your sponsor. I'll review the intake form within 2 working days.", "A: Thanks, that's clearer than the wiki."],
        ["A: What's the difference between amber and red status?", "M: Amber means we have a risk with a plan and an owner. Red means we're off track and need a decision or help. If you aren't sure, ask me in this channel.", "A: Got it, thanks."],
        ["A: Where's the status report template?", "M: {wiki} (the 'Weekly status' page). It's one slide, please keep it that way. 🙂 ~file:Weekly-status-template.pptx", "A: Perfect."],
        ["A: Can I change the budget after the steering committee approved it?", "M: Yes, through a change request. If the increase is under 10%, your sponsor can approve. Above that it goes back to the committee.", "A: Thanks for the quick answer."],
        ["A: How often should I update my tasks?", "B: At least weekly before the status review, daily if you're in a critical phase.", "M: What {B} said. The status roll-up reads from the task board, so it keeps everyone honest."],
        ["A: Dependency on another team's project, who do I talk to?", "M: Add the dependency in the task view and tag the owner. If it's blocking, flag it in the risk register and I'll bring it to the portfolio review.", "A: Done."],
        ["A: What's the steering committee schedule?", "M: First Thursday of the month at 10am ET. Agenda closes the Monday before. {wiki}", "A: Thanks!"],
        ["A: Can I archive a project that's finished?", "M: Yes, once the closure checklist is done: lessons learned, final budget, handover. Archive button is under project settings."],
        ["A: Is there a template for a RACI?", "M: Yes: {wiki}. Keep it to roles, not names, and review it at kickoff. ~file:RACI-template.xlsx"],
        ["A: What's an acceptable number of milestones for a 6-month project?", "B: Five to eight, more than that and nobody tracks them.", "M: Agree with {B}. Link milestones to deliverables the sponsor cares about."],
        ["A: How do I request a resource from another team?", "M: Use the resource request form, include the role, hours per week and the dates. I'll check capacity and loop in the manager.", "A: Submitted."],
        ["A: Where can I see all the projects I'm on?", "M: Dashboard → 'My projects'. You can also pin your favourites. ~rx:👍"],
        ["A: PMO office hours still on Thursdays?", "M: Yes, 2-3pm ET. Bring your plan, your risks and your questions."],
        ["A: Who approves a scope change?", "M: Sponsor plus the project manager, recorded in the decision log. Anything that changes the end date goes to the steering committee."],
      ],
    },
  },
  {
    name: 'product-launches',
    topic: 'Launch calendar, readiness checks and go/no-go coordination.',
    size: 4,
    cast: ['nadia', 'sofia'],
    castWeight: 0.2,
    depts: ['Product', 'Marketing', 'Engineering', 'Customer Success', 'Sales Operations'],
    mix: [['launch', 10], ['generic:release', 3], ['generic:decision', 2], ['generic:status', 2]],
    pools: {
      launch: [
        ["A: **T-minus 5 days to {proj} GA**\n- [x] Engineering code freeze\n- [x] Pricing page reviewed\n- [ ] Support training (Thursday)\n- [ ] Sales enablement call (Friday)\n- [ ] Press embargo confirmed", "B: Support training is booked, FAQ draft is in {wiki}. ~rx:👍"],
        ["A: Go/no-go meeting at {time}. Inputs: test results, support readiness, comms plan.", "B: Test results: green, 2 known issues, workarounds documented.", "C: Support is ready. Comms is ready.", "A: Decision: go. ~rx:🚀|✅"],
        ["A: Launch calendar for {q} is in {wiki}. Overlaps in the second week, let's talk.", "B: I'll shift one announcement by two days. ~rx:👍"],
        ["A: Pricing page will go live at 9am ET. Redirects are tested.", "B: Checking the checkout flow again. ~rx:👀"],
        ["A: First 24 hours: {n} sign-ups, {pct} conversion to paid.", "B: Support volume is normal. ~rx:🎉"],
        ["A: Post-launch retro on {day}. Please add your notes before then.", "B: Added mine. ~rx:👍"],
        ["A: Enablement deck for the sales team: {wiki}", "B: Will present on the call and record it. ~file:Sales-enablement-deck.pptx"],
        ["A: Launch day run-of-show: 8:30 final checks, 9:00 release, 9:15 announcement, 10:00 social, 11:00 customer webinar.", "B: I'll be on the bridge from 8. ~rx:🚀"],
        ["A: Embargo is lifted. Press release is live.", "B: Coverage in {n} outlets already. ~rx:🎉"],
      ],
    },
  },
  {
    name: 'customer-stories',
    topic: 'What customers are telling us: wins, quotes and escalations resolved.',
    size: 3,
    cast: ['oliver'],
    castWeight: 0.15,
    depts: ['Customer Success', 'Sales Operations', 'Marketing', 'Product'],
    mix: [['stories', 10], ['generic:feedback', 3], ['generic:thanks', 1]],
    pools: {
      stories: [
        ["A: From {cust} this morning:\n> 'The new dashboards saved my team two days a week. I can't imagine going back.'\n\nShare it with product. 🙌", "B: Sharing in the product channel. ~rx:❤️|🎉"],
        ["A: Case study draft with {cust}: they cut onboarding time by {pct}. Looking for a quote from their sponsor.", "B: I'll introduce you. They loved the process."],
        ["A: Escalation resolved with {cust}. Root cause fixed, credit applied and a call with their CTO went well.", "B: Great save. What did we learn?", "A: Better monitoring and a named owner for every top-tier account."],
        ["A: NPS verbatim of the week:\n> 'Support felt like part of my team.'", "B: Pinning this. ~rx:❤️|🙌 ~pin:Customer quote"],
        ["A: Renewal saved at {cust}: they were about to churn, we moved the sponsor meeting forward and added training.", "B: Textbook. ~rx:🏆"],
        ["A: A customer asked for feature X for months, shipped in {ver}. They wrote a thank-you note.", "B: That's why we do this. ~rx:🎉"],
        ["A: QBR with {cust}: they asked for deeper integration with their ERP.", "B: Adding it to the product requests. Story in {wiki}.", "A: Thanks. ~r"],
        ["A: A big thank you to {@B} for handling the {cust} call at 2am.", "B: Happy to help. Great customer, great call. ~rx:👏"],
        ["A: Quote for the website, approved by {cust}: 'It just works, and the team behind it listens.'", "B: Beautiful. ~rx:🎉"],
        ["A: Customer video testimonial recorded. Edit in progress.", "B: Can't wait to see it. ~rx:🎥"],
      ],
    },
  },
];
