/**
 * Kind libraries (part A): software, mobile, data, security, infrastructure.
 * Hand-authored project-channel conversations. Authoring contract: ./chat-dsl.ts
 */
import type { KindLib } from './chat-dsl';
import type { ProjectKind } from '../schema';

export const KINDS_A: Partial<Record<ProjectKind, KindLib>> = {
  // ═══════════════════════════════════════════════════════════════════
  // SOFTWARE: web / product engineering
  // ═══════════════════════════════════════════════════════════════════
  software: {
    lex: {
      feature: ['saved filters', 'SSO login', 'bulk invoice export', 'usage-based billing page', 'in-app notifications', 'team workspaces', 'audit log viewer', 'webhook retries', 'dark mode', 'CSV import wizard', 'role-based access', 'global search', 'activity feed', 'two-step checkout', 'inline comments'],
      component: ['billing service', 'API gateway', 'auth middleware', 'search indexer', 'notification worker', 'design-system Button', 'monorepo build graph', 'GraphQL schema', 'feature-flag client', 'session store', 'web client', 'orders API', 'rate limiter', 'background job runner'],
      tool: ['GitHub Actions', 'LaunchDarkly', 'Sentry', 'Datadog', 'Playwright', 'Storybook', 'Renovate', 'Turborepo', 'Vite', 'Postman', 'pnpm', 'Jest', 'ESLint', 'Chromatic'],
      problem: ['flaky Playwright test', 'N+1 query', 'memory leak in the worker', 'stale cache entry', 'race condition on save', 'hydration mismatch', 'circular dependency', 'timezone bug', 'unbounded retry loop', 'missing index', 'breaking API change', 'slow cold start', 'merge conflict in the lockfile'],
      metric: ['p95 latency', 'bundle size', 'CI duration', 'error budget burn', 'LCP', 'test coverage', 'deploy frequency', 'change failure rate', 'PR cycle time', 'flake rate', 'time to first byte', 'INP'],
      deliverable: ['migration guide', 'API changelog', 'OpenAPI spec', 'ADR', 'release notes', 'rollout checklist', 'load-test report', 'threat model', 'tech design doc', 'Storybook docs', 'contract test suite', 'deprecation notice'],
      team: ['platform team', 'web guild', 'backend squad', 'QA', 'SRE', 'design systems team', 'growth squad', 'mobile team', 'security champions', 'support engineering', 'payments squad', 'data eng'],
      flag: ['new-checkout-v2', 'saved-filters-beta', 'search-rewrite', 'async-export', 'sso-enforce', 'inline-comments', 'billing-v3-read', 'edge-cache-shell'],
      env: ['staging', 'the preview env', 'prod', 'the canary', 'the QA env', 'the sandbox tenant', 'the EU stack', 'dev'],
      artifact: ['source map', 'bundle report', 'flame graph', 'HAR file', 'heap snapshot', 'Lighthouse report', 'trace', 'coverage report'],
    },
    pools: {
      work: [
        [
          "A: Quick API-contract question. We want to add an optional `currency` field to the `/invoices` response. Breaking or not?",
          "B: Additive, so technically no. Practically it depends who deserialises strictly. {cust}'s integration used to choke on unknown fields.",
          "C: We have Pact tests for the three public consumers. Run them against the branch before you decide anything.",
          "A: Ran them, all green. I'll still note it in the {deliverable} so nobody is surprised. ~r",
          "B: 👍 and bump the minor version on the OpenAPI spec while you're there.",
        ],
        [
          "A: {pr} is up: moves the {component} onto the new request context. Big diff but ~70% is import path churn. Reviewer tip: start at `context.ts`, the rest is mechanical.",
          "B: Reading it now. Why are we passing the user ID twice in `handleRequest`? I see it in the ctx and as an arg.",
          "A: Legacy. Two callers still use the arg form, I left a comment explaining why and a ticket for the cleanup.",
          "B: Fine by me, approving once CI is green. The lint rule you added for ctx misuse is nice, by the way.",
        ],
        [
          "A: Flag hygiene round: `{flag}` has been at 100% for {n} weeks and the old path is still in the code. Who owns the cleanup?",
          "B: That's mine. I held it because support wanted a kill switch through the quarter-end close.",
          "A: Makes sense. Can we agree on a rule: flag at 100% for two weeks, cleanup ticket auto-created, owner is the author?",
          "C: +1. LaunchDarkly can tag flags with an expiry date and nag the owner in Slack. I'll set that up this week.",
          "B: Cleanup PR for `{flag}` by {day}. Please hold me to it. ~rx:👍",
        ],
        [
          "A: {metric} on the dashboard page went from 2.1s to 3.4s since {ver}. Bundle analyzer says a charting lib snuck into the main chunk.",
          "B: Ugh. Was it the barrel import? `import { Chart } from '@halcyon/ui'` drags the whole package in.",
          "A: Yes. Switching to a deep import brings the main chunk back down by 180kB gzip. Lazy-loading the chart below the fold gets us the rest.",
          "C: Can we add a size-limit check to CI so this fails loudly next time? {tool} has a plugin.",
          "A: Doing that in the same PR. Budget: 250kB for the entry chunk, tell me if that's too tight. ~img:Bundle analyzer treemap",
        ],
        [
          "A: Found the slow endpoint. Classic N+1: for each order we hit `line_items` separately. {n} orders per page means {n} extra round trips.",
          "A: ```sql\n-- before: one query per order\nSELECT * FROM line_items WHERE order_id = $1;\n\n-- after: one query per page\nSELECT * FROM line_items WHERE order_id = ANY($1::uuid[]);\n```",
          "B: Do you have the index on `order_id`? Last time we shipped that pattern without it the planner did a seq scan and made it worse.",
          "A: Index exists, checked with EXPLAIN ANALYZE. p95 drops from {ms} to under 90ms locally with the seed data. Will confirm on {env}.",
        ],
        [
          "A: CI is at {hours} per PR now and people are starting to merge without waiting for it. Not great.",
          "B: Turborepo remote cache hit rate is only 31%. Half the misses are because `.env.example` is in the hash inputs for every package.",
          "A: Oh no. That's a one-line fix in `turbo.json` then.",
          "B: One line plus the part where we re-run everything once to warm the cache. I'll push it tonight, so tomorrow morning should be fast.",
          "C: Also, can we shard the Playwright suite? It's the single longest job, and we have the runners to spare. ~r",
        ],
        [
          "A: We're {pct} through the TypeScript strict migration. The long tail is files with `any` coming from the old fetch wrapper.",
          "B: What if we generate types from the OpenAPI spec and delete the wrapper? That kills about 200 `any`s at once.",
          "A: I like it but the spec drifts from reality in a few endpoints. We'd trade `any` for confident wrong types, which is worse.",
          "C: Then we fix the spec first. Contract tests against {env} would tell us exactly where it lies.",
          "A: OK, plan: contract tests, fix the spec, then codegen. I'll write it up in {wiki}.",
        ],
        [
          "A: Webhook retries design question. If the consumer returns 500, do we retry with exponential backoff and jitter, or fixed intervals?",
          "B: Exponential with jitter, capped at around 6 hours, and stop after 24h. Fixed intervals make thundering herds when a customer's endpoint comes back.",
          "A: And idempotency: we send an `event_id`, consumers should dedupe on it. Do we document that or enforce it?",
          "B: Document it loudly and include it in the header, not just the body. Enforcing is their problem, but we can offer a replay endpoint.",
          "C: Replay endpoint, yes please. Support gets asked for it twice a week. ~rx:👍",
        ],
        [
          "A: Renovate opened a major bump for the framework. Changelog is 40 pages. Anyone brave?",
          "B: I'll take the first pass. Codemods cover most of it, it's the changes to the router behaviour that scare me.",
          "A: Do it on a branch with the preview env so QA can poke around. I'd rather find the weirdness in {env} than in prod.",
          "B: Will do. Estimate: {n} days if the tests are honest, {n2} if they're lying.",
          "A: They are mostly honest. Except the {problem}, ignore that one. 😅",
        ],
        [
          "A: Pagination. Offset or cursor for the new activity feed?",
          "B: Cursor. Feeds get new rows at the top while you scroll, so offset gives duplicates and skips.",
          "C: Counterpoint: support wants 'jump to page 20' for the audit log viewer. Cursor can't do that.",
          "B: Fair. Different endpoints, different answers: cursor for the feed, offset with a hard cap of 10k rows for the audit log.",
          "A: Writing it into the API guidelines so the next person doesn't relitigate it. ~r2",
        ],
        [
          "A: The {problem} in checkout is back. It fails roughly 1 run in 15, always on the payment step.",
          "B: I looked at the trace. The test clicks 'Pay' before the Stripe iframe finishes mounting. We're waiting on the wrong selector.",
          "A: So the app is fine and the test lies. Fix?",
          "B: Wait for the iframe's `ready` event instead of a fixed 500ms sleep. Pushed, running it 200 times to be sure. ~img:Playwright trace viewer",
          "A: Love a root-cause fix that deletes a sleep.",
        ],
        [
          "A: The generated client is out of sync again. `pnpm gen:api` creates a 600-line diff on a clean checkout.",
          "B: Somebody regenerated with a different generator version. Pin it in `package.json` and add a CI step that fails if the generated dir is dirty.",
          "A: Yes. And a comment at the top of the generated files saying DO NOT EDIT, because I know at least one person has.",
          "C: It was me, once. In my defence the comment wasn't there. 🙈 ~file:openapi-diff-report.txt",
        ],
        [
          "A: Planning the migration to split `users.full_name` into first and last name. Expand/contract, right?",
          "B: Yes. Step 1: add nullable columns, dual-write. Step 2: backfill in batches. Step 3: switch reads behind `{flag}`. Step 4: stop writing the old column. Step 5: drop it, weeks later.",
          "A: The backfill on {big} rows worries me. Batch size?",
          "B: 5k per batch with a short sleep, and run it off-peak. I'll put the loop in the runbook so it's resumable.",
          "A: ```sql\nUPDATE users SET first_name = split_part(full_name, ' ', 1)\nWHERE id IN (SELECT id FROM users WHERE first_name IS NULL LIMIT 5000);\n```\nThis is the core of it, but names with a single token will need a rule.",
          "B: Mononyms, yes. Put the whole name in `last_name` and leave first empty. Product agreed to that last week.",
        ],
        [
          "A: Sentry is {pct} noise right now. The top issue is a `ResizeObserver loop limit exceeded` that is, famously, harmless.",
          "B: Filter it at the SDK level with `ignoreErrors`, but let's not blanket-ignore stuff. Reviews of the ignore list in the {meeting}?",
          "A: Agreed. I'd also like alerts to fire on new issue regression only, not on every spike.",
          "B: Setting that up. Alert fatigue was the reason nobody noticed the real checkout error last week.",
        ],
      ],
      standup: [
        [
          "A: **Yesterday**: reviewed {pr}, fixed the {problem} in the {component}\n**Today**: pair with {B} on {task}, write tests for the retry path\n**Blockers**: waiting on a staging deploy, the pipeline is queued behind {n} others",
        ],
        [
          "A: Yesterday: {task} is code-complete, needs a reviewer who understands the billing proration. Today: docs for the {deliverable}. No blockers, mild existential dread about the flaky suite.",
          "B: I'll take the review after lunch. ~r",
        ],
        [
          "A: standup:\n- merged {pr}, behind `{flag}` at 5% in {env}\n- today: watch the dashboards, start {task2}\n- blocked: none",
          "B: 5% to who? Internal only or real users?",
          "A: Internal plus a handful of beta accounts. 100% internal stays on until Thursday.",
        ],
        [
          "A: Heads up, I'm in the {meeting} until noon. Yesterday: finished the CSV import parsing, found out Excel exports with BOMs. Today: handle encodings properly. Blockers: none.",
          "B: BOMs. Every time. Test with a file saved from Excel on Windows and one from Numbers. ~rx:😂",
        ],
        [
          "A: Yesterday I did mostly review (4 PRs) and one deploy rollback. Today I'm writing the postmortem for that rollback and then {task}. Blocked: I need a decision on {task3} scope before I can start.",
          "M: Tell me the two options and I'll decide by {time}. ~r",
          "A: Thanks. Option 1 is the minimal version in the ticket; option 2 adds the bulk action. Option 1 is {n} days faster.",
        ],
        [
          "A: **Daily**\n✅ {task}: shipped to {env}\n🔧 {task2}: debugging a {problem}\n❌ {task3}: not started, I'm borrowing the time for the incident follow-ups",
        ],
        [
          "A: Yesterday: dependency bumps, then spent two hours learning that a transitive package got yanked from the registry. Today: vendoring a replacement. Blocker: none, just regrets.",
          "B: 😬 lockfile PRs are going to be fun. Ping me if you want a second pair of eyes.",
          "A: Will do, thanks. {B} you're a hero. ~rx:🙏",
        ],
      ],
      blocker: [
        [
          "A: Blocked on {task}: the `{flag}` flag keeps resetting to off in {env}. Somebody is toggling it from a script.",
          "B: That's the nightly e2e job. It resets flags to a baseline, and the baseline predates your flag.",
          "A: Can we add per-flag overrides to that script, or exclude `{flag}`?",
          "B: Adding an override file now, 15 minutes.",
        ],
        [
          "A: Staging has been broken since {time}: the migration `{sha}` failed halfway and now the app won't boot. Pipeline is red for everyone.",
          "B: I see it, the migration holds a lock because a long-running report query is open. Killing the query.",
          "A: Thanks. Can we get a rule that blocks migrations from running while analytics queries are active on that table? That's the third time.",
          "M: Please write that up as an action in the retro, with an owner. I'll chase it. ~r",
        ],
        [
          "A: I can't finish {task} until the {team} publishes the new auth scopes. The spec says Q-end, my feature ships before.",
          "B: Is there a mock you can code against? The scopes are fixed, it's only the publish date that is open.",
          "A: Yes, a fake scope provider behind an interface. Feels dirty but it unblocks me. Doing it, with a hard-dated ticket to swap.",
        ],
        [
          "A: Escalating: design hasn't signed off on the {feature} empty states for two weeks and the sprint ends {day}. Engineering is idle on this stream.",
          "M: Understood. I'll get {@B} and the design lead in a room tomorrow morning. In the meantime, ship what's agreed and keep the rest behind the flag.",
          "A: Good. We'll ship with placeholder copy and swap it later. ~r",
        ],
        [
          "A: Does anyone have prod read access to the `billing_events` table? I need one customer's invoice rows to reproduce {ticket} and my request has been in the queue since Monday.",
          "B: Access reviews are slow right now because of the audit. I can run the query for you and paste redacted rows.",
          "A: That works, thanks. The invoice ID is in the ticket, I need `created_at`, `status` and `retries`.",
          "B: ```\nid        | status | retries | created_at\ninv_8821  | failed | 4       | 02:11:09\ninv_8821  | paid   | 0       | 02:44:50\n```\nSo it failed 4 times and then succeeded, which explains the duplicate email.",
        ],
        [
          "A: The code freeze for the {meeting} demo is tomorrow and the {component} PR still has {n} unresolved comments from {B}. I don't want to merge over objections.",
          "B: Honestly most of them are style. The one that matters is the missing transaction around the two writes. Fix that and I'll approve.",
          "A: Fair. That's a real bug, not style. On it, back with a push within the hour.",
        ],
        [
          "A: Third-party maps SDK just announced the old API key format stops working on {date}. We have {n} places using it.",
          "B: Do we know which ones are in prod paths?",
          "A: Checkout address autocomplete and the store locator. Both in prod. I'll have a migration PR ready tomorrow but I need someone from {team} to rotate the keys.",
          "C: I'll do the rotation. Send me the list of environments and which scopes each needs.",
        ],
      ],
      decision: [
        [
          "M: Decision needed on the search rewrite: keep Postgres full-text for another quarter or move to a dedicated search engine now?",
          "A: My take: stay on Postgres for now. Index size is {n} GB, query volume is modest, and a new datastore means a new on-call surface.",
          "B: The ranking quality is what product complains about. Postgres FTS can't do typo tolerance well.",
          "A: Then trigram extension plus a synonyms table gets us 80% of the way. We revisit when the data hits ~50 GB or latency passes {ms}.",
          "M: Decision: stay on Postgres, add trigram, revisit at the thresholds above. Writing it into the decision log. ~pin:Decision ~rx:👍|✅",
        ],
        [
          "A: ADR proposal: all new services use OpenTelemetry for traces, no more vendor SDKs directly. Objections?",
          "B: Fine for new services. What about existing ones?",
          "A: Migrate opportunistically, when you touch the service anyway. No big-bang.",
          "C: +1 from SRE. One collector config to maintain instead of four. ~rx:👍|✅",
        ],
        [
          "A: We need to pick the branching model for the release train: trunk-based with flags, or release branches?",
          "B: Trunk-based. Release branches mean cherry-picks, and cherry-picks mean bugs.",
          "C: I like trunk but we have the enterprise customers who need a long-lived stable version.",
          "M: Compromise? Trunk for the web app, release branches only for the on-prem package. Does that cover it?",
          "A: Yes. Decision recorded. ~pin:Decision ~rx:✅",
        ],
        [
          "A: Deprecation call: we sunset API v1 on {date}. Usage is down to {pct} of traffic, concentrated on {n} customers.",
          "B: I'd keep a six-month notice, with brownouts at 12 and 4 weeks out so people actually notice.",
          "C: Support is fine with that if we send the migration guide and name a contact per customer.",
          "A: Agreed. Brownouts: 5 minutes, off-peak. I'll draft the notice. ~rx:👍|✅",
        ],
        [
          "A: Do we adopt a monorepo for the mobile and web clients? {B} wrote up the trade-offs in {wiki}.",
          "B: Short version: shared types and one CI, versus bigger clone times and mixed ownership. I vote yes if we get code owners and path-filtered CI.",
          "C: Fine as long as mobile can still release independently.",
          "A: They can, we release from tags per package. Going ahead, migration starts next sprint. ~rx:👍",
        ],
        [
          "M: Quick call: we're {pct} through the error budget this quarter. Pause feature work for a reliability sprint, or ride it out?",
          "A: Error rate is concentrated in two endpoints. I'd fix those in the next sprint alongside features, not stop everything.",
          "B: I'd rather take a hard line. Last quarter 'alongside' meant never.",
          "M: Middle path: reliability work gets 40% of the next sprint, protected, tracked in its own epic. Revisit at the {meeting}. ~pin:Decision ~rx:👍|✅",
        ],
        [
          "A: Coverage gate: should CI fail when coverage drops by any amount, or only below an absolute floor?",
          "B: Absolute floor of {pct}, plus a per-PR rule: new code must be at least 80% covered. Deltas are noisy.",
          "A: OK with that. Patch coverage only, using the diff, not the whole file.",
          "C: Sounds sane. 👍 ~rx:👍|✅",
        ],
      ],
      launch: [
        [
          "A: Launch checklist for {feature}, going out {day}:\n- [x] `{flag}` configured, default off\n- [x] dashboards and alerts live\n- [x] rollback plan in {runbook}\n- [ ] support briefed\n- [ ] changelog entry\nRamp plan: 1% → 10% → 50% → 100%, 30 minutes between steps.",
          "B: Support briefing is at {time}, I'll confirm after.",
          "A: Thanks. Go/no-go at {time2}? I'll post the call in this channel. ~r",
        ],
        [
          "A: 🚀 `{flag}` is live at 1%. Error rate is flat, {metric} is within noise. Watching the next 30 minutes.",
          "B: Confirming from the SRE side, no alerts. Dashboard: {dash}",
          "A: Moving to 10%. ~rx:🚀|🎉",
        ],
        [
          "A: Ramp update: 50%. One new Sentry issue, a null deref in the receipt component. Fix is a one-liner, shipping now. Holding at 50% until it's out.",
          "B: Verified the fix in {env}, go.",
          "A: Fix deployed, resuming the ramp.",
          "A: 100% 🎉 Great work everyone, especially {B} for the load test that caught the connection pool issue last week. ~rx:🎉|🚀",
        ],
        [
          "M: Release announcement for {ver} is going out at {time}. Please make sure your changelog entries are in by {time2}. Reminder that anything not in the notes doesn't get a customer mention.",
          "A: Mine's in. Added a section on the new webhook headers because that is the part customers will actually trip on.",
          "B: Mine is up too. Highlights: {feature}, faster search, the export fix everyone asked about. ~rx:🎉",
        ],
        [
          "A: Cutover plan for the new billing service, {date}:\n1. Freeze billing writes (2 min)\n2. Final sync from legacy to new\n3. Flip `billing-v3-read` to 100%\n4. Smoke test with the {cust} sandbox tenant\n5. Unfreeze\nRollback = flip the flag back, legacy stays authoritative for 7 days.",
          "B: Added a verification query to step 4 so we compare invoice totals for the last 24h between old and new.",
          "M: I'll run comms to finance, they need to know about the two-minute freeze. Who is on call? ~r",
          "A: {B} is primary, I'm secondary. Phones on loud. ~rx:🚀",
        ],
        [
          "A: Post-launch, day 1: adoption of {feature} is at {pct} of eligible accounts, support tickets up by {n}, mostly 'where did my button go'. Nothing broken.",
          "B: Let's add a one-time tooltip pointing to the new location. Cheap and it'll cut those tickets.",
          "A: Doing it as a follow-up behind its own flag. Thanks for the clean launch, everyone. 🎉 ~rx:🎉|🚀",
        ],
        [
          "A: Dark launch finished: the new search indexer has been shadow-reading production traffic for a week. Result agreement with the old one: {pct}. The differences are mostly ranking ties.",
          "B: I looked at 100 of the mismatches. About 90 are tie-breaking order, 7 are real recall gaps, all in documents with special characters.",
          "A: Fixing the tokenizer for those, then we flip it for internal users and go from there. 🚀 ~rx:🚀|🎉",
        ],
      ],
      chatter: [
        ["A: Can someone approve {pr}? It's a one-line copy fix and I'm tired of looking at it."],
        ["A: Who owns the {component}? Asking for a very specific bug.", "B: Nominally the {team}. Actually {C}. Practically anyone who touched it last, so... you. 😅"],
        ["A: Is anyone else's local env refusing to start since the lockfile bump?", "B: Delete `node_modules` and the Turbo cache, it fixed mine.", "A: Back in business. {thanks}"],
        ["A: Reminder that `main` is not a feature branch. Please. ~rx:😂"],
        ["A: Does anyone remember why we have a 1337ms timeout somewhere in the {component}?", "B: Someone's joke from 2022. It's tested now, so no one dares touch it. 🙃"],
        ["A: Merge queue is huge today, {n} PRs. Is that normal?", "B: Friday before a release. It's always like this."],
        ["A: What's the command to run only the changed packages' tests again?", "B: `pnpm turbo test --filter=...[origin/main]`", "A: 🙏"],
        ["A: Naming bikeshed: `userId` or `user_id` in the JSON API?", "B: snake_case in the API, camelCase in the client, mapper in between. Settled in 2021, don't reopen. 😄"],
        ["A: Is {env} down for anyone or just me?", "B: Just you, I'm in. Clear cookies, your session token was probably issued before the rotation."],
        ["A: Hot take: half our unit tests test the mock.", "B: The other half test the framework. 😂 ~rx:😂"],
        ["A: Who broke the build? 🕵️", "B: Checking... it was me, I forgot to commit the generated types.", "A: Honest and fast, we'll allow it."],
        ["A: Anyone have a good reading on how Server Components handle auth context? I keep confusing myself.", "B: Short answer: read the session in the server component, pass only what you need down as props, never the whole token."],
        ["A: Is the `{flag}` flag on in {env} right now?", "B: Yes, 25%. Check the LaunchDarkly dashboard before asking me, I'm not a flag oracle. Kidding, it's on."],
        ["A: Lunch bet: how many flaky tests exist in the repo? I say {n}.", "B: Higher. I'll say double that and I'm sad about it."],
        ["A: Can I get a review on {pr}? Small, I promise. ~rx:👀"],
        ["A: Does the preview env get torn down after merge?", "B: Yes, after 24h. If you need it longer, add the `keep-preview` label."],
        ["A: Anyone who touched the CSV importer: this is your reminder that Excel is not a database.", "B: Neither is Postgres at 3am but here we are. 😂"],
        ["A: Pairing slot at {time}? I'm stuck on the {problem}.", "B: Yes, send a link. Bring the {artifact}."],
        ["A: Who's on call this week?", "B: {C}. Primary rotation is pinned in the channel topic."],
        ["A: It's a good day when the PR description is better than the code. Thank you {B} for the screenshots. ~rx:🙌"],
        ["A: Is it normal for `pnpm install` to take {n} minutes?", "B: Not if you're on the office wifi, try the wired dock."],
        ["A: Reminder: the {meeting} is moved to {time}. Bring your questions about the {deliverable}.", "B: 👍"],
        ["A: Can we stop using `utils.ts` as a folder name? It's where code goes to die.", "B: Proposing `lib/` with real names. Open an ADR, I'll second it."],
        ["A: Typo in the release notes: it says 'sear' instead of 'search'. Fixing it before it goes out. 🙈", "B: Looks like a fish feature. 🐟 ~rx:😂"],
      ],
      incident: [
        [
          "A: 🚨 Elevated 5xx on the {component} since {time}. {pct} of requests failing. Declaring an incident, I'm IC.",
          "B: Looking at traces: connection pool exhausted on the orders DB. A new query holds connections open.",
          "A: Is it from the {ver} deploy?",
          "B: Yes, the deploy timing lines up exactly. Rolling back now.",
          "B: Rollback done. Errors are dropping. I'll hold the incident open for 30 minutes for confirmation.",
          "A: Thanks. Status page updated. Postmortem owner is me, draft by {day}. ~r",
        ],
        [
          "A: Customer-reported: some users are seeing other people's saved filters. Possible cache key collision. This is a P1 until proven otherwise.",
          "B: Looking. The cache key doesn't include the tenant ID for the new endpoint. I see it, the key is just the filter name.",
          "A: Disable `{flag}` now, we'll fix forward.",
          "B: Flag off. Cache purged. No new reports in the last 5 minutes.",
          "M: I'm looping in security and legal. {A}, please list how many users and what data could have been exposed. I'll own the customer comms. ~r2",
          "A: On it. Preliminary: {n} users, filter names only, no PII beyond that. Full analysis in an hour.",
        ],
        [
          "A: Deploys are stuck: the pipeline can't pull images, registry returns 429s.",
          "B: We're rate-limited because someone's script is hammering it. Found it, a cron job that polls every second. Killing it.",
          "A: Pipeline's moving again. Please add a pull-through cache for the registry, this is the second time.",
          "B: Ticketed, I'll prioritise it for the next platform sprint.",
        ],
        [
          "A: Search is returning stale results. New documents don't appear for 20+ minutes.",
          "B: The indexer consumer lag is at {big}. A poison message is blocking the partition and it keeps retrying.",
          "A: Move it to the dead-letter queue and let the rest drain.",
          "B: Done, lag is clearing. The message had a 3MB title field, no idea how.",
          "A: Add a size validation on ingest. And we should alert on consumer lag, not just errors. ~rx:🙏",
        ],
        [
          "A: Postmortem notes from last night's {ticket}. Timeline in {wiki}. Contributing factors: no canary on the config change, alert threshold too high, runbook out of date.",
          "B: One thing missing: the person on call didn't have access to the feature-flag console. Should be in the factors.",
          "A: Good catch, added. Action items: canary configs, lower the threshold, review runbooks quarterly, fix on-call access.",
          "M: Please assign owners and dates to each of those before we close this. I'll check at the {meeting}. ~pin:Postmortem actions",
        ],
      ],
    },
  },
  // ═══════════════════════════════════════════════════════════════════
  // MOBILE: iOS / Android app releases
  // ═══════════════════════════════════════════════════════════════════
  mobile: {
    lex: {
      env: ['TestFlight', 'the internal track', 'staging', 'the beta ring', 'QA', 'the preview build', 'the device farm'],
      feature: ['offline mode', 'biometric login', 'push notification preferences', 'in-app purchase flow', 'deep link routing', 'document scanner', 'home screen widget', 'dark theme', 'background sync', 'tablet layout', 'Apple Pay checkout', 'onboarding carousel', 'live activity', 'saved drafts'],
      component: ['networking layer', 'local database', 'push handler', 'navigation stack', 'image cache', 'sync engine', 'analytics wrapper', 'keychain wrapper', 'deep link router', 'payments module', 'settings screen', 'WebView bridge'],
      tool: ['TestFlight', 'Fastlane', 'Firebase Crashlytics', 'Xcode Cloud', 'Play Console', 'App Store Connect', 'Bitrise', 'Detox', 'Instruments', 'Android Studio profiler', 'Charles Proxy', 'BrowserStack', 'Sentry', 'Gradle'],
      problem: ['crash on cold start', 'ANR on the main thread', 'memory spike on image load', 'push token mismatch', 'keyboard overlapping the CTA', 'broken universal link', 'out-of-order sync', 'provisioning profile mismatch', 'R8 stripping a class', 'background task getting killed', 'layout break on small screens', 'WebView session loss'],
      metric: ['crash-free sessions', 'crash-free users', 'ANR rate', 'cold start time', 'app size', 'store rating', 'day-1 retention', 'push opt-in rate', 'adoption of the latest build', 'battery drain', 'OOM rate', 'frame drop rate'],
      deliverable: ['release candidate', 'store listing', 'release notes', 'privacy nutrition label', 'data safety form', 'screenshot set', 'test matrix', 'rollout plan', 'hotfix build', 'beta changelog', 'accessibility audit', 'migration plan for the local database'],
      team: ['iOS team', 'Android team', 'QA', 'release engineering', 'design', 'backend squad', 'growth', 'support', 'accessibility champions', 'platform team', 'analytics', 'legal'],
      device: ['iPhone SE (2nd gen)', 'iPhone 15 Pro', 'Pixel 7a', 'Galaxy A14', 'Galaxy S23', 'iPad mini', 'Pixel Fold', 'a three-year-old Redmi', 'iPhone 12 on iOS 16', 'Moto G Power'],
      store: ['App Store review', 'Play review', 'the expedited review queue', 'the phased release', 'the staged rollout', 'the TestFlight external group', 'the internal testing track', 'the closed beta track'],
      os: ['iOS 17', 'iOS 18', 'Android 13', 'Android 14', 'Android 15', 'iOS 16'],
    },
    pools: {
      work: [
        [
          "A: Offline mode design question. When the user edits a record offline and someone else edits it on web, do we last-write-wins or surface a conflict?",
          "B: LWW is silent data loss. For notes, maybe fine. For anything with money or status, no.",
          "C: Field-level merge for the easy fields, conflict sheet for the rest. We did that on the last app and users understood it fine.",
          "A: OK. I'll write the sync rules in {wiki}: per-field timestamps, server wins on conflicts for `status`, prompt on `amount`. ~r",
          "B: Add a test where the phone goes offline for three days. That's the case that always bites.",
        ],
        [
          "A: Crash-free sessions on {ver} is sitting at 99.2%, below our 99.5% target. Top crash is a null in the {component} on {os}.",
          "B: Crashlytics shows it only on devices with less than 3GB RAM. I suspect the image cache is being purged mid-render.",
          "A: Reproduced on {device} with the memory warning simulated. The cache hands back a recycled bitmap. Fix is a null guard plus not recycling manually.",
          "B: Ship it as a hotfix or wait for the next train?",
          "A: Next train is {day}. I'd say hotfix, it's 0.8% of sessions. Preparing the build. ~rx:👍",
        ],
        [
          "A: App Store review rejected {ver} under 5.1.1. They say our account deletion flow isn't discoverable enough.",
          "B: It's under Settings > Account > Delete. Two taps. They want it from the profile screen?",
          "A: Reviewer note says 'a link or button should be easy to find'. I'd rather add a visible row on the profile screen than argue.",
          "C: Agree, arguing with review costs days. Add the row, reply in Resolution Center with a screenshot, resubmit.",
          "A: Doing it now. Build {n} to TestFlight in an hour. ~img:Resolution Center reply draft",
        ],
        [
          "A: Cold start is {ms} on {device}. The target is 1.5s. Instruments shows we're initialising the analytics SDK, the keychain wrapper and three feature flag clients before the first frame.",
          "B: Lazy-load analytics after first render, the SDK doesn't need to be ready in the first 500ms.",
          "C: And the keychain read is synchronous. Move it off the main thread and show the skeleton screen while it resolves.",
          "A: Both done on my branch: cold start is now 1.3s on the slow device. Merging after review. ~rx:🎉",
        ],
        [
          "A: Deep links question for {feature}. Universal links fine on iOS, but Android App Links keep opening the browser instead of the app.",
          "B: Did you host `assetlinks.json` with the right SHA-256 for the Play signing key, not the upload key?",
          "A: ...the upload key. 🤦",
          "B: It's the first thing everyone checks and the last thing anyone thinks of. Play app signing means the cert Google signs with is different. Grab it from Play Console > App integrity.",
          "A: ```json\n[{\n  \"relation\": [\"delegate_permission/common.handle_all_urls\"],\n  \"target\": { \"namespace\": \"android_app\", \"package_name\": \"org.halcyon.app\",\n    \"sha256_cert_fingerprints\": [\"<play signing cert sha256>\"] }\n}]\n```\nUpdated and verified with the `adb` link check.",
        ],
        [
          "A: Push notifications: delivery rate on iOS is 91% and Android is 78%. That gap seems too big.",
          "B: Android OEMs killing background apps, probably. Also, we're sending high-priority messages for everything, FCM throttles that.",
          "A: Right, only chat and alerts should be high-priority. Promotional stuff should be normal priority.",
          "C: And don't forget stale tokens. We never prune invalid tokens on 404/UNREGISTERED responses. That alone could be 10% of sends.",
          "A: Adding token cleanup to the backend ticket. Will report the numbers a week after. ~r",
        ],
        [
          "A: Test matrix for {ver}: iOS 16/17/18 on SE, 15, 15 Pro Max. Android 12 to 15 on Pixel 7a, Galaxy A14, S23, Redmi. Anything missing?",
          "B: iPad. The tablet layout is in this release.",
          "A: Adding iPad mini and Pro 11. And foldables, since we claim to support them.",
          "B: We claim to support them. Do they work? Truthfully. 😅",
          "A: That's what the matrix is for. BrowserStack covers most, the Fold I'll test physically. ~file:test-matrix-release-candidate.xlsx",
        ],
        [
          "A: Local DB migration for the v{n} schema: adding a `synced_at` column and a new index. On large installs (200k rows) the migration blocks launch for 4 seconds.",
          "B: Do the migration in the background and let the app open on the old schema read-only until it's done?",
          "A: Complicated. Alternative: batch the index build and show a one-time 'Updating your data' screen with a progress bar.",
          "B: Users hate loading screens but they hate crashes more. Go with the progress screen and test the migration on a copy of a real heavy-user DB.",
          "A: Pulling a sanitized sample from support. Will test on {device} too since it's the slowest storage we have.",
        ],
        [
          "A: R8 broke the release build only: `ClassNotFoundException` for the payment SDK model classes.",
          "B: Missing keep rule. Debug builds don't minify so nobody saw it. Add this to `proguard-rules.pro`:\n```\n-keep class com.halcyon.payments.model.** { *; }\n```",
          "A: Fixed. And I'm going to make CI build and smoke-test the release variant, not only debug.",
          "C: Yes please. This is the third time a release-only issue reached QA. ~r",
        ],
        [
          "A: App size jumped from 48MB to 71MB. What happened?",
          "B: Bundled the new onboarding videos in the binary. They should be downloaded on demand.",
          "A: Moving them to on-demand resources and compressing the Lottie files. App Store thinning should bring the download size down further.",
          "B: Also check that we didn't ship all architectures in the Android bundle. App Bundle should split by ABI. ~img:App size breakdown by module",
        ],
        [
          "A: Accessibility audit of the checkout flow is done. Highlights: unlabeled buttons for VoiceOver, touch targets under 44pt, and Dynamic Type at the largest size cuts off the total.",
          "B: TalkBack has the same label problems plus the focus order jumps to the footer first.",
          "A: Filed {n} tickets, 6 are release blockers because they're legal exposure in some markets.",
          "M: Please attach the audit to the release checklist. The ones marked blocker go to the top of the sprint. ~r",
        ],
        [
          "A: Biometric login on Android: BiometricPrompt works, but on some Samsung devices the fallback to device credential returns the wrong result code.",
          "B: Known quirk. The device credential path returns `RESULT_CANCELED` on certain One UI versions even on success. Use `BiometricManager.canAuthenticate` with `DEVICE_CREDENTIAL` flags instead of inferring from the result.",
          "A: Will try that. Do we have a Samsung with the affected One UI version, or do I use a cloud device?",
          "B: Cloud device, ours is too new. BrowserStack has it.",
        ],
        [
          "A: Is the background sync even running on iOS? I see in the logs it runs once a day at most.",
          "B: iOS decides when `BGAppRefreshTask` runs. Don't promise freshness. Use silent push to trigger the sync when the server has changes.",
          "A: Silent push is rate-limited too, and delivery isn't guaranteed.",
          "B: Right. So: opportunistic sync on app open, plus silent push as a hint, plus a visible 'last synced' timestamp. Set expectations in the UI instead of fighting the OS.",
        ],
        [
          "A: Analytics events look wrong: `purchase_completed` fires twice on {device}. Revenue dashboards are inflated.",
          "B: Debounce on the receipt screen? The view appears twice during the Apple Pay sheet dismiss.",
          "A: Confirmed. Moving the event to the order confirmation callback instead of `viewDidAppear`.",
          "B: Tell data so they can correct historic numbers. ~rx:👍",
        ],
      ],
      standup: [
        [
          "A: iOS standup: {task} is in review, picked up {task2}. Waiting on a new provisioning profile for the push entitlement from {B}.",
          "B: Generating it now, check Apple Developer in 10 minutes.",
        ],
        [
          "A: Android: fixed the {problem} in the {component}, trying a Gradle cache fix for build times (clean build is 9 min). Today: {task}. No blockers.",
        ],
        [
          "A: Yesterday: release candidate for {ver} went to the internal track, smoke tests are green. Today: waiting for QA sign-off, then submit. Risks: Apple review has been taking 2 days lately.",
          "B: QA: 3 open bugs, one is a blocker (tablet layout on iPad mini). Should be fixed today.",
          "A: I'll hold the submission until that's fixed. ~r",
        ],
        [
          "A: **iOS**\n- done: {task}, the widget extension builds in CI\n- today: widget timeline provider\n- blocked: none\n\n**Cross-team**\n- need an API field from backend for the widget (see {task2})",
        ],
        [
          "A: Spent yesterday chasing a crash that only happens on iOS 18.1 beta. Reported to Apple via Feedback Assistant. Today: workaround behind a runtime check, then back to {task}.",
          "B: Do we have the FB number? I'd like to link it in the ticket. ~r",
          "A: Pasted in {task}'s description.",
        ],
        [
          "A: Today: finishing the screenshot set for the new store listing (6.7\" and 12.9\" sizes), then localisation QA for {n} languages. Blocked on final French copy.",
          "B: Sent it to the translators, due tomorrow morning.",
        ],
        [
          "A: Yesterday: fixed {problem}, added unit tests. Today: crash triage, we have {n} new groups since the last build. Not blocked, just buried.",
          "B: I'll take half of the triage. Send me the Crashlytics links.",
        ],
      ],
      blocker: [
        [
          "A: Submission is blocked: App Store Connect says 'Missing compliance: export regulations'. Nobody on the team knows who owns the encryption declaration.",
          "B: That's legal. We've answered it before, the answer is 'uses standard encryption only, exempt'. Setting `ITSAppUsesNonExemptEncryption` to false in Info.plist will skip the prompt next time.",
          "M: I'll confirm with legal that the declaration is current and get it on record. {A}, go ahead and submit with the exemption. ~r",
        ],
        [
          "A: Android release is blocked. Play Console flags our `targetSdk` as too low, new updates won't be accepted after {date}.",
          "B: Bumping targetSdk means handling the new foreground service type restrictions and the notification permission.",
          "A: I know. It's a week of work minimum, mostly regression testing. Can we get QA time?",
          "M: Yes. Treat it as a hard deadline, I'll clear the QA capacity and move {task3} out of the sprint. Please send me a plan by tomorrow. ~r",
        ],
        [
          "A: TestFlight build is 'Processing' for 3 hours. Normal is 10 minutes.",
          "B: Apple status page shows a degraded App Store Connect. Nothing we can do except wait, or upload again.",
          "A: Re-uploading with a new build number just in case.",
          "B: Careful, you'll burn build numbers. They need to be monotonic. ...but yes OK, do it.",
        ],
        [
          "A: Need a signing certificate renewed. The distribution cert expires in {n} days. The account holder is on leave.",
          "B: Who else has the Admin role in the Apple Developer account?",
          "A: Only them. We have a process gap there.",
          "M: Thanks for flagging early. I'll get a second admin added through the company account owner today. Action item for the retro: document cert ownership and expiry dates in {wiki}.",
        ],
        [
          "A: Blocker for {feature}: the backend endpoint returns 400 for the new payload on {env}, but only from the mobile app. Web works.",
          "B: Mobile sends the date as `2025-01-01T00:00:00` without a timezone, backend wants ISO with offset.",
          "A: I'll fix it in the app. Can the backend also be lenient? We have old app versions out there for months.",
          "C: We can't change that now without breaking the validation contract. App fix plus a forced-update gate for versions older than {ver}.",
        ],
        [
          "A: Our only physical {device} test phone died. Charging port gone. We can't repro the bug on real hardware.",
          "B: There's one in the IT drawer. I'll bring it tomorrow. In the meantime use the BrowserStack session for {device}.",
          "A: Cloud device won't reproduce a thermal throttling issue. I'll wait for the real one.",
        ],
        [
          "A: Rejected on guideline 4.3 (spam), because the reviewer thinks our white-label app duplicates our main app.",
          "B: Ugh. That's a known risk. Do we have the written justification for the white-label setup?",
          "A: Yes in {wiki}. I'll appeal with it and attach the distinct bundle IDs, the customer contract and a screen recording of the differences.",
          "M: Good. Please also ask for a call with App Review if the appeal fails. I can escalate through our Apple account contact. ~r",
        ],
      ],
      decision: [
        [
          "M: Decision: min supported OS. Usage shows {os} is at {pct} of installs. Supporting older versions costs us roughly {n} days per release in testing. Proposal?",
          "A: Drop iOS 16 in the next release. It's under 3% and Apple's own requirements are moving.",
          "B: Android side: keep API 26+ for now, a lot of our enterprise customers run older Samsung devices.",
          "M: Decision: drop iOS 16 in {ver}, keep current Android floor, revisit in two quarters. Announcing it in the release notes. ~pin:Decision ~rx:👍|✅",
        ],
        [
          "A: React Native versus native for the new onboarding flow? We need to ship in 6 weeks, the team has 2 iOS and 2 Android engineers.",
          "B: The rest of the app is native. A shared flow written once saves time, but the bridge costs us debugging pain.",
          "C: I'd keep it native. Onboarding is the first impression and it needs the best performance and accessibility.",
          "A: Native it is, with a shared spec and shared test cases so the behaviours match. ~pin:Decision ~rx:✅",
        ],
        [
          "A: Staged rollout plan: 1%, 5%, 20%, 50%, 100% on Play. Phased release on iOS (the 7-day default). Halt if crash-free sessions drops under 99.3%.",
          "B: And halt on any new top-3 crash group, even if the overall number is fine.",
          "A: Added. Rollout owner: me, back-up {B}. ~rx:👍|✅",
        ],
        [
          "A: Crash reporting: stay on Crashlytics or move everything to Sentry? We pay for both right now.",
          "B: Sentry has better release health and session replay for mobile now. Crashlytics is free and the integration is already everywhere.",
          "C: Keep Crashlytics for crashes, and use Sentry only for non-fatal errors and performance? That's double the SDKs though.",
          "A: Let's not. One SDK. I'll run a two-week comparison on the same builds and decide at the {meeting}. ~rx:👍",
        ],
        [
          "A: We should decide on forced updates. Old versions (below {ver}) are hitting a deprecated API that we want to turn off.",
          "B: A soft prompt first for two weeks, then a hard block. Always with a clear message and a store link.",
          "C: Support will get the angry tickets. Can we schedule the hard block for a Tuesday morning and not a Friday?",
          "A: Tuesday. Soft prompt on release day, hard block {n} weeks later. ~rx:✅",
        ],
        [
          "A: In-app purchase: use StoreKit 2 and Play Billing Library 7 with our own receipt validation server, or a third-party like RevenueCat?",
          "B: Buy, don't build. Receipt validation edge cases will eat us alive.",
          "C: Cost is a % of revenue. For our volume it's about {usd} a year. Cheaper than two engineers on maintenance.",
          "M: Agreed, go with it. {A}, please run security review for the data we send them. ~pin:Decision ~rx:👍|✅",
        ],
        [
          "A: Beta programme: open TestFlight link for anyone, or invite-only? Support has asked for an open link for customers who want early access.",
          "B: Open link means unpredictable devices and feedback noise. Invite-only with 500 slots, curated.",
          "A: Compromise: invite-only now, open the link after the first two weeks of the beta when we're stable.",
          "B: Fine. ~rx:👍",
        ],
      ],
      launch: [
        [
          "A: Release {ver} is approved by Apple! Releasing manually at {time} tomorrow so it lines up with the web launch. Android is at 5% staged rollout already.",
          "B: Marketing has the push campaign scheduled for {time2}. Do we have the version gate in place so older apps don't show the deep link and 404?",
          "A: Yes, the campaign only targets {ver} and up. ~rx:🚀",
        ],
        [
          "A: 🚀 {ver} is live on both stores. First hour: crash-free sessions 99.7% on iOS, 99.6% on Android. No new top crashes.",
          "B: Store rating is holding at 4.6. First review mentions {feature}, positively. ~rx:🎉|🚀",
        ],
        [
          "M: Launch day checklist for {ver}. Everyone: please confirm your piece in this thread. {A} release build + store, {B} QA sign-off, support macros, marketing push, analytics dashboards live. ~pin:Launch checklist",
          "A: Build, store listing and screenshots confirmed. Phased release is on.",
          "B: QA signed off on the last RC, no open blockers.",
          "A: Support macros are in Zendesk for the two likely issues. ~r",
          "M: Great. Go time. 🎉 ~rx:🚀|🎉",
        ],
        [
          "A: Hotfix {ver} submitted for expedited review. Fix for the {problem}. Apple usually approves within a few hours when we mention crash impact.",
          "B: Android hotfix is already on the production track at 20%. Crash-free sessions going back up.",
          "A: Approved! Releasing now. 🙏 ~rx:🎉",
        ],
        [
          "A: Rollout at 50%: crash-free sessions 99.6%, ANR rate 0.18%, adoption {pct} of weekly actives. All inside the guard rails. Moving to 100% tomorrow morning unless the overnight numbers move.",
          "B: One thing, the push opt-in rate dropped 3 points since the new prompt. Might be a coincidence, but I'd like to watch it.",
          "A: Tracking in the dashboard {dash}. We'll look at it again on {day}.",
        ],
        [
          "A: {feature} is in beta on TestFlight: 240 external testers. Release notes posted. Please push the link to your customer champions, but ask them to use the in-app feedback button, not email.",
          "B: Done for my accounts. Some of them asked about Android, ETA?",
          "A: Android beta follows in a week, the closed track is already set up. ~rx:🎉",
        ],
        [
          "A: Store listing update for {ver}: new screenshots, new subtitle, what's new text. Approved in the same review as the binary. Product page optimisation test starts {day}.",
          "B: The A/B test on icon colour? I've been waiting for that one. 👀",
          "A: Yes, variant B has the brighter teal. My bet's on A. ~rx:😂",
        ],
      ],
      chatter: [
        ["A: Who has the Pixel Fold? I need it for the layout check.", "B: In the drawer, it's at 12%."],
        ["A: TestFlight crash feedback is the best bug report ever: 'it broke'. And a screenshot of the home screen.", "B: A classic. 😂"],
        ["A: Does anyone remember the command for resetting the iOS simulator keychain?", "B: `xcrun simctl keychain booted reset`. You're welcome."],
        ["A: Apple review is fast today. Suspiciously fast. Probably a bot.", "B: Or it's Tuesday. They like Tuesdays. ~rx:😂"],
        ["A: Xcode just downloaded 12GB for a point release. Again.", "B: And my disk filled up. Delete old simulators: `xcrun simctl delete unavailable`."],
        ["A: Can someone approve {pr}? Android only, 12 lines, dependency bump.", "B: Looking."],
        ["A: Is it safe to bump the Kotlin version today or is it a bad omen?", "B: The Gradle plugin needs a bump too, set aside an hour."],
        ["A: What's the minimum OS for the widget? Asking for design.", "B: iOS 17 for the interactive version. The static one goes back to 16."],
        ["A: Reminder: please don't test on the production account with real payments. Last time I got a $400 receipt for a coffee. 🙈", "B: Use the sandbox tester accounts, they're in {wiki}."],
        ["A: How do I make the simulator pretend I'm offline?", "B: Network Link Conditioner, or turn off the Mac's wifi. Or `adb shell svc wifi disable` for the emulator."],
        ["A: Does the Samsung A14 in the matrix have an SD card? I need to test low storage.", "B: It does, and it's nearly full. Perfect low storage test bed."],
        ["A: App Store Connect logged me out again. Third time this morning.", "B: Apple ID two-factor, it's their way of saying hello."],
        ["A: Dark mode screenshots are perfect. Whoever did the status bar fix, thank you.", "B: It was {C}. ~rx:🙌"],
        ["A: Any word on the new build number scheme?", "B: Build number = CI run number, version from the tag. It's in the Fastlane config."],
        ["A: Reviewer on the Play side asked why we need the `READ_PHONE_STATE` permission.", "B: We don't. It came with an old SDK. Removing it."],
        ["A: It's a good day when crash-free users has two nines and a five. Don't jinx it.", "B: Noted. Not looking. 🙈"],
        ["A: Who knows how the iPad split view handles our modal sheets?", "B: Badly, filed {task}."],
        ["A: Pizza for the release crew at {time}? Asking for the sake of morale.", "B: Pizza solves 60% of release problems. The other 40% need Fastlane. 🍕"],
        ["A: How many languages are we localised in now?", "B: {n}. Arabic RTL still has a few layout bugs, tracking in the board."],
        ["A: Has anyone seen the Android Studio emulator eat 16GB of RAM?", "B: Yes. Cold boot it and reduce the heap size. Or buy more RAM. 😅"],
        ["A: The QA phone shelf looks like a museum of technology. Can we update the lineup?", "B: Budget request submitted. Wish us luck."],
        ["A: Does the release train leave at {time} on Thursday or earlier?", "B: Branch cut Wednesday EOD, so Thursday is stabilisation only."],
        ["A: I just learned that Apple Pay sandbox cards expire. Ask me how.", "B: How? 😂", "A: Debugged for an hour. Don't ask again."],
        ["A: Fastlane lane `beta` is red. Looks like an expired API key.", "B: Rotating it, give me 10."],
      ],
      incident: [
        [
          "A: 🚨 Crash spike on Android: crash-free sessions fell from 99.6% to 97.1% in the last 2 hours. All on {ver}, on {os}.",
          "B: Stack trace points at the WebView bridge. Chrome WebView auto-updated this morning and something changed in how we inject JS.",
          "A: Can we pause the staged rollout?",
          "B: Paused at 20%. Working on a fix that uses the new injection API, with a fallback for older WebViews.",
          "M: Who owns support comms? Please post a short notice in the help centre and tell the account managers what to say. ~r",
          "A: Done, hotfix build is in QA, ETA {time}.",
        ],
        [
          "A: Push notifications aren't arriving for iOS users since {time}. Reports from {n} customers.",
          "B: The APNs certificate expired. Nobody had the renewal on their calendar.",
          "A: Do we have the auth key approach (.p8) set up as backup?",
          "B: No, only the cert. I'm generating a key now and switching the backend to token-based auth, which never expires. ~r",
          "A: Pushes flowing again. Adding cert expiry monitoring to the list. ~rx:🙏",
        ],
        [
          "A: Users on {ver} can't log in: they get an endless spinner after biometric success. Support is flooded.",
          "B: The token refresh returns 401 and the app retries forever without backoff. The backend deployed a change to the refresh endpoint at {time}.",
          "A: Backend can roll back faster than we can ship an app. {C}?",
          "C: Rolled back the refresh endpoint. Spinner should clear within a minute.",
          "A: Confirmed fixed. App fix for unbounded retry is next, otherwise we'll repeat this. ~r",
        ],
        [
          "A: Payments are failing for Apple Pay users on {ver}, error 'merchant validation failed'. About {pct} of iOS checkouts.",
          "B: The merchant identity certificate expired overnight.",
          "A: Do we have the renewal CSR?",
          "B: Yes, I generated it last month, it's in the vault. Uploading to the Apple Developer portal and the payment processor now.",
          "A: Checkout success rate recovering. Postmortem: certificate inventory with expiry alerts for everything. ~rx:🙏",
        ],
        [
          "A: Weird one: some users' offline edits are disappearing after sync. Support has {n} reports.",
          "B: I see it: the sync engine drops pending changes older than the last server cursor on conflict. A bug I introduced in {pr}.",
          "A: Can we recover the lost edits?",
          "B: The local DB keeps a change log for 7 days. I can ship a build that replays from it. Priority one.",
          "M: Please stop the rollout until the fix is out, and tell me how many users are affected so I can brief leadership. ~r",
          "A: Rollout halted. Affected: {n} users, details in {tracker}.",
        ],
      ],
    },
  },
  // @@NEXT
};
