/** Kind libraries (extra 2): marketing, design, operations. Contract: ./chat-dsl.ts */
import type { KindLib } from './chat-dsl';
import type { ProjectKind } from '../schema';

export const KINDS_E2: Partial<Record<ProjectKind, KindLib>> = {
  marketing: {
    lex: {
      feature: ['the launch landing page', 'the nurture email sequence', 'the webinar series', 'the case study programme', 'the partner co-marketing kit', 'the paid social campaign', 'the localised homepage', 'the brand refresh', 'the lifecycle journey', 'the event microsite'],
      component: ['the HubSpot workflow', 'the lead scoring model', 'the UTM taxonomy', 'the content calendar', 'the Contentful model', 'the email template', 'the attribution dashboard', 'the ad account structure', 'the consent banner', 'the press kit'],
      tool: ['HubSpot', 'Salesforce', 'Contentful', 'Figma', 'Google Analytics', 'Segment', 'Canva', 'Semrush', 'Asana', 'Mailchimp'],
      problem: ['a broken UTM on the paid links', 'a typo in the subject line', 'a form that drops the consent field', 'a duplicate send to the VIP list', 'an off-brand colour in the deck', 'a localisation gap in the German page', 'a landing page that loads in 6 seconds', 'an unapproved claim in the copy', 'a lead routing rule gone wrong', 'a webinar link that 404s'],
      metric: ['marketing-sourced pipeline', 'cost per lead', 'MQL to SQL rate', 'open rate', 'click-through rate', 'webinar attendance', 'conversion rate', 'share of voice', 'sign-ups', 'CAC'],
      deliverable: ['the creative brief', 'the launch plan', 'the messaging framework', 'the campaign report', 'the press release', 'the sales enablement deck', 'the localisation pack', 'the content calendar', 'the budget tracker', 'the approvals log'],
      team: ['demand gen', 'brand', 'product marketing', 'content', 'lifecycle', 'PR', 'the agency', 'sales enablement'],
      vendor: ['the creative agency', 'the video studio', 'the translation vendor', 'the events partner', 'the PR firm'],
    },
    pools: {
      work: [
        ["A: Draft of {feature} is in {figma}. Looking for feedback on hierarchy and the headline.", "B: Headline is clever but unclear. Customers won't decode the pun.", "C: Agree. Try the benefit first, pun in the subhead.", "A: Revised in 10. Thanks."],
        ["A: {metric} for the last campaign: {pct} against a {pct2} target. Learnings?", "B: Strong top of funnel, weak follow-up. The nurture emails need a sharper call to action.", "A: Let's A/B the first two emails. I'll set it up in {tool}."],
        ["A: Brand guidelines reminder: the accent colour is for buttons and links only, not backgrounds.", "B: And please stop stretching the logo. I will find you. 😅", "A: Added a do/don't page in {wiki}."],
        ["A: Compliance flagged one claim in the copy: 'the fastest in the industry'. We need substantiation or it goes.", "B: We don't have independent benchmarks. Cut it.", "A: Cut. New line: 'built for speed'."],
        ["A: UTM taxonomy is a mess. We have {n} spellings of 'linkedin'.", "B: Enforce a dropdown in the builder and lock the rest. I'll clean historical data.", "A: Yes please, attribution reports are unreadable right now."],
        ["A: Localisation: German and French pages are due {date}. The vendor needs the final English by {day}.", "B: Copy is frozen as of today. Any change from here goes through me.", "A: Perfect."],
        ["A: Webinar registrations at {n} of {big}. Day-before reminder goes out at 9am.", "B: Add a calendar invite to the confirmation, that lifts attendance by 10 points.", "A: Already there."],
        ["A: Reminder that our press release embargo lifts {date} at 9am ET.", "B: Spokespeople are briefed. Q&A doc is in {wiki}."],
      ],
      standup: [
        ["A: Yesterday: finalised {deliverable}. Today: build the nurture sequence in {tool}. Need creative sign-off on the hero image."],
        ["A: Finishing the case study with {cust}. Their legal review is the last step.", "B: Writing the launch email and the social posts. First drafts by 3."],
        ["A: Standup: QA'ing links on the landing page. {n} issues so far, all minor."],
        ["A: Agency call at 11, then the budget review. Back online at 2."],
      ],
      blocker: [
        ["A: Blocked: the final product screenshots won't arrive until {day} but we send the creative to the agency tomorrow.", "B: Use the staging build for now and swap at the last minute. I'll ask design to keep the layout stable."],
        ["A: Legal hasn't approved the claims in the campaign copy. The launch is in {n} days.", "B: Escalating. If we don't have approval by {day}, we launch with the softer version.", "A: That's the plan."],
        ["A: The agency's invoice dispute is delaying the video edit.", "B: I'll talk to finance and get a purchase order sorted today."],
        ["A: Event venue cancelled on us, {n} weeks out.", "B: Backup venue is available, holds 20% fewer people. Cap registrations?", "A: Yes, and tell the VIPs first."],
      ],
      decision: [
        ["A: Go with the bold headline or the safe one for the homepage hero?", "B: Test both for a week, then commit.", "C: Agreed. Decision date is {date}.", "A: Locked in. ~rx:👍|✅"],
        ["A: Budget split: 60% paid, 25% content, 15% events. Approvals?", "B: Shift 5 points from events to content, the data supports it.", "A: Done. ~rx:👍|✅ ~pin:Decision: budget split"],
        ["A: Do we gate the whitepaper or leave it open?", "B: Open for the summary, gated for the full report.", "A: Ok. ~rx:👍"],
        ["A: Agency retainer vs project-based for next year?", "B: Retainer for design, projects for video. I'll draft the proposal.", "A: Good. ~rx:👍|✅"],
      ],
      launch: [
        ["A: Launch checklist for {feature}:\n- [x] landing page live\n- [x] emails scheduled\n- [ ] social posts queued\n- [ ] sales enablement call at 2pm", "B: Social posts queued as of now. 🎉", "A: We're go for 9am tomorrow. ~rx:🚀"],
        ["A: We're live! 🚀 First hour: {n} sign-ups and strong engagement on social.", "B: Reply to comments quickly in the first few hours, that's when the algorithm rewards you. ~rx:🎉|🙌"],
        ["A: Press release is out. Coverage already in {n} outlets.", "B: Sharing the links in {ch}. ~rx:🎉|📣"],
        ["A: Post-launch report on {day}: results, learnings and a list of things we'd do differently.", "B: Start the list now, memory is a liar. ~rx:👍"],
      ],
      chatter: [
        ["A: Who approved the stock photo of people laughing at salad?", "B: Marketing legend says it's from 2014 and nobody can delete it."],
        ["A: Our open rate is up {pct}. Subject lines with emojis seem to work.", "B: Don't tell the brand team. 😄"],
        ["A: Free coffee at the brand workshop on {day}.", "B: Free coffee is our top-performing campaign."],
        ["A: Does anybody have the hex code for the older blue?", "B: There is no older blue. There's only the blue.", "A: Of course. Sorry, brand."],
        ["A: New teaser for next week and I'm so excited I can't tell you anything.", "B: The best marketing is pure suspense. 👀"],
        ["A: Can someone proofread? I've read this headline {n} times and it's now just shapes.", "B: Sending corrections now."],
        ["A: {ack}, will add it to the calendar.", "B: 👍"],
        ["A: Our competitor just posted a new ad. Thoughts?", "B: Pretty. But the CTA is invisible.", "A: Noted for our own critique doc."],
        ["A: The offsite theme is 'Back to basics'.", "B: Which basics? Fundamentals or Excel?"],
        ["A: Quick poll: do we say 'sign up' or 'get started'?", "B: 'Get started'. It tests better.", "A: Done, thanks."],
        ["A: Friday: no meetings, only content. Will it last?", "B: No. But I respect the optimism."],
        ["A: The video turned out amazing. Nobody blinked in the whole take.", "B: Blinking is an acquired skill. ❤️"],
      ],
      incident: [
        ["A: Urgent: the newsletter went out with a placeholder subject line: 'TEST TEST'.", "B: Pulling the next batch. Sending a short apology in 20 minutes with the right subject.", "A: Drafted: 'Oops, wrong subject line, here's what we meant to send.' Approving.", "B: Out. Open rate on the follow-up is actually higher. 😂 ~rx:🙏"],
      ],
    },
  },
  design: {
    lex: {
      feature: ['the new component library', 'the design tokens', 'dark mode', 'the accessibility audit', 'the onboarding redesign', 'the navigation rework', 'the form patterns', 'the empty states', 'the icon set', 'the data table component'],
      component: ['the Button component', 'the date picker', 'the modal system', 'the colour palette', 'the typography scale', 'the spacing tokens', 'the Figma library', 'the Storybook', 'the tab bar', 'the toast pattern'],
      tool: ['Figma', 'Storybook', 'Style Dictionary', 'axe', 'Maze', 'Zeroheight', 'Chromatic', 'Playwright', 'FigJam', 'Notion'],
      problem: ['a contrast ratio below 4.5:1', 'a focus ring that disappears', 'a component with four variants nobody uses', 'a token mismatch between Figma and code', 'an icon exported at the wrong stroke', 'a truncated label in German', 'a modal that traps focus', 'a spacing inconsistency of 2px', 'a disabled state without a reason', 'an unlabeled icon button'],
      metric: ['component adoption', 'accessibility issues', 'handoff time', 'task success rate', 'SUS score', 'design debt count', 'usability findings closed', 'time to first design', 'Figma library coverage', 'bug count from design QA'],
      deliverable: ['the usage guidelines', 'the audit report', 'the research readout', 'the component spec', 'the migration plan', 'the token documentation', 'the prototype', 'the usability script', 'the release notes', 'the design critique notes'],
      team: ['design systems', 'product design', 'research', 'content design', 'front-end', 'QA', 'brand', 'accessibility'],
    },
    pools: {
      work: [
        ["A: Audit found {n} contrast failures on the primary palette. The brand blue fails on grey backgrounds.", "B: Darken it one step on small text and keep the original for large headings.", "C: Update the token and the docs, not just one screen.", "A: Doing it now. PR will include before/after screenshots. ~img:Contrast before and after"],
        ["A: Proposal: deprecate three of the four button variants. Usage data shows two are barely used.", "B: What replaces them?", "A: Primary, secondary, tertiary and destructive. Migration guide in {wiki}.", "B: Ok, announce with a 90-day sunset."],
        ["A: Research readout: {n} of 8 participants missed the secondary action on the form.", "B: Positioning or labelling?", "A: Both. The button looks disabled. We'll test a new treatment next week."],
        ["A: Handoff notes for {feature} are in {figma}. Spacing uses tokens only, no magic numbers.", "B: Great. One question about the empty state, is there copy for the error variant?", "A: Content design owns it, adding to the file now."],
        ["A: Figma and code tokens are out of sync again. Colours match, spacing doesn't.", "B: Generate both from the same source with Style Dictionary and stop hand-editing.", "A: That's the plan for the next sprint."],
        ["A: Component audit: {n} custom variations of the card across the product.", "B: Collapse them to two and make them composable.", "A: Yes, doing a pass with front-end this week."],
        ["A: Dark mode: do we invert the palette or design a separate set?", "B: Separate semantic tokens, mapped per theme. Never invert.", "A: Agreed. Docs go live on {date}."],
        ["A: Quick usability test next week, 5 participants, 30 minutes each. Who wants to observe?", "B: I'll join. Observers take notes, no talking.", "A: Sign up sheet in {wiki}."],
      ],
      standup: [
        ["A: Yesterday: finished tokens for {component}. Today: spacing audit. Blocked: waiting on engineering for the theme switch."],
        ["A: Running usability sessions all morning. Notes by EOD in {wiki}."],
        ["A: Documenting {component} usage guidelines. I'll share a draft by {day}.", "B: Reviewing {pr} for design QA. Found {n} spacing issues."],
        ["A: Out at the research recruiting call, back at 2."],
      ],
      blocker: [
        ["A: Blocked on {task}: the icon library has 3 sizes and engineering uses a 4th.", "B: Whose is canonical? We need to pick one.", "A: 24px as the default. I'll update the file today."],
        ["A: Can't finish the accessibility audit without a screen reader test on the iOS app, the device is booked.", "B: I'll lend mine until {day}."],
        ["A: Stakeholder wants a last-minute change after sign-off on {deliverable}.", "B: Log it as a change request with impact on the timeline. Let them decide the trade-off."],
        ["A: Engineering says the component can't support the animation without a rewrite.", "B: Ship without the animation and add it in the next iteration."],
      ],
      decision: [
        ["A: Which icon style for the system: outline or filled?", "B: Outline with a filled state for selection. Consistent with the stroke weight.", "A: Decision recorded in {wiki}. ~rx:👍|✅ ~pin:Decision: icon style"],
        ["A: Adopt 8px grid or 4px?", "B: 4px base unit, 8px for layout rhythm.", "C: Agree. ~rx:👍"],
        ["A: Do we support IE-level browsers for the new components?", "B: No. Evergreen only. Legal confirmed the contract doesn't require it.", "A: Done. ~rx:✅"],
        ["A: Brand wants rounded corners at 12px, design system uses 8px. Pick one?", "B: 8px for components, 12px for marketing surfaces.", "A: Great compromise. ~rx:👍"],
      ],
      launch: [
        ["A: Component library v2 released: {dash}. Migration guide in {wiki}. Office hours on {day}.", "B: Thanks to everyone who contributed. ~rx:🎉|🙌"],
        ["A: Dark mode ships Monday for the admin console, mobile follows in {n} weeks.", "B: Reminder to check your custom components, they won't theme themselves. ~rx:🚀"],
        ["A: The accessibility audit passed WCAG 2.2 AA with {n} minor notes. 🎉", "B: Months of work paid off. ~rx:🎉|👏"],
        ["A: Storybook is live and searchable. No more screenshot archaeology.", "B: Bookmarking. ~rx:🙌"],
      ],
      chatter: [
        ["A: Whoever made a 1px border at 99% opacity, I see you.", "B: Subtlety is a design principle."],
        ["A: Reminder that 'make the logo bigger' is not a design brief.", "B: Should that be on a mug?"],
        ["A: Critique rules: ask questions before giving opinions.", "B: And ban 'I like it'. Say why."],
        ["A: My cursor blinked at a different rate in dark mode, I'm convinced.", "B: Perfectionists unite. 😄"],
        ["A: Typography meetup tonight, anyone going?", "B: Me! Bringing opinions about kerning."],
        ["A: Who's got the good Figma plugin for renaming layers?", "B: Check pinned in {ch}."],
        ["A: {ack}, will update the file.", "B: 👍"],
        ["A: Spent 40 minutes on a drop shadow. It's now 4% darker.", "B: Worth it."],
        ["A: Can we agree placeholder text is not copy?", "B: Content designers just stood up and applauded."],
        ["A: User said 'this is intuitive'. I have framed the transcript.", "B: Frame it next to the one that says 'where is the button?'"],
        ["A: Component naming: 'Card' or 'Tile'?", "B: Card. Tile sounds like a bathroom."],
        ["A: Friday inspiration thread: post something beautiful.", "B: My plant. It's growing in a very pleasing way. 🌱"],
      ],
      incident: [
        ["A: Heads up: the new button style shipped with the wrong focus ring colour in production.", "B: Reproduced. Fix is a token change, PR in 15 minutes.", "A: Deployed and verified in staging. Will promote after review.", "B: Added a visual regression test for focus rings so it can't slip past again. ~rx:🙏"],
      ],
    },
  },
  operations: {
    lex: {
      feature: ['the new scanner workflow', 'the conveyor upgrade', 'the shift handover process', 'the safety checklist', 'the cycle counting programme', 'the dock scheduling system', 'the maintenance dashboard', 'the training academy', 'the cross-dock lane', 'the returns processing line'],
      component: ['the WMS interface', 'the sortation line', 'the dock doors', 'the handheld devices', 'the labelling station', 'the pick-to-light zone', 'the forklift fleet', 'the cold storage unit', 'the packing benches', 'the network at the site'],
      tool: ['SAP EWM', 'Power BI', 'ServiceNow', 'Zebra scanners', 'Honeywell devices', 'Excel', 'Teams', 'MES', 'Jira', 'the CMMS'],
      problem: ['a scanner firmware mismatch', 'a mislabelled pallet', 'a conveyor jam on line 3', 'a shift with missing training sign-off', 'a dock door double-booked', 'an inventory variance in aisle 14', 'a forklift charging bottleneck', 'a power glitch during cutover', 'a stock-out of labels', 'a safety near miss'],
      metric: ['throughput per hour', 'pick accuracy', 'on-time dispatch', 'lost-time injuries', 'inventory accuracy', 'dock-to-stock time', 'OEE', 'training completion', 'overtime hours', 'cost per order'],
      deliverable: ['the site readiness checklist', 'the cutover plan', 'the training schedule', 'the safety assessment', 'the layout drawing', 'the vendor schedule', 'the go-live criteria', 'the hypercare roster', 'the lessons-learned log', 'the SOP updates'],
      team: ['site ops', 'the night shift', 'maintenance', 'safety', 'logistics', 'IT on site', 'the vendor crew', 'HR'],
      site: ['the Rotterdam DC', 'the Austin hub', 'the Singapore warehouse', 'the Toronto facility', 'the Dubai depot', 'the Warsaw site'],
    },
    pools: {
      work: [
        ["A: Site readiness for {site}: {n} of {n2} checklist items closed. Remaining: network cabling and scanner pairing.", "B: Cabling crew is there Tuesday. Pairing is a half-day job.", "A: Good. Go/no-go at 4pm {day}."],
        ["A: Throughput on line 3 is {pct} of target since the sortation change.", "B: Jams at the merge point. Maintenance is adjusting the sensor gap.", "A: Update me at lunch, I'll warn the shift lead."],
        ["A: Training status: {pct} of the night shift is signed off, day shift at {pct2}.", "B: Block two more training sessions for nights this week.", "A: Done. Sessions on {day} and the next day."],
        ["A: Cycle count variance in aisle 14 is {pct}. Higher than usual.", "B: Likely mis-slotted items after the layout change. Counting again with a second person.", "A: I'll flag any item with repeat variance."],
        ["A: Safety walk found {n} items: blocked fire exit, a missing floor marking and an unlit stairwell.", "B: Fixing all three today. Photos in {wiki}.", "A: Appreciate it. Closing them out in the log."],
        ["A: Vendor crew arrives {day} for the conveyor install. Access badges are with security.", "B: I'll meet them at the gate and run the induction."],
        ["A: Peak season staffing: we need {n} temps by {date}.", "B: Agency has {n2} confirmed, searching for the rest.", "A: Shorten onboarding to one day with a buddy system."],
        ["A: New SOP for returns is live. Please walk your teams through it before shift start.", "B: Printed copies on the floor boards. ~rx:👍"],
      ],
      standup: [
        ["A: **Today at {site}:** cutover prep, {n} tasks. **Blockers:** waiting on scanner delivery. **Safety:** all clear."],
        ["A: Shift handover: line 2 down for 30 minutes (sensor), back online. Pick accuracy 99.4%.", "B: Night shift: no incidents, throughput on target."],
        ["A: Heads down on {task}, floor walk at 2pm."],
        ["A: Vendor onsite until 4. I'm the contact."],
      ],
      blocker: [
        ["A: Blocked: the conveyor parts are held at customs. Install is scheduled {day}.", "B: Escalating with the customs broker. We might need a different carrier.", "A: Let me know by tomorrow, I'll re-plan the install."],
        ["A: The WMS update window overlaps with peak shipping. IT won't move it.", "B: Request a one-day shift. I'll explain the revenue at risk.", "A: Thanks, I'll back you up."],
        ["A: Union consultation for the shift change isn't done and we planned to go live Monday.", "B: Don't go live without it. We'll slip a week.", "A: Understood, updating the plan."],
        ["A: Forklift battery chargers are insufficient for the new shift pattern.", "B: Rent {n} chargers for the peak. Purchase request in motion."],
      ],
      decision: [
        ["A: Cutover this weekend or after the peak? Risk vs. benefit.", "B: After the peak. A failed cutover during peak would cost more than waiting.", "A: Agreed. New date {date}. ~rx:👍|✅ ~pin:Decision: cutover date"],
        ["A: Hypercare staffing: 24/7 for 3 days then business hours for 2 weeks?", "B: Yes, with a daily 8am review.", "A: Done. ~rx:👍"],
        ["A: Do we train operators in classroom or on the floor?", "B: Floor, 70/30. Classroom is for safety.", "A: Ok. ~rx:✅"],
        ["A: Buy or lease the scanners?", "B: Lease with a refresh option, cash flow matters.", "A: Procurement to draft. ~rx:👍"],
      ],
      launch: [
        ["A: Go-live criteria for {site}: 98% pick accuracy, zero safety incidents in dry runs, all operators trained.", "B: Met all three. Go.", "A: Go-live Monday 6am. ~rx:🚀|🙌"],
        ["A: We're live! First shift: {n} orders processed with no stoppages. 🎉", "B: Congrats team. Hypercare is on the floor. ~rx:🎉|🚀|👏"],
        ["A: Cutover complete in {hours}, ahead of plan. Inventory reconciled to 99.9%.", "B: Huge effort by the night crew. ~rx:🎉"],
        ["A: Lessons-learned session Friday at 3. Bring one thing that worked and one that didn't.", "B: Coffee on me. ~rx:☕"],
      ],
      chatter: [
        ["A: Whoever labelled a pallet 'misc stuff', please see me.", "B: It was stuff. It was misc."],
        ["A: Free pizza at the end of the shift for hitting the safety milestone.", "B: Safe and fed. 🍕"],
        ["A: Who parked the forklift on the charging mat sideways?", "B: Maybe it parked itself."],
        ["A: Barcode scanners work better when they're charged. Revolutionary.", "B: We should put that on a poster."],
        ["A: Cold storage is 4°C. I'm wearing three jackets. Worth it.", "B: The hat is a lifestyle."],
        ["A: Shift lead of the month: Lucia. Lunch on us.", "B: Well deserved. ~rx:👏"],
        ["A: {ack}, will update the board.", "B: 👍"],
        ["A: Radio check, anyone on channel 3?", "B: Loud and clear."],
        ["A: New vending machine has real coffee. Break room is now a destination.", "B: Productivity will tank. 😄"],
        ["A: Reminder: hard hats in zone B, always.", "B: Zone B hates a bare head."],
        ["A: First forklift cert done! Next stop: speed limit ({n} km/h).", "B: Speed limits exist for a reason."],
        ["A: Photos of the new layout are on the board.", "B: It looks bigger. Is it?", "A: Same size. Better organised."],
      ],
      incident: [
        ["A: Safety alert: a pallet fell from the top rack in aisle 9. No injuries.", "B: Zone cordoned off. Inspecting the rack and the load.", "A: Cause: pallet was loaded past the rack rating. Retraining on load limits starts tomorrow.", "B: Report to the safety committee filed. ~rx:🙏"],
      ],
    },
  },
};
