/** Global channels (extra 1): announcements, random, wins, watercooler, engineering. Contract: ./chat-dsl.ts */
import type { GlobalChannelDef } from './chat-dsl';

const LEADERS = ['daniel', 'priya', 'tomas', 'hannah', 'ravi', 'elena', 'james', 'amara', 'kenji', 'sofia', 'oliver', 'nadia'];

export const GLOBAL_E1: GlobalChannelDef[] = [
  {
    name: 'announcements',
    topic: 'Company news from leadership. Read-mostly; discuss in threads.',
    size: 2,
    cast: LEADERS,
    castWeight: 0.92,
    depts: [],
    mix: [['posts', 10], ['reminders', 4], ['generic:release', 1]],
    pools: {
      posts: [
        ["A: **Q{n} results are in** 📈\n\nThank you all. Highlights:\n- Revenue up {pct} year over year, ahead of plan\n- Net revenue retention at {pct2}\n- Three of our five board initiatives are on track, two need attention (details at the all-hands)\n\nThe full recap and Q&A are in {wiki}. Proud of what this team delivered.", "B: Great quarter. Will the slides be shared after the all-hands?", "A: Yes, in {wiki} by end of day. ~r ~rx:🎉|👏|🙌"],
        ["A: **Welcome {@B}!** 👋\n\nPlease join me in welcoming {B} as our new {dept} lead, starting Monday. {B} joins us after {n} years in the industry and will focus on simplifying how our teams plan and deliver together.\n\nSay hello, and help them find the good coffee. ~rx:👋|🎉|❤️", "B: Thank you, {A}, I'm thrilled to be here. Looking forward to meeting you all!"],
        ["A: **Heads up: office changes in {city}** 🏢\n\nFrom {date} the {city} office moves to the new floor plan. Desks are booked via the app, and the old floor is closed for refurbishment. Facilities will host walk-throughs at {time} on {day}.\n\nQuestions go to #general or facilities@halcyon.example.", "B: Is parking changing?", "A: No change to parking. Details in the FAQ: {wiki}. ~r"],
        ["A: **Security reminder** 🔐\n\nPhishing attempts are up this month. Three simple rules:\n1. Never share MFA codes, with anyone, for any reason\n2. Report suspicious emails with the button in your mail client\n3. If something feels urgent and unusual, call the sender\n\nThank you for keeping Halcyon safe. ~rx:🔐|👍"],
        ["A: **Open enrolment is now open** 🩺\n\nBenefits enrolment runs until {date}. This year we've added:\n- Expanded mental-health coverage\n- A learning stipend of {usd} per person\n- More flexible parental leave\n\nVisit the benefits portal or book a 1:1 with People Ops. ~rx:🙌|❤️", "B: Is the stipend available for conferences?", "A: Yes, conferences and courses both. FAQ: {wiki}. ~r"],
        ["A: **Our values refresh** 🌱\n\nAfter {n} listening sessions, we've simplified our values to four: *Be curious, own the outcome, make it simple, look after each other.* Thank you for the {big} comments that shaped this.\n\nTeams will run a short workshop in the coming weeks. ~rx:🌱|👏"],
        ["A: **Product milestone** 🚀\n\n{proj} reached general availability this week. Months of work by {dept}, engineering and customer teams. If you're not sure how it helps you, #product-launches has the summary.\n\nThank you to everyone involved. ~rx:🚀|🎉|👏"],
        ["A: **Holiday calendar** 📅\n\nThe company holidays for next year are published: {wiki}. A reminder that we have a shutdown between {date} and {date2}. Please plan your customer commitments accordingly.", "B: Does the shutdown include the support team?", "A: Support runs a reduced rota. Schedules go out next week. ~r ~pin:Holiday calendar"],
        ["A: **Leadership update** 🧭\n\n{@B} is taking on an expanded role leading {dept}, and I'll step back from day-to-day delivery to focus on strategy. This change reflects what the business needs next. Reach out with questions, my door is open.", "B: Looking forward to it. Thank you for the trust. ~rx:👏|🙌"],
        ["A: **Town hall: {date}** 🎤\n\nSubmit your questions in advance: {wiki}. We'll cover the roadmap, hiring, and the move to the new planning process. Everything will be recorded.", "B: Can we ask about remote-work policy?", "A: Absolutely, add it to the form. ~r ~rx:👍"],
        ["A: **New learning programme** 📚\n\nThe Halcyon Academy launches next month with {n} courses on leadership, data literacy and project delivery. Registration opens on {date}. Managers: please encourage your teams to take time for it. ~rx:📚|🙌"],
        ["A: **Thank you, {city}!** 🙏\n\nOur {city} team handled the migration weekend with calm and professionalism. Customers experienced no downtime. Recognising {@B} and {@C} in particular for their leadership.", "B: A team effort, thank you. ~rx:👏|🎉"],
        ["A: **Sustainability update** 🌍\n\nWe've cut office energy use by {pct} compared with last year and moved all {city} deliveries to electric vehicles. Next up: a travel policy that reflects our targets. Details at {wiki}. ~rx:🌍|👏"],
        ["A: **Policy update: expenses** 💳\n\nFrom {date}, expenses under {usd} no longer need manager pre-approval. Receipts are still required. The updated policy: {wiki}.", "B: Thank you, this will save everyone time. ~rx:🙌"],
      ],
      reminders: [
        ["A: Reminder: performance goals for the next cycle are due {date}. Template and examples: {wiki}. ~rx:👍"],
        ["A: Reminder: all-hands is tomorrow at {time}. Link in your calendar. See you there!"],
        ["A: Reminder: mandatory security training closes {date}. It takes about 25 minutes. ~rx:👍"],
        ["A: Reminder: please submit your timesheets by {day} so finance can close the month on time."],
        ["A: Reminder: the {city} office is closed on {day} for a public holiday. Plan accordingly. ~rx:👍"],
      ],
    },
    intro: [["A: Welcome to **#announcements**. Leadership posts company news here. Please keep discussion in threads, and use #general for chat. ~pin:Read me"]],
  },
  {
    name: 'random',
    topic: 'Off-topic, memes, links and good news that has nothing to do with work.',
    size: 8,
    mix: [['fun', 10], ['generic:social', 4], ['generic:poll', 1], ['generic:ack', 1]],
    pools: {
      fun: [
        ["A: Unpopular opinion: pineapple on pizza is fine.", "B: Report this person to HR.", "C: The pineapple is optional, the controversy is mandatory. 😄", "A: I regret nothing. 🍍"],
        ["A: Just learned that octopuses have three hearts. Lunchtime fact of the day.", "B: Three hearts and still no work-life balance."],
        ["A: Best podcast for a long commute? I've run out.", "B: Anything with a murder mystery and a tangent about gardening.", "C: I'll send a list."],
        ["A: https://en.wikipedia.org/wiki/List_of_common_misconceptions I just lost two hours.", "B: Everything I know is wrong now."],
        ["A: New keyboard arrived. It makes a sound like rain.", "B: Don't use it on calls. Please."],
        ["A: My cat sat on my keyboard and approved a PR.", "B: Best reviewer on the team. 🐱 ~img:Cat on keyboard"],
        ["A: What are we reading? I need a book.", "B: *Project Hail Mary*, if you like science and optimism.", "C: Adding to my list. ~rx:📚"],
        ["A: Does anyone else read the terms and conditions? Asking for me.", "B: Nobody does and we all know it."],
        ["A: Hot take: tabs vs spaces is solved, we use a formatter.", "B: Hot take: the formatter is the real boss."],
        ["A: The sunrise today. Worth waking up early for.", "B: Stunning. ~img:Sunrise over the river ~rx:😍"],
        ["A: If you could master any skill instantly?", "B: Juggling. For the dinner party trick.", "C: Learning every language. Or juggling."],
        ["A: Spotted: a person on the train reading a printed spreadsheet.", "B: Respect."],
        ["A: Friday question: what's your comfort show?", "B: Anything with baking and gentle competition.", "A: Same. 🍰"],
        ["A: Who's up for a lunchtime walk? Blue sky and zero calendar conflicts.", "B: Joining. ~rx:🚶"],
      ],
    },
  },
  {
    name: 'wins',
    topic: 'Celebrate shipped milestones, closed deals and kind words from customers.',
    size: 4,
    mix: [['wins', 10], ['generic:thanks', 3], ['generic:release', 1]],
    pools: {
      wins: [
        ["A: 🎉 {proj} just hit {pct} adoption two weeks ahead of plan. Thank you to everyone involved!", "B: Fantastic result, proud of this team. ~rx:🎉|🚀|👏"],
        ["A: We passed our external audit with zero findings. Months of evidence collection, worth every hour.", "B: Congratulations to {@C} and the whole team. ~rx:🏆|🎉|👏"],
        ["A: A customer sent this today: 'Your support team made my week.' ❤️", "B: Pinning it. ~rx:❤️|🙌"],
        ["A: Closed the {cust} renewal, 3-year term, up {pct} on last time.", "B: Incredible. Thank you to everyone who supported the deal. ~rx:🎉|🏆"],
        ["A: Cutover finished in {hours} with zero customer impact. The runbook worked.", "B: Practiced it three times, and it showed. ~rx:🚀|🙌"],
        ["A: First production release of the new platform is live. 🚀", "B: Thank you to {@C} for staying late. ~rx:🚀|🎉|👏"],
        ["A: Our NPS is the highest it's been since we started measuring.", "B: Customers noticed the changes. ~rx:🎉|📈"],
        ["A: {@B} just completed the leadership programme with distinction. 🎓", "B: Thank you, that means a lot. ~rx:🎓|🎉|👏"],
        ["A: Month-end close finished in 4 working days, down from 7.", "B: Automation pays off. ~rx:🙌|🏆"],
        ["A: We hit {n} milestones this sprint, a team record. 🙌", "B: Cake on Friday. ~rx:🎂|🎉"],
      ],
    },
  },
  {
    name: 'watercooler',
    topic: 'Coffee, lunch plans and weekend stories.',
    size: 7,
    mix: [['chat', 10], ['generic:social', 5], ['generic:poll', 1], ['generic:ack', 1]],
    pools: {
      chat: [
        ["A: Coffee run in 10, who's in?", "B: Flat white please.", "C: Tea, strong. Thank you!"],
        ["A: Anyone know a good lunch place near the {city} office?", "B: The ramen place on the corner, go before 12:30.", "A: Heading there now. 🍜"],
        ["A: Weekend plans?", "B: Hiking with the dog if the weather holds.", "C: Absolutely nothing and I'm excited about it."],
        ["A: It's raining so hard I'm now at work early and drenched.", "B: Dry socks in the bottom drawer. You're welcome."],
        ["A: Board game lunch on Friday, bring your competitive side.", "B: I'll bring Catan and zero mercy. 🎲"],
        ["A: Who keeps moving my mug?", "B: It's a community mug now.", "A: Then I'm taking it back."],
        ["A: New espresso machine is the best thing to happen this quarter.", "B: Priorities. ☕"],
        ["A: Running club tonight, 6pm at the park. All speeds welcome.", "B: Mine is 'gentle jog and chat'.", "A: Perfect. ~rx:🏃"],
        ["A: The plant by my desk grew a new leaf. I feel unreasonably proud.", "B: Name it. ~img:Plant with a new leaf"],
        ["A: Please stop microwaving fish.", "B: It was salmon. It was delicious.", "A: It was also an event."],
        ["A: Sourdough starter update: alive. Sort of.", "B: Mine is named Gerald and he's thriving."],
        ["A: Who's watching the match tonight?", "B: Everyone, apparently. Quiet office tomorrow."],
      ],
    },
  },
  {
    name: 'engineering',
    topic: 'Engineering-wide: architecture, tooling, CI, on-call stories and TILs.',
    size: 9,
    mix: [['eng', 8], ['generic:code', 3], ['generic:review', 3], ['generic:incident', 2], ['generic:question', 3], ['kind:software:work', 3], ['generic:release', 1], ['generic:ack', 2]],
    cast: ['daniel', 'kenji'],
    castWeight: 0.08,
    depts: ['Engineering', 'IT & Infrastructure', 'Data & Analytics', 'Security'],
    pools: {
      eng: [
        ["A: TIL: `git bisect run ./test.sh` finds the breaking commit while you make coffee.", "B: How have I lived without this?", "A: You can feed it any script that exits non-zero. Magic. ~rx:🤯|👍"],
        ["A: RFC up for review: moving our job queue to a managed service. {wiki}", "B: What's the exit plan if we don't like it?", "A: Adapter pattern, two weeks to swap back. It's in section 6.", "B: Ok. Reading it properly."],
        ["A: CI is 14 minutes now. Let's find the slow tests.", "B: Top offender is an integration test hitting a real network. I'll mock it.", "A: That alone takes a third off. ~rx:🙌"],
        ["A: Dependency upgrade day is Thursday. Bring your lockfiles.", "B: And your resignation letters. Kidding. ~rx:😂"],
        ["A: Hot take: monorepo tooling is fine, our build graph isn't.", "B: Build graph is a symptom. Fix the module boundaries first."],
        ["A: Our latest postmortem has the line 'the clock was wrong'. I'm not surprised.", "B: Time is the hardest problem in computing."],
        ["A: What's the best way to share types between front-end and back-end?", "B: Generate them from a schema. Never hand-copy.", "C: OpenAPI plus a codegen step in CI. We've done it for years."],
        ["A: Reminder: don't squash-merge a PR with six unrelated changes.", "B: Receipts: {pr}. ~rx:😅"],
        ["A: Slow query of the day:\n```sql\nSELECT * FROM events WHERE payload LIKE '%error%';\n```\nWe need a column for that.", "B: Add a generated column and an index. Please. ~rx:🙏"],
        ["A: Looking for pair for {task}, two hours, tricky refactor.", "B: I can do after lunch.", "A: Perfect, thanks!"],
        ["A: Tech talk on {day}: 'Scaling our search stack'. Free lunch.", "B: Free lunch is my favourite design pattern. ~rx:🍕"],
        ["A: Flaky test count is down to {n}. Hit zero by end of month?", "B: Never believe in zero. But I'm in. ~rx:🎯"],
      ],
    },
  },
];
