/** Kind libraries (extra 3): supply-chain, customer, sales + research addendum. Contract: ./chat-dsl.ts */
import type { KindLib, Pools } from './chat-dsl';
import type { ProjectKind } from '../schema';

export const RESEARCH_EXTRA: Pools = {
  decision: [
    ["A: Go/no-go on the pilot: the model clears the accuracy bar but cost per query is 3x budget.", "B: Go for a limited pilot with a cost cap, no-go for broad rollout until we've tried a smaller model.", "C: Agree. Success criteria and the cap are in {wiki}.", "A: Recorded. ~rx:👍|✅ ~pin:Decision: pilot scope"],
    ["A: Which evaluation set is the source of truth, the curated 500 or the sampled 5,000?", "B: Curated for regressions, sampled for the headline number. Report both.", "A: Fine by me. ~rx:👍"],
    ["A: Can we send real customer text to the hosted model?", "B: Only through the approved gateway with PII redaction on. Privacy signed it off on {date}.", "A: Thanks, adding to the data-handling doc. ~rx:✅"],
    ["A: Build vs buy for the vector store?", "B: Start with pgvector, we have the skills and it's good enough at this scale. Revisit at 10M documents.", "A: Agreed. ~rx:👍|✅"],
  ],
  launch: [
    ["A: Pilot goes live for {n} users on {date}. Feedback form is in the app, kill switch is a feature flag.", "B: Support has the FAQ. ~rx:🚀"],
    ["A: Readout on {day} at {time}: what we tried, what worked, what it costs at scale.", "B: Slides draft by {day2}. ~rx:👍"],
    ["A: The assistant is now in the hands of the support team. First day: {pct} of suggestions accepted.", "B: Good start. Watch for the edge cases in the afternoon. ~rx:🎉"],
    ["A: Production shadow mode starts today. We log outputs but don't show them.", "B: Two weeks of data and then we compare against human decisions. ~rx:🙌"],
  ],
  chatter: [
    ["A: The model confidently invented a policy that doesn't exist.", "B: Added to the 'creative writing' bucket of the eval. 😅"],
    ["A: Prompt v14 is better than v13 but worse than v12.", "B: Welcome to research."],
    ["A: Reminder: don't paste customer data into any tool that isn't on the approved list.", "B: Pinning that, forever."],
    ["A: Run finished, accuracy is up 0.4 points.", "B: Within noise. But I'll allow a smile."],
    ["A: Who killed the GPU job?", "B: The queue did. Resubmitting."],
    ["A: The new paper reproduces our result. Great or concerning?", "B: Great! Citation party."],
    ["A: {ack}, adding it to the experiment log.", "B: 👍"],
    ["A: My notebook has 400 cells and I regret all of them.", "B: Refactor Friday."],
    ["A: Reading group on {day}: attention is all we have.", "B: Terrible pun, will attend."],
    ["A: Baseline beat our fancy model on the hard slice.", "B: The baseline is a stubborn little legend."],
    ["A: Embedding drift alert: nothing's wrong, we changed the tokenizer.", "B: Classic."],
    ["A: Seeds matter. Run it 5 times before you tweet about it.", "B: Do not tweet about it."],
  ],
};

export const KINDS_E3: Partial<Record<ProjectKind, KindLib>> = {
  'supply-chain': {
    lex: {
      feature: ['the demand sensing model', 'the supplier portal', 'safety stock optimisation', 'the S&OP cadence', 'the control tower dashboard', 'the carrier scorecards', 'the exception workflow', 'multi-echelon planning', 'the lane re-bid', 'real-time shipment tracking'],
      component: ['the forecast pipeline', 'the planning cube', 'the ASN feed', 'the TMS integration', 'the inventory snapshot', 'the supplier master data', 'the replenishment engine', 'the EDI gateway', 'the allocation rules', 'the freight audit tool'],
      tool: ['SAP IBP', 'project44', 'Manhattan WMS', 'OR-Tools', 'Snowflake', 'Power BI', 'Coupa', 'Excel', 'Anaplan', 'Kinaxis'],
      problem: ['a supplier delay on the key component', 'a forecast bias on promotions', 'a lane with 30% late deliveries', 'a duplicate PO from the EDI feed', 'a stock-out at the regional DC', 'a customs hold at the border', 'excess inventory on slow movers', 'a carrier capacity crunch', 'a master data error on lead times', 'a currency swing on freight cost'],
      metric: ['OTIF', 'forecast accuracy (WMAPE)', 'inventory turns', 'days of supply', 'expedite spend', 'perfect order rate', 'supplier on-time rate', 'fill rate', 'freight cost per unit', 'order cycle time'],
      deliverable: ['the S&OP pack', 'the supplier scorecard', 'the network design study', 'the safety stock policy', 'the lane re-bid results', 'the forecast review', 'the carrier contracts', 'the cutover schedule', 'the exception playbook', 'the master data cleanse'],
      team: ['planning', 'logistics', 'procurement', 'the supplier team', 'demand planning', 'transport', 'the DC leads', 'finance'],
      supplier: ['Alpine Components', 'Meridian Plastics', 'Kestrel Packaging', 'Ironvale Steel', 'Larkspur Textiles', 'Harborline Freight'],
    },
    pools: {
      work: [
        ["A: Forecast accuracy for promo weeks: WMAPE {pct} vs {pct2} for baseline weeks. The model under-calls promos.", "B: The promo flag arrives late from marketing. We're feeding the model stale data.", "A: Pull the promo calendar from the source directly. I'll raise it with {team}."],
        ["A: OTIF on the Rotterdam lane dropped to {pct} last week.", "B: Carrier changed their cut-off time and nobody told us.", "A: Updating the lane rules and asking the carrier for a rate review."],
        ["A: S&OP pack is ready: {deliverable}. Two items need a decision: supply constraint on SKU family B and the Q4 build plan.", "B: I'll bring the cost view. Constraint is real, expediting adds {usd}.", "A: Pre-read goes out tomorrow."],
        ["A: Safety stock recalculation lowers inventory by {pct} without hurting service on paper.", "B: On paper is the keyword. Simulate against last year's volatility first.", "A: Running Monte Carlo now, results in the morning."],
        ["A: {supplier} says the delay is 3 weeks, not 1. Production plan for week {n} is exposed.", "B: Split the order with the backup supplier, accept a price premium for the first 20%.", "A: Approved. Placing the PO today."],
        ["A: Customs hold on shipment {ticket}. Documents missing for the certificate of origin.", "B: Broker is chasing. We need it by {day} or the line stops.", "A: Escalating to the supplier's export manager."],
        ["A: Supplier portal adoption: {n} of {n2} suppliers have confirmed orders in the portal this month.", "B: The rest still email PDFs. Three phone calls and a visit should do it.", "A: I'll schedule them."],
        ["A: Network design study says consolidating two DCs saves {usd} a year but adds a day of transit to a region.", "B: Which service level does that violate?", "A: None, but it's tight on the express tier. Needs commercial input."],
      ],
      standup: [
        ["A: **Yesterday:** reconciled the ASN feed. **Today:** {task} (carrier scorecards). **Blockers:** waiting for data from {supplier}."],
        ["A: Expedite calls all morning, two lines at risk. Will update at noon.", "B: Preparing the S&OP pack, chasing the last numbers."],
        ["A: Heads down on the forecast review until 2."],
        ["A: At the port today with logistics. Online again at 3."],
      ],
      blocker: [
        ["A: Blocked on {task}: lead times in master data are wrong for {n} suppliers.", "B: Procurement owns them but hasn't had a review in a year. I'll set up a clean-up sprint.", "A: Thanks, I'll provide the list of the worst offenders."],
        ["A: The TMS integration fails for one carrier because their API returns dates in a different format.", "B: Transform at the gateway and log the raw payload.", "A: On it."],
        ["A: We can't finalise the re-bid until finance approves the budget ceiling.", "B: Chasing today."],
        ["A: Warehouse capacity is full at the regional DC and the inbound is still arriving.", "B: Divert to the overflow site and communicate to carriers.", "A: Doing it now."],
      ],
      decision: [
        ["A: Air freight for the critical component or accept a 10-day delay?", "B: Air for 30% of the order, sea for the rest. Cost {usd}, avoids the line stop.", "A: Approved. ~rx:👍|✅"],
        ["A: Dual-source the packaging supplier?", "B: Yes, 70/30 split. I'll start the qualification.", "A: Agreed. ~rx:👍|✅ ~pin:Decision: dual sourcing"],
        ["A: Move to weekly planning cycle for fast movers?", "B: Pilot with 3 categories first.", "A: Ok. ~rx:👍"],
        ["A: Safety stock policy: service level target 97% for A items, 95% for B?", "B: Fine, with quarterly review.", "A: Done. ~rx:✅"],
      ],
      launch: [
        ["A: The control tower dashboard is live: {dash}. Shipments, exceptions and ETA risk in one view.", "B: Planners are already using it in the morning huddle. ~rx:🎉|🚀"],
        ["A: Go-live of the new planning tool on {date}. Parallel run for 4 weeks.", "B: Training sessions booked for all planners. ~rx:🙌"],
        ["A: Supplier portal phase {n} released. Order confirmation and ASN submission are now self-service.", "B: Great news for the team. ~rx:🎉"],
        ["A: Lane re-bid concluded: expected savings {usd} with the same service levels.", "B: Congrats. Contracts go out Monday. ~rx:👏"],
      ],
      chatter: [
        ["A: The shipment is in 'transit' for the 9th day. It's not transit, it's tourism.", "B: A scenic route. 😄"],
        ["A: Inventory is a function of optimism.", "B: And forecasting is a function of regret."],
        ["A: Free coffee at the S&OP kick-off. Come for the coffee, stay for the constraints.", "B: Mostly the coffee."],
        ["A: Who owns this spreadsheet with 14 tabs and no names?", "B: It has been here longer than any of us."],
        ["A: Container just cleared customs. Champagne for the broker.", "B: Coffee for the broker. They're on shift."],
        ["A: {ack}, will check the ETA.", "B: 👍"],
        ["A: New warehouse smells like fresh cardboard. I love it.", "B: You need a hobby. 😅"],
        ["A: Forecast says we'll sell more umbrellas next week. Also sunscreen.", "B: Weather models are beating ours."],
        ["A: Back to back calls with the carriers. Send snacks.", "B: On the way."],
        ["A: Can someone share the lane map? Mine looks like spaghetti.", "B: Posted in {ch}."],
        ["A: The supplier reply was one word: 'Soon'.", "B: Chilling."],
        ["A: Trucks arrived on time. Take a picture, it will not happen again.", "B: Framing it. ~rx:😂"],
      ],
      incident: [
        ["A: Alert: ASN feed from {supplier} has stopped, {n} inbound shipments not visible.", "B: Their SFTP certificate expired. They're renewing.", "A: Manually loading yesterday's ASNs so the dock team has visibility.", "B: Feed restored. Adding a certificate expiry alert for all partners. ~rx:🙏"],
        ["A: Scanner update broke the receiving workflow at one DC, {n} pallets waiting.", "B: Roll back the firmware on those devices, 20 minutes.", "A: Rolled back, backlog cleared in an hour. ~rx:✅"],
      ],
    },
  },
  customer: {
    lex: {
      feature: ['the in-app help centre', 'health scores', 'the onboarding checklist', 'automated renewal reminders', 'the escalation workflow', 'the customer portal', 'the CSAT survey', 'ticket deflection', 'the QBR template', 'the success plan builder'],
      component: ['the Zendesk macros', 'the Gainsight playbooks', 'the churn model', 'the usage telemetry feed', 'the support routing rules', 'the knowledge base', 'the CRM sync', 'the email templates', 'the community forum', 'the chatbot flows'],
      tool: ['Zendesk', 'Gainsight', 'Salesforce', 'Segment', 'Looker', 'Intercom', 'Slack', 'Notion', 'Gong', 'Zoom'],
      problem: ['a P1 ticket sitting for 3 hours', 'a confusing renewal email', 'an angry exec escalation', 'a health score that never updates', 'a macro with an outdated link', 'a customer stuck in onboarding for 6 weeks', 'a duplicate survey sent', 'a missing owner on a key account', 'a knowledge article that contradicts itself', 'a routing rule that sends billing to tech support'],
      metric: ['CSAT', 'time to value', 'ticket deflection rate', 'first response time', 'net revenue retention', 'churn rate', 'NPS', 'resolution time', 'onboarding completion rate', 'at-risk accounts'],
      deliverable: ['the escalation playbook', 'the QBR deck', 'the success plan', 'the onboarding guide', 'the churn analysis', 'the macro library', 'the training session', 'the account review', 'the survey results', 'the knowledge base cleanup'],
      team: ['support', 'customer success', 'onboarding', 'solutions', 'account management', 'tier 2', 'product', 'renewals'],
    },
    pools: {
      work: [
        ["A: Health score for {cust} dropped from green to amber. Usage down {pct} and no exec sponsor engagement.", "B: Their champion left last month. Setting up a call with the new contact.", "A: Prep a short value recap. They're up for renewal in {n} weeks."],
        ["A: Deflection rate is {pct} since the new help centre went live. Target was {pct2}.", "B: Top unanswered searches are on billing. Let's write those articles first.", "A: Adding six articles this week."],
        ["A: First response time: {n} minutes against a target of 30. Biggest delay is the 3pm handover.", "B: Overlap the shifts by 30 minutes. It fixes this in most teams.", "A: Trying it for two weeks."],
        ["A: QBR with {cust} on {day}. They want to talk about the roadmap.", "B: I'll invite product so they hear it from the source.", "A: Great. Keep it to 3 slides."],
        ["A: CSAT comments say the onboarding emails are too long.", "B: Cut them to 3 short messages and a checklist in the app.", "A: Drafting now."],
        ["A: Renewal at risk: {cust} wants a 20% discount.", "B: Offer an extended term at 8% and a free training bundle.", "A: Taking that to the call."],
        ["A: Tickets about export errors up {pct}. Same root cause?", "B: Yes, the {component} timeout. Bug is in {task}.", "A: Adding the known issue banner and a workaround macro."],
        ["A: Playbook for escalations: acknowledge in 15 minutes, owner named in 30, update every 2 hours until resolved.", "B: Pinning this. ~rx:👍 ~pin:Escalation playbook"],
      ],
      standup: [
        ["A: Yesterday: 3 customer calls, 1 escalation resolved. Today: QBR prep for {cust}. No blockers."],
        ["A: Working through the backlog of tier 2 tickets, {n} left. Shout if something is urgent.", "B: Onboarding sessions at 10 and 2. Updating success plans in between."],
        ["A: Standup: on a call with {cust} until noon, then macros cleanup."],
        ["A: Out at a customer site, replying to messages from the train."],
      ],
      blocker: [
        ["A: Blocked: customer needs an urgent fix and engineering says it's next sprint.", "B: Escalate with the revenue at stake. If it's more than {usd}, it jumps the queue.", "A: It is. Writing the case now."],
        ["A: Can't launch the health score v2 until data science fixes the usage feed.", "B: ETA is {day}. I'll ping them for an update."],
        ["A: Legal wants to review every renewal over {usd} and it's slowing things.", "B: Propose a threshold and a template. Only deviations go to legal."],
        ["A: Customer data export blocked by a consent flag.", "B: Check with privacy, they can approve a one-off."],
      ],
      decision: [
        ["A: Offer the discount to {cust} or hold the line?", "B: Hold the line on price, give them added value instead.", "A: Agreed. ~rx:👍|✅"],
        ["A: Do we move to a pooled support queue or keep tiered?", "B: Pooled for L1, dedicated for the top tier accounts.", "A: Decision logged. ~rx:👍|✅ ~pin:Decision: queue model"],
        ["A: Survey after every ticket or only after close?", "B: After close, with a 7-day cooldown.", "A: Fine. ~rx:👍"],
        ["A: Shall we add a community forum?", "B: Pilot with 20 customers first.", "A: Ok. ~rx:✅"],
      ],
      launch: [
        ["A: Customer portal goes live for the first 100 accounts on {date}. Training is on {day}.", "B: Support macros are ready. ~rx:🚀"],
        ["A: Health score v2 is live. At-risk accounts are flagged 60 days earlier.", "B: That's the headline. ~rx:🎉|👏"],
        ["A: New onboarding flow cut the time to value by {pct}. 🎉", "B: Customers noticed too. ~rx:🙌"],
        ["A: Chatbot is answering {pct} of questions without a human handoff.", "B: Keep an eye on the quality scores. ~rx:👍"],
      ],
      chatter: [
        ["A: Customer sent a thank-you note with a photo of their dog.", "B: Pinned in the wins channel. 🐶"],
        ["A: Ticket subject: 'HELP!!!!!!!!!!'. Body: 'forgot my password'.", "B: We've all been there."],
        ["A: Ticket volume is calm. I'm suspicious.", "B: Don't say it out loud."],
        ["A: {ack}, will reply to them today.", "B: 👍"],
        ["A: Coffee machine broke. It's now a priority 1 incident.", "B: Tier 2 is on it. ☕"],
        ["A: Our macro for apologies has been used {n} times today.", "B: We should be sorry less. Fix the cause."],
        ["A: A customer asked for a feature we shipped last year.", "B: Mark it as an adoption problem."],
        ["A: Customer success is just therapy with a roadmap.", "B: Billable hours."],
        ["A: QBR slide count is now 31. Help.", "B: Cut to 5. They'll thank you."],
        ["A: Our NPS verbatims have a lot of heart emojis lately.", "B: Whatever we're doing, keep doing it."],
        ["A: The customer said 'your product changed my life'.", "B: Frame it. Share it. Use it in the board deck."],
        ["A: Weekly reminder to log your calls in the CRM.", "B: Logged right after this message."],
      ],
      incident: [
        ["A: Major outage reported by {n} customers, tickets flooding in.", "B: Status page updated, engineering is on it. Macro for 'we're investigating' is live.", "A: Proactively emailing the top 20 accounts.", "B: Service restored. Sending a root-cause summary within 48 hours. ~rx:🙏"],
      ],
    },
  },
  sales: {
    lex: {
      feature: ['the new CPQ flow', 'deal desk approvals', 'the forecast roll-up', 'the territory model', 'the partner portal', 'the pipeline dashboard', 'the quote templates', 'the commission calculator', 'opportunity scoring', 'the renewal motion'],
      component: ['the Salesforce validation rules', 'the quote approval chain', 'the pricing book', 'the lead routing rules', 'the contract template', 'the Clari forecast', 'the DocuSign integration', 'the territory assignment', 'the commission plan', 'the CRM dashboards'],
      tool: ['Salesforce', 'Clari', 'Gong', 'DocuSign', 'Outreach', 'Looker', 'Slack', 'Excel', 'Zoom', 'LinkedIn Sales Navigator'],
      problem: ['a quote stuck in approval', 'a discount outside policy', 'a duplicate account in the CRM', 'a mis-assigned territory', 'a forecast call that is 20% off', 'a missing legal clause in the order form', 'a rep not logging activity', 'a stale opportunity from last year', 'a commission dispute', 'a pricing book out of date'],
      metric: ['pipeline coverage', 'win rate', 'quote-to-cash cycle', 'forecast accuracy', 'average deal size', 'discount rate', 'sales cycle length', 'quota attainment', 'approval turnaround', 'partner-sourced revenue'],
      deliverable: ['the territory plan', 'the pricing guide', 'the enablement deck', 'the approval matrix', 'the quarterly forecast', 'the commission plan docs', 'the partner programme', 'the CPQ training', 'the deal review notes', 'the win/loss report'],
      team: ['deal desk', 'sales ops', 'enablement', 'finance', 'legal', 'the AEs', 'the SDR team', 'partner managers'],
    },
    pools: {
      work: [
        ["A: Forecast call: commit {usd}, best case {usd2}. Last quarter we landed at {pct} of commit.", "B: Two big deals slipped into next quarter. Need to haircut those.", "A: I'll adjust the roll-up before the exec review."],
        ["A: Deal desk SLA is {n} hours but we're averaging {n2}. Backlog is from the pricing exceptions.", "B: Tier the approvals: standard discounts auto-approve, exceptions to desk.", "A: Rule change goes live Monday."],
        ["A: {cust} wants custom payment terms. Finance says no more than net 45.", "B: Offer net 45 with a small early-pay discount.", "A: Passing that to the rep."],
        ["A: New territory plan: {n} accounts moving to other reps. Comms go out Friday.", "B: Account owners get a note and a handover template.", "A: Keep rep-to-rep handover meetings short."],
        ["A: Win/loss review: price came up in {pct} of losses, product gaps in {pct2}.", "B: Price is usually a symptom. Let's look at the value story in those deals.", "A: Gong clips are in {wiki}."],
        ["A: CPQ rollout: {pct} of reps have used the new flow. Big win is the auto-generated order form.", "B: Remaining pain: multi-year pricing. I'll write a quick guide.", "A: Thanks."],
        ["A: Quote {ticket} has a clause that legal hasn't approved.", "B: Pulling it back, adding the standard clause, resending to the rep in 10.", "A: Thanks. Training the rep on the template."],
        ["A: Partner programme: three new partners signed this month.", "B: Enablement session on {day} for their sales teams.", "A: Invite sent."],
      ],
      standup: [
        ["A: Yesterday: approved {n} quotes, cleaned {n2} duplicate accounts. Today: forecast prep. No blockers."],
        ["A: Working on {task} (commission calculator fixes). ETA {day}.", "B: Enablement session on CPQ at 2pm. Slides ready."],
        ["A: In deal reviews until noon. Ping me for urgent approvals."],
        ["A: Quarter-end crunch, I'll be fast to respond. Coffee required."],
      ],
      blocker: [
        ["A: Blocked: the contract template is missing a data-processing addendum and customers keep asking.", "B: Legal is drafting. ETA {day}.", "A: Meanwhile reps use the manual addendum."],
        ["A: CRM sync is failing for opportunities with more than 50 line items.", "B: Batch the sync and increase the timeout. Ticket opened with the vendor.", "A: Thanks."],
        ["A: Finance can't approve the discount without the margin analysis.", "B: Sending it now."],
        ["A: Territory assignment conflicts for {n} strategic accounts.", "B: Escalate to the VP of sales for a decision by {day}."],
      ],
      decision: [
        ["A: Cap discount at 25% without VP approval?", "B: Yes, 15% for AEs, 25% for managers, above that the VP.", "A: Policy updated. ~rx:👍|✅ ~pin:Decision: discount tiers"],
        ["A: Accelerators for the last month of the quarter?", "B: Only on net new, not on renewals.", "A: Fine. ~rx:👍"],
        ["A: Sunset the old pricing book on {date}?", "B: Yes, with a 30-day grace for in-flight deals.", "A: Agreed. ~rx:✅"],
        ["A: Which leads go to SDRs vs direct to AEs?", "B: Score above 80 direct to AEs. Everything else SDR.", "A: Updating the routing rules. ~rx:👍"],
      ],
      launch: [
        ["A: New CPQ flow goes live Monday. Training this week, office hours daily at 11.", "B: Cheat sheet is in {wiki}. ~rx:🚀"],
        ["A: Forecast roll-up v2 is live. One number, one source.", "B: Finally. ~rx:🎉"],
        ["A: Quarter closed at {pct} of target. Huge thanks to deal desk.", "B: The team crushed it. ~rx:🎉|🏆|👏"],
        ["A: Partner portal is live for the first cohort of partners.", "B: Welcome emails sent. ~rx:🙌"],
      ],
      chatter: [
        ["A: Who closed a deal at 11:58pm on the last day?", "B: Legend. Please never do that again."],
        ["A: A rep said 'it's a lock'. It was not a lock.", "B: Nothing is a lock until the cash arrives."],
        ["A: Closing bell for the quarter, someone buy a gong.", "B: Already ordered. 🔔"],
        ["A: {ack}, will approve right after the call.", "B: 👍"],
        ["A: Pipeline review at 3. Bring your biggest deals and your biggest excuses.", "B: Mostly excuses."],
        ["A: Our best rep never logs notes. How?", "B: Memory. And fear."],
        ["A: Coffee on the house for any deal over {usd}.", "B: I only close for coffee."],
        ["A: The CRM has {n} accounts named 'Test'.", "B: Test account of the year."],
        ["A: Another quarter, another spreadsheet.", "B: Excel is eternal."],
        ["A: New hire onboarding on {day}, wear comfy shoes.", "B: And bring an appetite for acronyms."],
        ["A: Gong says I talk 80% of the time. I'll stop. Soon.", "B: Listen more, close more."],
        ["A: A thank-you card from a customer! Pinning it to the whiteboard.", "B: Nice one. ~rx:❤️"],
      ],
      incident: [
        ["A: Quote PDFs are generating with the wrong currency symbol for EU customers.", "B: Template variable broke after the update. Fix is a one-line change.", "A: Deployed. Re-sending the affected quotes today.", "B: Notified the 6 reps. Adding a template regression test. ~rx:🙏"],
      ],
    },
  },
};
