/** Kind libraries (extra 1): data, security, infrastructure. Contract: ./chat-dsl.ts */
import type { KindLib } from './chat-dsl';
import type { ProjectKind } from '../schema';

export const KINDS_E1: Partial<Record<ProjectKind, KindLib>> = {
  data: {
    lex: {
      feature: ['the semantic layer', 'the customer 360 model', 'incremental dbt models', 'the metrics catalog', 'column-level lineage', 'the freshness dashboard', 'self-serve cohort analysis', 'the revenue mart', 'the certified datasets list', 'row-level security on finance tables'],
      component: ['the Airflow scheduler', 'the staging schema', 'the dbt project', 'the CDC pipeline', 'the Snowflake warehouse', 'the Looker explore', 'the orders fact table', 'the reverse-ETL sync', 'the data contract checks', 'the backfill job'],
      tool: ['dbt', 'Snowflake', 'Airflow', 'Looker', 'Great Expectations', 'Fivetran', 'Monte Carlo', 'Python notebooks', 'Spark', 'Kafka'],
      problem: ['a late-arriving partition', 'duplicate keys after the merge', 'a schema drift in the source', 'a timezone bug in the daily rollup', 'a fan-out join inflating revenue', 'an expired service credential', 'a null spike in customer_id', 'a stuck DAG run', 'a warehouse queue backlog', 'a metric defined two different ways'],
      metric: ['freshness lag', 'credits per day', 'dashboard load time', 'test pass rate', 'row-count variance', 'query p95', 'certified dataset coverage', 'backfill throughput', 'failed DAG runs', 'cost per TB scanned'],
      deliverable: ['the lineage map', 'the metric definitions doc', 'the migration runbook', 'the data quality scorecard', 'the access review', 'the cost report', 'the cutover checklist', 'the dataset ownership list', 'the parity report', 'the training session'],
      team: ['analytics engineering', 'data platform', 'BI', 'finance analytics', 'data science', 'data governance', 'ingestion', 'the warehouse team'],
      dataset: ['orders_daily', 'customer_dim', 'revenue_mart', 'web_events', 'inventory_snapshot', 'ledger_entries', 'support_tickets', 'subscriptions_history'],
    },
    pools: {
      work: [
        ["A: Parity check on {feature}: old warehouse says {big} orders yesterday, Snowflake says {big}. Digging into the delta.", "B: Check the timezone on the date filter. The legacy job cut at midnight UTC, ours cuts at local midnight.", "A: That's it. Switching to UTC, the difference is down to 3 rows.", "B: Document it in {wiki} so nobody rediscovers it in March."],
        ["A: Proposal: every certified dataset gets an owner, an SLA and a test suite before it appears in {tool}.", "B: Love it. Who owns the orphans? There are about {n} tables nobody will admit to.", "A: Deprecate after 60 days of zero queries. I'll post the list in {ch} and wait for objections.", "C: Please add the query count column, that's how I'd decide."],
        ["A: {dataset} is {pct} slower since the join change. Warehouse queueing or the query plan?", "B: Plan. The new join explodes on `customer_id` nulls. Filter them first and it drops from {ms} to 400ms.", "A: Nice. Putting the filter in the staging model so everyone benefits."],
        ["A: Quick sanity check, is `revenue` gross or net in {feature}?", "B: Net of refunds, gross of tax. It's in the definition but nobody reads definitions.", "C: We should rename it `net_revenue` and kill `revenue`. Confusion cost us a board slide last quarter.", "A: Agreed, writing the deprecation notice."],
        ["A: Backfilling {dataset} for three years. Estimated {hours} on a medium warehouse. Run it overnight?", "B: Chunk it by month and make it idempotent, otherwise one failure costs you the whole night.", "A: Already chunked. Each month writes to a temp table and swaps in at the end.", "B: Perfect. Alert me if month 14 fails, that's where the schema changed."],
        ["A: Looker explore is returning different numbers from the SQL I ran. Who's right?", "B: Probably the explore, it applies a default filter on `is_test = false`. Check the base view.", "A: Found it. So the SQL is wrong for the audience that matters. Thanks!"],
        ["A: Credit usage spiked {pct} yesterday. Anyone running something heavy?", "B: Data science notebook, full scan on {dataset}. It's been killed.", "A: Please set a resource monitor on that role so it can't happen again. {@C} can you own that?", "C: On it, will do today."],
        ["A: Lineage graph is now live for the revenue mart: {dash}", "B: This is great. Can we get column-level, at least for finance-critical fields?", "A: Next sprint. Parsing SQL for column lineage is the hard 80%."],
      ],
      standup: [
        ["A: **Yesterday:** finished the dbt tests for {dataset}\n**Today:** parity run on {feature}\n**Blocked:** waiting on {team} for source credentials"],
        ["A: Yesterday: fixed {problem} in {component}. Today: backfill month 7-12. No blockers.", "B: Yesterday: reviewed {pr}. Today: pairing with {A} on the lineage parser. Need an answer from finance on the revenue definition."],
        ["A: Heads down on {task} all day. Pipeline's green, dashboards are fresh, I'll surface when I have numbers."],
        ["A: Standup: reconciling {dataset}, {n} rows still off. Will update by 3pm.", "B: I can help after lunch, I wrote the original job."],
      ],
      blocker: [
        ["A: Blocked on {task}: the source team changed a column type with no notice and our pipeline fails at the merge.", "B: Data contract would have caught that. Raising it with their lead.", "A: Meanwhile I've added a cast in staging. Not pretty, but the data flows."],
        ["A: Can't certify {dataset} until finance signs off the definitions. They've had the doc for {n} days.", "B: I'll chase. If they don't respond by {day}, we certify with the current definition and flag the open question.", "A: Works for me."],
        ["A: The reverse-ETL sync is rate-limited by the CRM and we're {pct} behind.", "B: Batch it and prioritise accounts touched in the last week. Nobody needs stale prospects at the front of the queue."],
        ["A: Production credentials for {tool} expire {day} and the renewal request is stuck in procurement.", "B: {@me} you've got a contact in procurement, can you nudge?", "M: On it, I'll ping them now and come back with an ETA."],
      ],
      decision: [
        ["A: Decision needed: incremental models or full refresh for {dataset}? Incremental saves ~{pct} of credits but adds late-data risk.", "B: Incremental with a 3-day lookback window. Full refresh weekly as a safety net.", "C: Agree. Weekly full refresh catches the weird edge cases.", "A: Decided. Recording in {wiki}. ~rx:👍|✅"],
        ["A: Which BI tool is the standard for finance reporting, {tool} or the legacy cubes? Need a call so we stop building both.", "B: {tool}. Cubes retire at the end of {q}.", "A: Ok, announcing it in {ch}. ~rx:👍|✅"],
        ["A: Proposed: PII columns are masked by default and unmasked only via an approved role.", "B: +1. We should have done this years ago.", "A: Policy goes live {date}. Owners get a heads-up from me. ~rx:👍|✅ ~pin:Decision: PII masking"],
        ["A: Retention for raw events: 13 months or 25? Legal says 13 is the minimum, analytics wants 25.", "B: 13 months raw, 25 months aggregated. Best of both.", "A: Sold. ~rx:👍|✅"],
      ],
      launch: [
        ["A: Cutover weekend plan for {feature}: freeze Friday 6pm, final sync Saturday 2am, validation until 8am, switch DNS aliases at 9am.", "B: I'll be on call. Rollback is a one-line alias flip back to the legacy warehouse.", "A: Reminder: reports will be read-only until Sunday noon. Comms went out today. ~rx:🚀|🙌"],
        ["A: **Go-live:** {dataset} is now served from Snowflake. Dashboards are green, parity at {pct}.", "B: Fantastic work, everyone. 🎉 ~rx:🎉|🚀|👏"],
        ["A: Parity report is signed off by finance. We are go for cutover.", "B: Congrats. That was the long pole.", "A: Next: decommission the old warehouse in {n} weeks, once nobody's querying it. ~rx:🎉"],
        ["A: Training for analysts is on {day} at {time}. Bring a query you run weekly, we'll port it live.", "B: Recording will be in {wiki}. ~rx:👍"],
      ],
      chatter: [
        ["A: Who named a table `final_final_v3`?", "B: I'm not saying it was me but I'm also not saying it wasn't {lol}"],
        ["A: Dashboard loads in 2 seconds. I refreshed it 10 times just to feel something.", "B: Joy is the little things. 😄"],
        ["A: Reminder that `SELECT *` on a 4 TB table is not a personality trait.", "B: Receipts, please. 👀"],
        ["A: My dbt run finished before my coffee cooled. New record."],
        ["A: Can someone explain why Tuesday's numbers are always weird?", "B: Quarterly close batch runs on Tuesdays. We should annotate the dashboard.", "A: Adding an annotation."],
        ["A: Whoever put an emoji in a column name, I respect it and I'm renaming it."],
        ["A: Friday data quality score: {pct}. Not bad.", "B: Better than my sleep score."],
        ["A: {ack}, will look after standup.", "B: 👍"],
        ["A: Is anyone else's notebook kernel dying?", "B: Yes, restart the cluster, memory leak in the plotting lib.", "A: Fixed, thanks."],
        ["A: New joiner asks what a 'grain' is. Best one-line answer?", "B: What one row represents. If you can't say it, the table is broken.", "C: Printing that on a mug."],
        ["A: Lunch and learn on window functions on {day}. Free pastries.", "B: Pastries are the real KPI. ~rx:😂"],
        ["A: The warehouse is idle, so I'm going to call it a win and go home.", "B: Don't tempt the schedulers."],
      ],
      incident: [
        ["A: Heads up: the daily revenue dashboard shows $0 for today.", "B: Pipeline stalled at the merge step, upstream file never landed.", "A: Contacted the source team, file is being resent.", "B: Reloaded, dashboard recovered. I'm adding a freshness alert so we catch this before finance does. ~rx:🙏"],
      ],
    },
  },
  security: {
    lex: {
      feature: ['phishing-resistant MFA', 'the vulnerability SLA policy', 'the evidence collection automation', 'the access review workflow', 'the secrets rotation job', 'conditional access rules', 'the endpoint compliance check', 'the SIEM correlation rules', 'device posture checks', 'the vendor risk assessment'],
      component: ['the identity provider', 'the privileged access vault', 'the EDR agent', 'the SIEM pipeline', 'the WAF ruleset', 'the CI secret scanner', 'the VPN gateway', 'the SCIM connector', 'the asset inventory', 'the log forwarder'],
      tool: ['Okta', 'CrowdStrike', 'Vault', 'Splunk', 'Wiz', 'Snyk', 'Drata', 'Burp Suite', 'OPA', 'Terraform'],
      problem: ['an overprivileged service account', 'an unpatched library', 'a shared admin credential', 'a public storage bucket', 'a stale user in the directory', 'an expired certificate', 'a missing log source', 'an exception with no expiry', 'a phishing click-through', 'an unreviewed firewall rule'],
      metric: ['mean time to remediate', 'MFA coverage', 'open critical findings', 'patch compliance', 'evidence automation rate', 'phishing report rate', 'overdue access reviews', 'policy attestation rate', 'alert triage time', 'vendor reviews completed'],
      deliverable: ['the audit evidence pack', 'the pen test report', 'the risk register', 'the policy update', 'the access review results', 'the remediation plan', 'the tabletop exercise report', 'the control matrix', 'the training deck', 'the exception register'],
      team: ['GRC', 'the SOC', 'AppSec', 'IT', 'platform', 'identity', 'compliance', 'the red team'],
      regulation: ['SOC 2', 'ISO 27001', 'GDPR', 'PCI DSS', 'HIPAA', 'NIST CSF'],
    },
    pools: {
      work: [
        ["A: Audit window opens {date}. We still have {n} controls without automated evidence.", "B: Prioritise the ones auditors sample most: access reviews, change approvals and backups.", "A: Agreed. {@C} can you take access reviews? I'll take change approvals.", "C: Yes. I'll have the export scripted by {day}."],
        ["A: Pen test findings are in. 2 high, 5 medium, the rest informational.", "B: Highs first. What are they?", "A: Broken object-level auth on an internal API and a verbose error leaking stack traces. Tickets are {task} and {task2}.", "B: Both are fixable this sprint. I'll pair with the owning team."],
        ["A: Rolled out {feature} to the pilot group, {pct} of users enrolled in the first week.", "B: Who's holding out?", "A: Mostly shared-device staff in the warehouses. We need a different flow for them.", "B: Passkeys on a hardware key? I'll write up the options."],
        ["A: Remember, evidence needs a date, a system and a person. Screenshots without those get bounced.", "B: Pinning this. Every audit we relearn it. ~rx:👍 ~pin:Evidence rules"],
        ["A: Q: Do we need a risk assessment for a new SaaS tool that only stores public marketing data?", "B: Lightweight one. Fill the short form in {wiki}, no pen test needed.", "A: Thanks, that's less painful than I feared."],
        ["A: Phishing simulation results: {pct} clicked, {pct2} reported. Reporting is up on last quarter.", "B: Reporting rate is the metric to celebrate. Clicks will always happen.", "A: Agreed, sharing both in the monthly note."],
        ["A: {problem} found during the access review: a contractor still has admin on production.", "B: Revoke now, investigate after. Check logs for any use since their contract ended.", "A: Revoked. Log review shows no activity. Writing it up as a near miss."],
        ["A: Compliance wants a policy update on remote work and device encryption.", "B: Draft is in {wiki}. Main change: full-disk encryption verified by the MDM, not self-attested.", "A: Reviewing today. Attestation goes out Monday."],
      ],
      standup: [
        ["A: Yesterday: closed {n} access review items. Today: pen test remediation sync. Blocked: waiting on {team} for log samples."],
        ["A: Working on {task} (evidence for change management). {n} of {n2} controls done. ETA {day}.", "B: Finishing the vendor risk review for {cust}'s integration. Two questions out to their security team."],
        ["A: Standup: triaging alerts from {tool}, {n} real out of {big}. Tuning rules after lunch."],
        ["A: Out at the auditor kickoff all morning. Back at 1, ping me for urgent stuff."],
      ],
      blocker: [
        ["A: Blocked on {task}: the vendor won't share their SOC 2 report without an NDA and legal hasn't replied.", "B: Escalating to {@C} in legal. NDAs for security reviews should be a 24-hour thing.", "C: Sorry, it slipped through. Sending today."],
        ["A: We can't enforce MFA for the legacy app, it doesn't support SAML.", "B: Put it behind the access proxy. It handles auth in front of the app.", "A: That's the plan, but proxy capacity is tied up until {date}."],
        ["A: {problem} across {n} accounts and the owners aren't responding.", "B: Escalate to their managers with a deadline. I'll draft the note.", "A: Thanks. Remediation SLA starts from the notification date."],
        ["A: Auditors want evidence for a control that was changed mid-period.", "B: Provide both versions with the change record and approval dates. They'll ask about the gap.", "A: Pulling the change tickets now."],
      ],
      decision: [
        ["A: Decision: hardware security keys for all admins, passkeys for everyone else.", "B: Cost is fine, procurement approved {usd}.", "A: Ok, rollout starts {date}. ~rx:👍|✅ ~pin:Decision: key policy"],
        ["A: Should we accept the risk on the legacy printer firmware or isolate the VLAN?", "B: Isolate, it takes two hours and removes the risk entirely.", "A: Done, logging it as mitigated. ~rx:👍|✅"],
        ["A: Pen test cadence: annual external plus quarterly internal scoped scans, agreed?", "B: Yes, with a retest included in each report.", "A: Great, I'll update the policy. ~rx:👍"],
        ["A: Vulnerability SLA: critical 7 days, high 30, medium 90. Any objection?", "B: Fine as long as we get exceptions with an expiry date.", "A: Exceptions expire in 90 days, owner reapplies. ~rx:👍|✅"],
      ],
      launch: [
        ["A: Enforcement of {feature} starts {date}. After that, unenrolled users are prompted at sign-in and blocked after 7 days.", "B: Support is ready with scripts and a spare-key stock.", "A: Reminder emails go out Monday. ~rx:🚀|👍"],
        ["A: **We passed.** SOC 2 Type II, zero exceptions. 🎉", "B: Huge credit to everyone who chased evidence. ~rx:🎉|🏆|👏"],
        ["A: Tabletop exercise on {day}. Scenario: ransomware on a finance workstation. Execs are attending.", "B: I'll bring the comms templates. ~rx:👍"],
        ["A: Zero Trust rollout phase {n}: {team} and {team2} cut over this weekend. Rollback is a policy flag.", "B: Standing by with the helpdesk. ~rx:🙌"],
      ],
      chatter: [
        ["A: Reminder: if the CEO emails you gift card requests, it's not the CEO.", "B: It was my aunt last week."],
        ["A: Someone locked themselves out, again, with a hardware key they left at home.", "B: The key is at home. The cat is on the key. It's an ongoing situation."],
        ["A: Please stop screenshotting the QR code for MFA enrolment into Slack.", "B: Guilty. Deleting. 🙈"],
        ["A: Our phishing reports are up {pct}. Culture change is real.", "B: Reward the reporters, not the clickers. Stickers are in the post room."],
        ["A: Password manager tip: you can store the Wi-Fi password too.", "B: I'm taking that to the grave. ❤️"],
        ["A: Security awareness quiz results: top team gets lunch.", "B: Engineering by a nose, again."],
        ["A: Auditors are on site Monday, please wear your badges.", "B: Badge location confirmed, not in the other jacket."],
        ["A: {ack}, adding it to the register."],
        ["A: Anyone know why my laptop shows 'compliance: unknown'?", "B: MDM check-in is stale, run the sync from the menu.", "A: That fixed it. Thanks."],
        ["A: Fun fact: 'admin123' was found in {n} configs this quarter.", "B: I'd like to speak to the manager of fun facts."],
        ["A: Threat model review at 3pm, bring your worst-case thinking.", "B: Bringing coffee and pessimism."],
        ["A: I just got a security alert about my security alert system.", "B: Inception. 😅"],
      ],
      incident: [
        ["A: Suspicious sign-ins to {n} accounts from a new country within 10 minutes.", "B: Forcing re-auth and revoking sessions. Pulling logs.", "A: It's password spray, all from one ASN. No successful logins beyond the 2 accounts we've reset.", "B: Blocked the range at the edge. Writing the summary for {@me}.", "M: Thanks, please include the customer-impact statement even if it's 'none'."],
      ],
    },
  },
  infrastructure: {
    lex: {
      feature: ['the blue/green deploy pipeline', 'the new VPC layout', 'cluster autoscaling', 'the DR runbook', 'the service mesh', 'the cost allocation tags', 'the backup verification job', 'infrastructure drift detection', 'the golden AMI pipeline', 'zero-downtime database failover'],
      component: ['the Kubernetes control plane', 'the load balancer', 'the primary database', 'the Terraform state', 'the ingress controller', 'the NAT gateways', 'the object store', 'the observability stack', 'the CI runners', 'the DNS zone'],
      tool: ['Terraform', 'Kubernetes', 'Datadog', 'Argo CD', 'Prometheus', 'Ansible', 'Grafana', 'PagerDuty', 'Packer', 'Vault'],
      problem: ['a noisy-neighbour node', 'a certificate nearing expiry', 'a state lock that never released', 'an undersized node group', 'a runaway log volume', 'a failed rolling update', 'an IP exhaustion warning', 'a flaky health check', 'an orphaned volume bill', 'a misconfigured security group'],
      metric: ['availability', 'p99 latency', 'monthly cloud spend', 'deploy frequency', 'MTTR', 'error budget burn', 'cost per request', 'recovery time', 'node utilisation', 'change failure rate'],
      deliverable: ['the DR test report', 'the capacity plan', 'the migration schedule', 'the cost optimisation backlog', 'the SLO document', 'the change calendar', 'the architecture diagram', 'the runbook set', 'the compliance mapping', 'the post-incident report'],
      team: ['SRE', 'platform', 'cloud ops', 'networking', 'FinOps', 'database', 'security', 'release engineering'],
    },
    pools: {
      work: [
        ["A: Cluster utilisation is at {pct}. We're paying for a lot of idle nodes.", "B: Right-size the node groups and turn on bin-packing. I'd expect ~{pct2} savings.", "A: Plan: pilot on staging this week, production after the change freeze lifts.", "B: Put it in {wiki}, finance will ask for the numbers."],
        ["A: DR test results: recovered the primary in 22 minutes, target was 15.", "B: Where did the time go?", "A: Waiting on DNS TTL and a manual step to promote the replica. Automating both.", "B: Good. Retest next month."],
        ["A: Terraform plan shows {n} resources being replaced. That's not what I changed.", "B: Provider version bump. Pin it and re-plan.", "A: Pinned. Plan is clean now, one in-place update. Phew."],
        ["A: Proposal: error budget policy. If we burn >50% in the first half of the month, feature deploys pause.", "B: I like it, but who decides when it's lifted?", "A: SRE lead and the product owner together, documented in the incident channel."],
        ["A: Moved {n} services to the new VPC layout this week. No impact so far.", "B: Latency dashboards look normal. NAT cost drops by about a third.", "A: Next batch is the data services, need more care."],
        ["A: Why is the build queue 40 minutes today?", "B: Runner autoscaling cap is at 10 and a monorepo rebuild ate them all.", "A: Raised the cap to 25 and added a priority lane for hotfixes."],
        ["A: Logs bill is up {pct} month on month. Anyone know why?", "B: A debug flag got left on in one service. Rolled back, volume dropped immediately.", "A: Adding a budget alert on log ingestion."],
        ["A: Upgrade of the control plane to the next minor is scheduled for {date}.", "B: Check deprecated APIs first. Two of ours still use the old ingress version.", "A: Scanner found them, patching this week."],
      ],
      standup: [
        ["A: **Yesterday:** drift detection on 3 accounts. **Today:** {task} (node group rightsizing). **Blockers:** none"],
        ["A: Reviewing {pr} for the DNS cutover. Then {task}. Might need a hand with the rollback plan.", "B: Happy to pair after lunch."],
        ["A: Quiet night, one false page from the disk alert. Tuning the threshold today."],
        ["A: On change calendar duty. Three changes today, all low risk. Will confirm completion in {ch}."],
      ],
      blocker: [
        ["A: Blocked: the cloud provider quota for the region is capped and the increase request has been 'in review' for 4 days.", "B: Escalating through our account manager. I'll copy you.", "A: Meanwhile I'm using the secondary region for the test."],
        ["A: State lock on the shared Terraform workspace since yesterday. Nobody owns up.", "B: Force-unlock after checking the CI run isn't still going. It isn't.", "A: Unlocked. Adding an automated lock timeout."],
        ["A: Change freeze starts {date} but our migration needs {n} more days.", "B: Request an exception with a rollback plan, {@C} approves those.", "C: Send me the plan and I'll turn it around today."],
        ["A: The database vendor says the failover bug is fixed in the next patch release, not available until {date}.", "B: We can ride it out with a manual runbook. I'll make sure it's rehearsed."],
      ],
      decision: [
        ["A: Multi-region active/active or active/passive? Active/active doubles the cost and complexity.", "B: Active/passive with a tested 15-minute RTO is enough for this tier.", "A: Agreed. Recording in {wiki}. ~rx:👍|✅ ~pin:Decision: DR topology"],
        ["A: Reserved instances or savings plans for the steady-state workloads?", "B: Savings plans. Same discount, more flexibility.", "A: Approved by finance. ~rx:👍|✅"],
        ["A: Adopt Argo CD for all production deployments by {q}?", "B: Yes, with Terraform for infra and Argo for apps. One clear boundary.", "A: Done. ~rx:👍|✅"],
        ["A: Deprecate the old bastion hosts in favour of the access proxy?", "B: Yes, with a 30-day overlap.", "A: Announcing today. ~rx:👍"],
      ],
      launch: [
        ["A: Cutover window is {day} 02:00-04:00 UTC. Steps: freeze writes, final replication, flip DNS, verify, unfreeze.", "B: I'll be on the bridge. Rollback is DNS flip plus replica promote, 10 minutes.", "A: Status updates in {ch} every 15 minutes. ~rx:🚀"],
        ["A: Migration complete. Zero customer-visible downtime, p99 unchanged. 🎉", "B: Legendary. Cleaning up old resources next week. ~rx:🎉|🚀|👏"],
        ["A: The new VPC layout is live in production for all services.", "B: Great. Decommissioning the old subnets on {date}. ~rx:🎉"],
        ["A: SLO dashboards are live: {dash}. Error budget burn alerts are on.", "B: Finally, a shared definition of 'healthy'. ~rx:🙌"],
      ],
      chatter: [
        ["A: Turned it off and on again. Fixed it.", "B: The oldest runbook is still the best."],
        ["A: Someone left a 64-core instance running over the weekend.", "B: It was me. Please don't tell FinOps.", "C: FinOps is in this channel. 😅"],
        ["A: Pager went off at 3am for a disk at 81%.", "B: Raising the threshold. Sleep is a feature."],
        ["A: The datacentre aisle smells like new cables. Best smell.", "B: You need a hobby. 😄"],
        ["A: {ack}, deploying after lunch.", "B: 👍"],
        ["A: What's the difference between a pet and cattle server?", "B: One has a name and one has a number. Both page you at 3am."],
        ["A: New dashboards have too many gauges. I miss tables.", "B: Gauges are for executives, tables are for people who fix things."],
        ["A: Terraform destroy: the only command that makes my heart rate rise.", "B: Always read the plan. Always."],
        ["A: Free pizza at the on-call retro on {day}.", "B: Retro attendance has never been higher."],
        ["A: Cert renewal reminder, expires in {n} days.", "B: Renewing now, not on the last day this time."],
        ["A: DNS is always the culprit.", "B: It was DNS. It's always DNS."],
        ["A: Back from leave. What did I miss?", "B: Nothing, which is the best outcome for infra."],
      ],
      incident: [
        ["A: Alert: elevated 5xx from the ingress controller.", "B: One node group is saturated, a rolling update stalled with pods pending.", "A: Scaling the node group manually and cordoning the bad node.", "B: Errors back to baseline. Root cause: autoscaler max was too low. Fixing the config and adding an alert on pending pods. ~rx:🙏"],
      ],
    },
  },
};
