/** Kind vocabularies, part 2: finance, people, marketing, design, operations. */
import type { KindVocab } from './pmo-content-common';

export const FINANCE: KindVocab = {
  pools: {
    thing: [
      'the intercompany reconciliation', 'the month-end close checklist', 'the vendor master data', 'the three-way match', 'the chart of accounts mapping',
      'the accruals process', 'the fixed asset register', 'the revenue recognition schedule', 'the approval matrix', 'the expense policy rules',
      'the payment run', 'the budget template', 'the cash forecast', 'the cost-centre hierarchy', 'the FX revaluation', 'the tax reporting pack',
      'the purchase order workflow',
    ],
    sys: ['SAP S/4HANA', 'Coupa', 'Anaplan', 'Blackline', 'Power BI', 'Workato', 'the general ledger'],
    vendor: ['SAP', 'Coupa', 'Anaplan', 'Blackline', 'Workday', 'Deloitte', 'KPMG'],
    metric: ['days to close', 'touchless invoice rate', 'manual journal entries', 'forecast accuracy', 'DPO', 'first-pass match rate'],
    cohort: ['budget owners', 'accounts payable', 'the controllership team', 'regional finance leads', 'approvers'],
  },
  titles: {
    plan: [
      'Map the current close calendar and identify tasks that can move earlier',
      'Define the future-state chart of accounts and mapping rules',
      'Agree the approval thresholds for {thing} with {team}',
      'Document the policy changes needed for {thing}',
      'Build the business case for {thing} with the benefits tracked by Finance',
      'Plan the data cleansing for {thing} ahead of the migration',
      'Scope the audit evidence needed for {thing}',
      'Agree the cutover calendar with the external auditors',
    ],
    build: [
      'Configure the posting rules for {thing} in {sys}',
      'Build the automated reconciliation for {thing}',
      'Migrate open items for {thing} to the new ledger',
      'Set up the approval workflow for purchase orders above {amount}',
      'Create the variance report for {cohort}',
      'Automate the journal entry for {thing}',
      'Cleanse duplicate vendors from the master data',
      'Integrate {sys} with the payroll feed',
      'Configure tax codes for {region}',
      'Build the self-service budget view for {cohort}',
      'Replace the spreadsheet for {thing} with a governed model',
      'Create the intercompany netting rules for {region}',
    ],
    verify: [
      'Run the parallel close for {thing} and compare with the legacy results',
      'UAT of {thing} with {cohort}',
      'Reconcile the opening balances after the migration',
      'Test the segregation-of-duties rules for {thing}',
      'Sample 40 invoices through the new flow and check the postings',
      'Validate the FX rates used in {thing} against treasury',
    ],
    rollout: [
      'Go live with {thing} for {region}',
      'Train {cohort} and track completion',
      'Run the first live month-end close on the new process',
      'Switch off the legacy approval emails',
      'Cut over the payment run for {region}',
    ],
    ops: [
      'Review the first close: what slipped and why',
      'Close out the open reconciling items older than 60 days',
      'Update the finance policy portal for {thing}',
      'Tune the matching tolerances for {thing}',
      'Archive the legacy ledger extracts for the audit trail',
    ],
    comms: [
      'Send the close calendar to {cohort}',
      'Write the one-page guide for submitting {thing}',
      'Present the benefits realised so far to the CFO staff meeting',
      'Brief the auditors on the control changes',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Finance transformation roadmap'],
    sprint: ['Sprint {n}', 'Wave {n} configuration'],
    launch: ['Go-live & hypercare', 'Cutover plan'],
    backlog: ['Backlog', 'Open items'],
    risk: ['Controls & audit', 'Compliance evidence'],
    vendor: ['Vendor & implementation partner', 'Procurement & contracts'],
    discovery: ['Requirements & process mapping'],
    enable: ['Training & change management'],
  },
  folders: ['Policies', 'Reconciliations', 'Contracts', 'Meeting notes', 'Reports', 'Audit', 'Training'],
  files: [
    'Policies|Approval matrix v{n}.xlsx', 'Policies|Expense policy draft.docx', 'Policies|Close calendar {q}.pdf',
    'Reconciliations|Intercompany balances {q}.xlsx', 'Reconciliations|Open items aging.xlsx', 'Reports|Variance analysis.xlsx',
    'Reports|Benefits tracker.xlsx', 'Contracts|Implementation partner SOW.pdf', 'Contracts|License order form.pdf',
    'Audit|Control matrix.xlsx', 'Audit|Auditor request list.xlsx', 'Training|Approver quick guide.pdf',
  ],
  notes: {
    meeting: ['Close readiness meeting', 'Steering committee notes', 'Process owner workshop'],
    rfc: ['Design: chart of accounts', 'Design: approval workflow', 'Design: intercompany'],
    runbook: ['Month-end close runbook', 'Payment run runbook'],
    retro: ['First close retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Design decision log'],
    brief: ['Finance glossary and definitions'],
  },
  boards: [
    ['flow', 'Procure-to-pay flow'],
    ['journey', 'Month-end close timeline'],
    ['retro', 'Close retro board'],
  ],
};

export const PEOPLE: KindVocab = {
  pools: {
    thing: [
      'the new-hire checklist', 'the onboarding portal', 'the performance review cycle', 'the job architecture', 'the compensation bands',
      'the manager toolkit', 'the leave policy', 'the employee data migration', 'the learning catalog', 'the engagement survey',
      'the equity plan communications', 'the hybrid work guidelines', 'the offboarding workflow', 'the HR case management queue', 'the buddy programme',
      'the calibration process', 'the benefits enrollment window',
    ],
    sys: ['Workday', 'Greenhouse', 'Culture Amp', 'Okta', 'Workato', 'the HRIS'],
    vendor: ['Workday', 'Greenhouse', 'Culture Amp', 'Cornerstone', 'Deel', 'ADP'],
    metric: ['time to productivity', 'onboarding completion', 'manager NPS', 'survey response rate', 'HR ticket volume', 'regretted attrition'],
    cohort: ['new hires', 'people managers', 'the {region} workforce', 'HR business partners', 'the October starters'],
  },
  titles: {
    plan: [
      'Map the onboarding journey from offer to day 90',
      'Define the new job architecture and levelling guide',
      'Agree the data privacy approach for {thing} with Legal',
      'Plan the rollout waves by region and legal entity',
      'Draft the manager communication plan for {thing}',
      'Review {thing} with the works council representatives in {region}',
      'Confirm eligibility rules for {thing}',
      'Design the calibration process and the guidance for managers',
    ],
    build: [
      'Configure {thing} in {sys} for {region}',
      'Migrate employee records for the {region} entity',
      'Build the manager dashboard for {thing}',
      'Set up the integration between {sys} and the identity provider',
      'Automate provisioning tasks for new hires',
      'Create the survey questions and the reporting hierarchy',
      'Translate {thing} into the five supported languages',
      'Configure the approval flow for {thing}',
      'Clean up duplicate worker profiles before the migration',
      'Build the self-service flow for {thing}',
    ],
    verify: [
      'Validate migrated payroll-relevant fields for a sample of 200 employees',
      'Run the manager pilot for {thing} and collect feedback',
      'Compliance check of {thing} for {region}',
      'UAT with HR business partners for {thing}',
      'Parallel-run the old and new versions of {thing} for one cycle',
      'Check accessibility of the portal on mobile and screen readers',
    ],
    rollout: [
      'Launch {thing} to {cohort}',
      'Roll out the wave for {region} and monitor the support queue',
      'Open the enrollment window for {thing}',
      'Retire the old spreadsheet-based process for {thing}',
      'Cut over payroll feeds for the {region} entity',
    ],
    ops: [
      'Review the top ten HR tickets raised since launch',
      'Update the knowledge base articles for {thing}',
      'Close the migration defects with {team}',
      'Check data privacy access logs for {thing}',
      'Collect the lessons learned from the {region} wave',
    ],
    comms: [
      'Write the all-hands announcement for {thing}',
      'Run manager briefings for {cohort}',
      'Send the reminder for {thing} to {cohort}',
      'Record the how-to video for {thing}',
      'Publish the FAQ in the people portal',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'People programme roadmap'],
    sprint: ['Sprint {n}', 'Wave {n}'],
    launch: ['Launch readiness', 'Rollout waves'],
    backlog: ['Backlog', 'Requests & improvements'],
    risk: ['Compliance & works councils', 'Risks & data privacy'],
    vendor: ['Vendor management', 'Implementation partner'],
    discovery: ['Discovery & requirements'],
    enable: ['Change management & comms', 'Manager enablement'],
  },
  folders: ['Policies', 'Communications', 'Training', 'Meeting notes', 'Reports', 'Vendor docs', 'Legal reviews'],
  files: [
    'Policies|Leave policy v{n}.docx', 'Policies|Job architecture.xlsx', 'Policies|Levelling guide.pdf',
    'Communications|Manager briefing deck.pptx', 'Communications|Announcement draft.docx', 'Communications|FAQ for employees.pdf',
    'Training|Manager toolkit.pdf', 'Training|Onboarding checklist.xlsx', 'Reports|Engagement survey results {q}.pdf',
    'Reports|Migration validation report.xlsx', 'Vendor docs|Implementation SOW.pdf', 'Legal reviews|Works council notes.docx',
  ],
  notes: {
    meeting: ['People steering committee', 'HRBP weekly sync', 'Works council consultation notes'],
    rfc: ['Design: onboarding journey', 'Design: review cycle', 'Design: data migration'],
    runbook: ['Wave cutover runbook', 'Offboarding runbook'],
    retro: ['Wave retrospective', 'Pilot retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Manager FAQ'],
  },
  boards: [
    ['journey', 'New-hire journey map'],
    ['flow', 'Review cycle flow'],
    ['retro', 'Wave retro board'],
  ],
};

export const MARKETING: KindVocab = {
  pools: {
    thing: [
      'the homepage hero', 'the launch landing page', 'the nurture email sequence', 'the keynote storyline', 'the sponsor prospectus',
      'the brand guidelines', 'the case study programme', 'the paid social campaign', 'the webinar series', 'the lead scoring model',
      'the product video', 'the press kit', 'the partner co-marketing plan', 'the content calendar', 'the speaker lineup', 'the registration page',
      'the event app',
    ],
    sys: ['HubSpot', 'Salesforce', 'Contentful', 'Figma', 'Segment', 'Google Analytics'],
    vendor: ['HubSpot', 'Contentful', 'Cvent', 'Hootsuite', 'Wistia', 'Semrush'],
    metric: ['marketing-sourced pipeline', 'cost per lead', 'registration conversion', 'organic traffic', 'MQL to SQL rate', 'email open rate'],
    cohort: ['enterprise prospects', 'existing customers', 'channel partners', 'the {region} audience', 'press and analysts'],
  },
  titles: {
    plan: [
      'Write the campaign brief for {thing}',
      'Agree the messaging hierarchy with Product Marketing',
      'Build the budget and the channel mix for {thing}',
      'Confirm the venue, dates and capacity for {region}',
      'Align sales on the target accounts for {thing}',
      'Draft the content calendar for {quarter}',
      'Define the measurement plan and UTM conventions for {thing}',
      'Review the competitive positioning with {team}',
    ],
    build: [
      'Design {thing} in the new brand system',
      'Write the copy for {thing} and send it to Legal for review',
      'Build the landing page for {thing} in the CMS',
      'Set up the lead routing between {sys} and Salesforce',
      'Produce the video for {thing}',
      'Create the A/B test plan for {thing}',
      'Migrate the top 200 pages to the new templates',
      'Localise {thing} for {region}',
      'Build the email templates for {thing}',
      'Set up the tracking for {thing} in analytics',
      'Prepare the speaker briefs and slide templates',
      'Create the social asset kit for {thing}',
    ],
    verify: [
      'Proof every asset for {thing} against the brand checklist',
      'QA the forms, tracking and redirects on {thing}',
      'Send test emails to the seed list and check rendering',
      'Legal and brand sign-off for {thing}',
      'Review the first week of results against the plan for {thing}',
      'Accessibility check of {thing}',
    ],
    rollout: [
      'Launch {thing} to {cohort}',
      'Open registration for {thing}',
      'Switch DNS and redirects to the new site',
      'Send the first wave of the nurture sequence',
      'Brief the {region} field marketers on {thing}',
    ],
    ops: [
      'Weekly performance review of {thing}',
      'Clean up the old campaign assets and archive them',
      'Reconcile spend against the budget for {thing}',
      'Fix broken links reported after the migration',
      'Update the lead scoring thresholds with Sales Ops',
    ],
    comms: [
      'Draft the press release for {thing}',
      'Brief the executive spokespeople ahead of {thing}',
      'Publish the recap blog post and the highlights video',
      'Send the thank-you note and survey to attendees',
      'Share the results readout with the leadership team',
    ],
  },
  lists: {
    roadmap: ['Campaign roadmap', 'Roadmap', 'Plan & milestones'],
    sprint: ['Sprint {n}', 'Production sprint {n}'],
    launch: ['Launch readiness', 'Event week checklist'],
    backlog: ['Backlog', 'Content backlog'],
    risk: ['Legal & brand review'],
    vendor: ['Agencies & vendors', 'Vendor management'],
    discovery: ['Strategy & positioning'],
    enable: ['Field enablement', 'Sales enablement'],
  },
  folders: ['Creative', 'Copy', 'Brand', 'Meeting notes', 'Reports', 'Agencies', 'Event logistics'],
  files: [
    'Creative|Hero concepts round {n}.png', 'Creative|Social asset kit.zip', 'Creative|Event signage.pdf',
    'Copy|Campaign brief.docx', 'Copy|Landing page copy v{n}.docx', 'Copy|Press release draft.docx',
    'Brand|Brand guidelines.pdf', 'Brand|Logo pack.zip', 'Reports|Campaign performance {q}.xlsx',
    'Reports|Pipeline attribution.xlsx', 'Agencies|Agency SOW.pdf', 'Event logistics|Venue contract.pdf',
  ],
  notes: {
    meeting: ['Campaign sync', 'Agency check-in', 'Launch readiness review'],
    rfc: ['Brief: campaign strategy', 'Brief: messaging framework'],
    runbook: ['Launch day runbook', 'Event week runbook'],
    retro: ['Campaign retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Creative brief', 'Messaging house'],
  },
  boards: [
    ['journey', 'Customer journey and touchpoints'],
    ['flow', 'Launch week flow'],
    ['retro', 'Campaign retro board'],
  ],
};

export const DESIGN: KindVocab = {
  pools: {
    thing: [
      'the button component', 'the data table', 'the date picker', 'the navigation pattern', 'the form validation messages',
      'the colour tokens', 'the empty states', 'the modal and drawer patterns', 'the icon set', 'the typography scale',
      'the chart components', 'the focus ring style', 'the toast notifications', 'the page templates', 'the illustration set',
      'the dark theme', 'the loading skeletons',
    ],
    sys: ['Figma', 'Storybook', 'Style Dictionary', 'React', 'Playwright', 'axe-core'],
    vendor: ['Figma', 'Chromatic', 'Deque', 'Zeroheight', 'Maze', 'UserTesting'],
    metric: ['component adoption', 'contrast failures', 'design-to-dev handoff time', 'accessibility violations', 'task success rate', 'time on task'],
    cohort: ['product squads', 'the web team', 'the mobile team', 'new designers', 'external agencies'],
  },
  titles: {
    plan: [
      'Audit the existing screens for inconsistencies in {thing}',
      'Define the principles and contribution model for {subj}',
      'Plan the component migration order based on usage',
      'Agree the accessibility acceptance criteria for {thing}',
      'Write the usage guidelines for {thing}',
      'Prioritise the issues found in the WCAG audit by severity',
      'Draft the research plan for {thing} with eight participants',
      'Scope the token architecture across web and mobile',
    ],
    build: [
      'Design {thing} with all states and variants',
      'Build {thing} as a coded component with tests',
      'Add keyboard support and ARIA roles to {thing}',
      'Publish the new tokens for {thing} to the package registry',
      'Fix colour contrast failures in {thing}',
      'Document {thing} with live examples and do/don\'t guidance',
      'Migrate {thing} in the checkout flow to the new components',
      'Create the Figma library variables for {thing}',
      'Write visual regression tests for {thing}',
      'Remove the deprecated variants of {thing}',
      'Add reduced-motion behaviour to {thing}',
    ],
    verify: [
      'Run the screen reader pass on {thing} with VoiceOver and NVDA',
      'Moderated usability test of {thing} with {n} participants',
      'Design QA of {thing} against the specs',
      'Cross-browser check of {thing}',
      'Retest the remediated issues with the external auditor',
      'Review the pull request for {thing} with the design lead',
    ],
    rollout: [
      'Release the components for {thing} in version 3.0',
      'Migrate {cohort} to the new library',
      'Announce the deprecation of the old version of {thing}',
      'Run the codemod across the monorepo and review the diffs',
      'Switch the default theme to the new tokens',
    ],
    ops: [
      'Triage the incoming requests in the design system channel',
      'Update the changelog and the migration notes',
      'Review adoption numbers and contact the lagging teams',
      'Fix the Storybook build warnings',
      'Close out stale Figma comments and archive old files',
    ],
    comms: [
      'Present {thing} at the design critique',
      'Write the release announcement for {cohort}',
      'Record a short demo of {thing}',
      'Hold the monthly office hours for {cohort}',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Design system roadmap'],
    sprint: ['Sprint {n}', 'Component sprint {n}'],
    launch: ['Release 3.0 readiness', 'Launch readiness'],
    backlog: ['Backlog', 'Requests & fixes'],
    risk: ['Accessibility audit', 'Accessibility remediation'],
    discovery: ['Research & discovery'],
    enable: ['Adoption & enablement'],
  },
  folders: ['Design files', 'Research', 'Specs', 'Meeting notes', 'Audits', 'Guidelines', 'Assets'],
  files: [
    'Design files|Component library export.fig', 'Design files|Token spec v{n}.json', 'Design files|Pattern gallery.pdf',
    'Research|Usability test summary.pdf', 'Research|Interview notes {q}.docx', 'Research|Survey results.xlsx',
    'Audits|WCAG audit report.pdf', 'Audits|Issue tracker export.csv', 'Guidelines|Usage guidelines.pdf',
    'Guidelines|Accessibility checklist.md', 'Assets|Icon set.svg', 'Specs|Contribution guide.docx',
  ],
  notes: {
    meeting: ['Design critique notes', 'Office hours notes', 'Accessibility working group'],
    rfc: ['RFC: token architecture', 'RFC: component API conventions', 'RFC: theming'],
    runbook: ['Release runbook', 'Deprecation procedure'],
    retro: ['Release retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Contribution guidelines'],
  },
  boards: [
    ['architecture', 'Token architecture'],
    ['journey', 'Adoption journey for product squads'],
    ['retro', 'Release retro board'],
  ],
};

export const OPERATIONS: KindVocab = {
  pools: {
    thing: [
      'the dock scheduling process', 'the pick-and-pack line', 'the facilities move plan', 'the emergency response procedure', 'the critical supplier list',
      'the safety induction', 'the floor layout', 'the conveyor commissioning', 'the cutover weekend plan', 'the shift pattern',
      'the business impact analysis', 'the call tree', 'the helpdesk macros', 'the escalation matrix', 'the recovery time objectives',
      'the equipment inventory', 'the move-in checklist',
    ],
    sys: ['SAP EWM', 'ServiceNow', 'Power BI', 'the WMS', 'the ticketing system'],
    vendor: ['Honeywell', 'Zebra', 'ServiceNow', 'Kuehne+Nagel', 'JLL', 'Zendesk'],
    metric: ['throughput per hour', 'unplanned downtime', 'order cycle time', 'first-contact resolution', 'recovery time', 'safety incidents'],
    cohort: ['the day shift', 'the pilot zone', 'site supervisors', 'floor associates', 'the support agents'],
  },
  titles: {
    plan: [
      'Write the detailed cutover plan for {thing}',
      'Complete the business impact analysis for {thing}',
      'Agree the shift pattern for {thing} with the site leads',
      'Plan the move sequence floor by floor',
      'Review the capital budget forecast with {team}',
      'Define the safety requirements for {thing}',
      'Confirm the contingency plan if the cutover slips',
      'Map the critical processes and their recovery time objectives',
    ],
    build: [
      'Commission {thing} and record the acceptance test results',
      'Configure {thing} in {sys}',
      'Install and label the new equipment for {thing}',
      'Rewire the network drops for {thing}',
      'Update the standard operating procedures for {thing}',
      'Set up the dashboards for {metric}',
      'Build the training simulator for {cohort}',
      'Migrate the ticket queues and macros to the new platform',
      'Prepare the temporary workspace for {cohort}',
      'Order the long-lead items for {thing}',
    ],
    verify: [
      'Dry-run {thing} over a weekend with {cohort}',
      'Safety walkthrough with the site manager',
      'Measure {metric} before and after the change',
      'Inspection by the fire marshal and the insurer',
      'Test the call tree and record how long it takes',
      'Validate the data after the system cutover',
    ],
    rollout: [
      'Go live with {thing} for {cohort}',
      'Start the shift handover on the new process',
      'Move the {region} team into the new space',
      'Decommission the old equipment and arrange disposal',
      'Switch the support queue to the consolidated platform',
    ],
    ops: [
      'Review the first week of {metric}',
      'Close the punch list from the commissioning',
      'Update the emergency contact sheet',
      'Fix the issues raised by {cohort} in the first week',
      'Reorder consumables and spares for {thing}',
    ],
    comms: [
      'Brief {cohort} before the go-live',
      'Post the move schedule and the floor map',
      'Write the daily cutover update for the leadership group',
      'Publish the lessons learned from {thing}',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Program plan'],
    sprint: ['Phase {n}', 'Work package {n}'],
    launch: ['Cutover & go-live', 'Go-live checklist', 'Move weekend'],
    backlog: ['Punch list', 'Backlog'],
    risk: ['Safety & compliance', 'Risks & contingency'],
    vendor: ['Vendors & contractors', 'Procurement'],
    discovery: ['Assessment & planning'],
    enable: ['Training & change management'],
  },
  folders: ['Plans', 'Safety', 'Contracts', 'Meeting notes', 'Reports', 'Floor plans', 'Training'],
  files: [
    'Plans|Cutover plan v{n}.pdf', 'Plans|Move schedule.xlsx', 'Plans|Business impact analysis.xlsx',
    'Safety|Site safety plan.pdf', 'Safety|Inspection checklist.docx', 'Floor plans|Floor layout.png',
    'Floor plans|Equipment placement.pdf', 'Contracts|Contractor agreement.pdf', 'Reports|Weekly progress report.pdf',
    'Reports|Throughput tracker {q}.xlsx', 'Training|Induction deck.pptx', 'Training|Quick reference card.pdf',
  ],
  notes: {
    meeting: ['Site coordination meeting', 'Weekly program review', 'Safety committee notes'],
    rfc: ['Plan: cutover approach', 'Plan: continuity strategy'],
    runbook: ['Cutover weekend runbook', 'Emergency response procedure'],
    retro: ['Phase retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Site handbook'],
  },
  boards: [
    ['flow', 'Material flow through the site'],
    ['journey', 'Cutover weekend timeline'],
    ['retro', 'Phase retro board'],
  ],
};
