/** Kind vocabularies, part 3: legal, research, supply-chain, customer, sales. */
import type { KindVocab } from './pmo-content-common';

export const LEGAL: KindVocab = {
  pools: {
    thing: [
      'the record of processing activities', 'the standard contract templates', 'the data subject request intake form', 'the retention schedule', 'the vendor DPA register',
      'the consent banner', 'the approval workflow for non-standard terms', 'the clause library', 'the privacy impact assessment', 'the policy review calendar',
      'the cross-border transfer assessment', 'the cookie inventory', 'the legal hold process', 'the subprocessor list', 'the e-signature workflow',
      'the contract repository', 'the regulator correspondence log',
    ],
    sys: ['Ironclad', 'OneTrust', 'ServiceNow', 'DocuSign', 'Workato', 'the CLM'],
    vendor: ['Ironclad', 'OneTrust', 'DocuSign', 'Relativity', 'Thomson Reuters', 'Linklaters'],
    metric: ['request turnaround', 'contract cycle time', 'template usage', 'overdue requests', 'policy attestation rate', 'audit findings'],
    cohort: ['business owners', 'the sales team', 'procurement', 'the privacy champions', 'all people managers'],
  },
  titles: {
    plan: [
      'Inventory the personal data flows for {thing}',
      'Draft the statutory response procedure for {thing}',
      'Agree the risk appetite for non-standard terms with {team}',
      'Map the requirements of CCPA, LGPD and GDPR for {thing}',
      'Review the existing contracts for {thing} and rank them by risk',
      'Define the owner and review cycle for each policy',
      'Scope the repository migration for {thing}',
      'Write the playbook for regulator enquiries on {thing}',
    ],
    build: [
      'Configure {thing} in {sys}',
      'Draft the fallback clauses for {thing}',
      'Automate the intake and the identity verification for {thing}',
      'Build the dashboard for {metric}',
      'Migrate the 4,000 active contracts into {sys}',
      'Create the approval rules for {thing}',
      'Digitise the legacy paper agreements flagged by Compliance',
      'Connect {sys} to the HRIS so owners are always current',
      'Redact and export the data package for {thing}',
      'Update the templates for {region} law',
    ],
    verify: [
      'Run 20 mock requests through {thing} and time each step',
      'External counsel review of {thing}',
      'Sample the migrated contracts for metadata accuracy',
      'Test the approval routing with {cohort}',
      'Validate that deletions in {thing} reach the downstream systems',
      'Internal audit walkthrough for {thing}',
    ],
    rollout: [
      'Launch {thing} to {cohort}',
      'Switch off the shared mailbox intake for {thing}',
      'Publish the new templates to {region}',
      'Run the policy attestation campaign for {cohort}',
      'Go live with the {region} privacy notice',
    ],
    ops: [
      'Review the overdue items with {team}',
      'Clear the intake backlog from the first month',
      'Refresh the register of processing activities after the latest changes',
      'Check the sub-processor changes for the quarter',
      'File the regulatory submission for {region}',
    ],
    comms: [
      'Write the guidance for {cohort}',
      'Run the training session for {cohort}',
      'Send the policy reminder and track attestations',
      'Prepare the board briefing on the privacy programme',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Programme plan'],
    sprint: ['Sprint {n}', 'Workstream {n}'],
    launch: ['Launch readiness', 'Rollout plan'],
    backlog: ['Backlog', 'Open items'],
    risk: ['Compliance evidence', 'Regulatory tracker'],
    vendor: ['Vendor & counsel', 'Procurement & contracts'],
    discovery: ['Requirements & legal analysis'],
    enable: ['Training & awareness'],
  },
  folders: ['Policies', 'Contract templates', 'Regulatory', 'Meeting notes', 'Assessments', 'Vendor DPAs', 'Training'],
  files: [
    'Policies|Data retention policy v{n}.pdf', 'Policies|Privacy notice draft.docx', 'Policies|Policy review calendar.xlsx',
    'Contract templates|Master services agreement.docx', 'Contract templates|NDA mutual.docx', 'Contract templates|Clause library.xlsx',
    'Assessments|Privacy impact assessment.pdf', 'Assessments|Transfer impact assessment.pdf', 'Regulatory|Regulator correspondence log.xlsx',
    'Regulatory|Requirements matrix.xlsx', 'Vendor DPAs|DPA register.xlsx', 'Training|Business owner training.pptx',
  ],
  notes: {
    meeting: ['Privacy working group', 'Counsel review notes', 'Business owner sync'],
    rfc: ['Position paper: retention periods', 'Position paper: transfers', 'Position paper: template strategy'],
    runbook: ['Request handling runbook', 'Legal hold procedure'],
    retro: ['Rollout retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Legal positions log'],
    brief: ['Guidance for business owners'],
  },
  boards: [
    ['flow', 'Request handling flow'],
    ['architecture', 'Systems and data flows'],
    ['retro', 'Rollout retro board'],
  ],
};

export const RESEARCH: KindVocab = {
  pools: {
    thing: [
      'the retrieval pipeline', 'the evaluation set', 'the prompt templates', 'the embedding model comparison', 'the red-team scenarios',
      'the cost-per-query model', 'the latency benchmark', 'the guardrail layer', 'the grounding data sources', 'the pilot user group',
      'the data-handling boundary', 'the feasibility scorecard', 'the prototype', 'the vendor shortlist', 'the experiment log',
      'the approval path for model providers', 'the hardware test bench',
    ],
    sys: ['PyTorch', 'LangChain', 'pgvector', 'AWS Bedrock', 'Jupyter', 'the vector store'],
    vendor: ['Anthropic', 'AWS Bedrock', 'Hugging Face', 'Nvidia', 'Cloudflare', 'Pinecone'],
    metric: ['answer accuracy', 'p95 latency', 'cost per 1k queries', 'hallucination rate', 'user-rated helpfulness', 'throughput'],
    cohort: ['the pilot group of 40 employees', 'support agents', 'the legal team', 'engineers in two squads', 'the research reading group'],
  },
  titles: {
    plan: [
      'Define the evaluation criteria and the test set before building anything',
      'Write the research question and the success threshold for {thing}',
      'Agree the data-handling boundaries for {thing} with Security',
      'Review the literature and existing vendor offerings on {thing}',
      'Draft the go / no-go criteria for the pilot',
      'Estimate cost to scale {thing} to the full user base',
      'Select the shortlisted approaches to compare for {thing}',
      'Plan the pilot with {cohort} and the feedback loop',
    ],
    build: [
      'Prototype {thing} on the evaluation set',
      'Build the baseline for {thing} so we can measure improvement',
      'Implement the guardrails for {thing}',
      'Add citation of sources to the answers from {thing}',
      'Index the knowledge base content for {thing}',
      'Write the benchmark harness for {metric}',
      'Reduce {metric} by caching and batching in {thing}',
      'Compare three embedding models on the internal corpus',
      'Create the red-team scenarios for {thing}',
      'Instrument {thing} to log prompts without storing personal data',
    ],
    verify: [
      'Run the evaluation and record {metric} for each approach',
      'Human review of 200 sampled answers by domain experts',
      'Red-team session with Security for {thing}',
      'Check that no restricted data leaves the boundary in {thing}',
      'Repeat the benchmark on fresh data to rule out overfitting',
      'Analyse the pilot feedback from {cohort}',
    ],
    rollout: [
      'Open the pilot to {cohort}',
      'Extend the pilot to the second group and compare results',
      'Shut down the pilot environment and archive the logs',
      'Present the go / no-go recommendation to the steering committee',
    ],
    ops: [
      'Review the weekly usage and cost report for {thing}',
      'Tidy up the experiment log and reproduce the three key results',
      'Rotate the keys used by the prototype',
      'Triage the open feedback items from {cohort}',
    ],
    comms: [
      'Write the findings summary for the research readout',
      'Present the interim results to {team}',
      'Publish the evaluation method internally so others can reuse it',
      'Prepare the demo script for {thing}',
    ],
  },
  lists: {
    roadmap: ['Research plan', 'Roadmap'],
    sprint: ['Experiment cycle {n}', 'Sprint {n}'],
    launch: ['Pilot launch', 'Pilot readiness'],
    backlog: ['Backlog', 'Ideas to test'],
    risk: ['Risks & guardrails', 'Security & data handling'],
    vendor: ['Vendor evaluation'],
    discovery: ['Discovery & feasibility', 'Literature & landscape'],
    enable: ['Pilot enablement'],
  },
  folders: ['Experiments', 'Reports', 'Datasets', 'Meeting notes', 'Vendor material', 'Security review', 'Pilot feedback'],
  files: [
    'Experiments|Evaluation results v{n}.xlsx', 'Experiments|Benchmark harness readme.md', 'Experiments|Experiment log.csv',
    'Reports|Interim findings {q}.pdf', 'Reports|Cost model.xlsx', 'Datasets|Evaluation set description.docx',
    'Security review|Data handling assessment.pdf', 'Security review|Red-team findings.pdf', 'Vendor material|Vendor comparison.xlsx',
    'Pilot feedback|Survey results.xlsx', 'Pilot feedback|Interview notes.docx', 'Reports|Architecture sketch.png',
  ],
  notes: {
    meeting: ['Research sync', 'Pilot feedback session', 'Security review notes'],
    rfc: ['Proposal: evaluation approach', 'Proposal: data boundary', 'Proposal: pilot design'],
    runbook: ['Pilot operations runbook'],
    retro: ['Experiment retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Evaluation rubric'],
  },
  boards: [
    ['architecture', 'Prototype architecture'],
    ['flow', 'Evaluation pipeline'],
    ['retro', 'Experiment retro board'],
  ],
};

export const SUPPLY_CHAIN: KindVocab = {
  pools: {
    thing: [
      'the supplier scorecard', 'the carrier rate cards', 'the safety stock parameters', 'the demand plan', 'the purchase order acknowledgment flow',
      'the lane analysis', 'the inbound appointment scheduling', 'the packaging specification', 'the tariff classification file', 'the return flow',
      'the S&OP cycle', 'the supplier onboarding checklist', 'the freight audit', 'the slotting rules', 'the replenishment model',
      'the last-mile route plan', 'the vendor-managed inventory pilot',
    ],
    sys: ['SAP IBP', 'project44', 'Manhattan WMS', 'Snowflake', 'OR-Tools', 'the TMS'],
    vendor: ['project44', 'Manhattan Associates', 'Maersk', 'DHL', 'Flexport', 'Coupa'],
    metric: ['on-time-in-full', 'inventory days of supply', 'expedited freight spend', 'cost per delivery', 'forecast bias', 'supplier lead time'],
    cohort: ['the top 50 suppliers', 'the {region} carriers', 'planners', 'the pilot distribution centre', 'warehouse supervisors'],
  },
  titles: {
    plan: [
      'Model the impact of the new tariff schedule on landed cost for {thing}',
      'Segment suppliers by criticality and risk',
      'Agree the service level targets for {thing} with Sales',
      'Define the data requirements for {thing} with {cohort}',
      'Draft the sourcing strategy for the {region} market',
      'Plan the pilot at the first distribution centre',
      'Review twelve months of history to calibrate {thing}',
      'Scope the supplier onboarding wave for {quarter}',
    ],
    build: [
      'Build the optimisation model for {thing}',
      'Integrate {sys} with the supplier portal for {thing}',
      'Automate the weekly refresh of {thing}',
      'Create the exception dashboard for {metric}',
      'Replace the spreadsheet for {thing} with a governed model',
      'Implement EDI for order acknowledgments with {cohort}',
      'Set up the carrier API for tracking updates',
      'Tune the safety stock parameters for the top 500 SKUs',
      'Configure the slotting rules for the pilot site',
      'Add the packaging weight and recyclability fields to the item master',
    ],
    verify: [
      'Backtest {thing} against the last twelve months of data',
      'Validate the supplier data with the category managers',
      'Run the pilot at the first distribution centre for four weeks and compare {metric}',
      'Reconcile the freight audit results with Finance',
      'Check that planners trust the numbers: run a blind comparison against the manual plan',
      'Simulate a port closure scenario for {thing}',
    ],
    rollout: [
      'Onboard {cohort} to the supplier portal',
      'Roll out {thing} to the {region} distribution centres',
      'Switch the planners to the new model for the next S&OP cycle',
      'Retire the legacy macros for {thing}',
      'Start the vendor-managed inventory pilot with two suppliers',
    ],
    ops: [
      'Review the weekly {metric} with {team}',
      'Resolve the data quality issues found in the pilot',
      'Review the exceptions queue and clear the oldest items',
      'Update the contact list for carriers and suppliers',
      'Audit the freight invoices flagged by the system',
    ],
    comms: [
      'Brief {cohort} on the changes and what we need from them',
      'Write the supplier guide for the portal',
      'Present the savings tracker at the operations review',
      'Send the weekly service level report to {team}',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Programme roadmap'],
    sprint: ['Sprint {n}', 'Wave {n}'],
    launch: ['Pilot & rollout', 'Launch readiness'],
    backlog: ['Backlog', 'Open items'],
    risk: ['Risk & compliance', 'Contingency planning'],
    vendor: ['Supplier & carrier management', 'Supplier onboarding'],
    discovery: ['Analysis & discovery'],
    enable: ['Planner enablement', 'Training & change'],
  },
  folders: ['Analysis', 'Suppliers', 'Reports', 'Meeting notes', 'Contracts', 'Process maps', 'Training'],
  files: [
    'Analysis|Lane analysis {q}.xlsx', 'Analysis|Tariff impact model v{n}.xlsx', 'Analysis|Safety stock review.xlsx',
    'Suppliers|Supplier scorecard.xlsx', 'Suppliers|Onboarding checklist.docx', 'Suppliers|Supplier guide.pdf',
    'Reports|Service level report.pdf', 'Reports|Savings tracker.xlsx', 'Process maps|As-is process map.png',
    'Process maps|To-be process map.png', 'Contracts|Carrier agreement summary.pdf', 'Training|Planner training deck.pptx',
  ],
  notes: {
    meeting: ['S&OP preparation meeting', 'Supplier council notes', 'Operations review notes'],
    rfc: ['Design: planning model', 'Design: supplier portal', 'Design: exception handling'],
    runbook: ['Pilot site runbook', 'Carrier escalation procedure'],
    retro: ['Pilot retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Service level definitions'],
  },
  boards: [
    ['flow', 'Order-to-delivery flow'],
    ['architecture', 'Planning system landscape'],
    ['retro', 'Pilot retro board'],
  ],
};

export const CUSTOMER: KindVocab = {
  pools: {
    thing: [
      'the welcome journey', 'the health score model', 'the renewal playbook', 'the support macros', 'the self-service articles',
      'the customer survey', 'the onboarding checklist', 'the escalation process', 'the QBR template', 'the in-app guidance',
      'the churn risk alerts', 'the success plan', 'the knowledge base taxonomy', 'the CSAT follow-up', 'the executive sponsor programme',
      'the product feedback loop', 'the time-to-value dashboard',
    ],
    sys: ['Salesforce', 'Zendesk', 'Gainsight', 'Segment', 'Looker', 'the support platform'],
    vendor: ['Zendesk', 'Gainsight', 'Salesforce', 'Intercom', 'Qualtrics', 'Pendo'],
    metric: ['time to value', 'CSAT', 'net revenue retention', 'ticket deflection', 'first response time', 'health score coverage'],
    cohort: ['new enterprise customers', 'at-risk accounts', 'CSMs', 'support agents', 'the {region} customer base'],
  },
  titles: {
    plan: [
      'Define the segments and the playbooks for {thing}',
      'Agree the health score inputs with Product and Data',
      'Map the customer journey from signature to first value',
      'Write the target operating model for {cohort}',
      'Review the top ten reasons for contact and rank them by effort',
      'Set the baseline for {metric} before we change anything',
      'Draft the communication plan for customers affected by {thing}',
      'Plan the pilot with five friendly customers',
    ],
    build: [
      'Build {thing} in {sys}',
      'Write the 25 most requested knowledge base articles',
      'Automate the welcome emails and the kickoff scheduling',
      'Create the playbook for {thing} with the CSM team',
      'Connect product usage data to {thing}',
      'Migrate the macros and the views to the new platform',
      'Configure the alerts for {thing} and route them to the owners',
      'Add the in-app guidance for {thing}',
      'Build the dashboard for {metric}',
      'Create the QBR template and a sample for one customer',
    ],
    verify: [
      'Validate the health score against churned and renewed accounts of the last year',
      'Review ten onboarding calls recordings for {thing}',
      'UAT with {cohort} for {thing}',
      'Check the article search results for the top 50 queries',
      'Pilot {thing} with five accounts and collect feedback',
      'Compare {metric} for the pilot and the control group',
    ],
    rollout: [
      'Roll out {thing} to {cohort}',
      'Switch the support queue to the new platform for {region}',
      'Enable the in-app guidance for all new customers',
      'Retire the old knowledge base and redirect the URLs',
      'Launch the executive sponsor programme with the first ten accounts',
    ],
    ops: [
      'Review {metric} weekly and note what moved it',
      'Tidy the article backlog and fix the broken links',
      'Review the false positives from {thing} with Data',
      'Check that every at-risk account has an owner and a plan',
      'Update the escalation contacts for {region}',
    ],
    comms: [
      'Announce {thing} to {cohort}',
      'Train {cohort} on the new process',
      'Write the customer-facing note explaining what changes',
      'Share the success stories from the pilot internally',
      'Present the results to the executive team',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Programme roadmap'],
    sprint: ['Sprint {n}', 'Iteration {n}'],
    launch: ['Launch readiness', 'Rollout plan'],
    backlog: ['Backlog', 'Requests & ideas'],
    risk: ['Risks & escalations'],
    vendor: ['Vendor management', 'Platform vendor'],
    discovery: ['Discovery & journey mapping'],
    enable: ['CSM enablement', 'Training & adoption'],
  },
  folders: ['Playbooks', 'Research', 'Reports', 'Meeting notes', 'Templates', 'Customer stories', 'Training'],
  files: [
    'Playbooks|Renewal playbook v{n}.pdf', 'Playbooks|Onboarding checklist.docx', 'Playbooks|Escalation process.pdf',
    'Research|Customer interviews summary.pdf', 'Research|Survey results {q}.xlsx', 'Reports|Health score validation.xlsx',
    'Reports|Ticket deflection report.pdf', 'Templates|QBR template.pptx', 'Templates|Success plan template.docx',
    'Customer stories|Pilot customer story.docx', 'Training|CSM training deck.pptx', 'Training|Agent quick guide.pdf',
  ],
  notes: {
    meeting: ['Customer success sync', 'Pilot customer call notes', 'Voice of customer review'],
    rfc: ['Design: health score', 'Design: onboarding journey', 'Design: knowledge taxonomy'],
    runbook: ['Escalation runbook', 'Renewal runbook'],
    retro: ['Pilot retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Success plan guide'],
  },
  boards: [
    ['journey', 'Customer journey map'],
    ['flow', 'Escalation flow'],
    ['retro', 'Pilot retro board'],
  ],
};

export const SALES: KindVocab = {
  pools: {
    thing: [
      'the quote template', 'the discount approval matrix', 'the territory map', 'the quota model', 'the forecast call cadence',
      'the partner tiering model', 'the lead assignment rules', 'the opportunity stages', 'the commission plan documents', 'the pricing rules',
      'the contract renewal flow', 'the deal desk queue', 'the referral payout process', 'the pipeline inspection dashboard', 'the call recording policy',
      'the product catalogue', 'the account hierarchy',
    ],
    sys: ['Salesforce', 'Clari', 'Gong', 'DocuSign', 'Workato', 'the CPQ'],
    vendor: ['Salesforce', 'Clari', 'Gong', 'DocuSign', 'Xactly', 'LeanData'],
    metric: ['quote-to-cash cycle time', 'forecast accuracy', 'rep adoption', 'win rate', 'deal desk turnaround', 'partner-sourced pipeline'],
    cohort: ['quota-carrying reps', 'sales managers', 'deal desk', 'channel partners', 'the {region} sales team'],
  },
  titles: {
    plan: [
      'Draft the territory design principles and review them with {team}',
      'Agree the quote approval thresholds with Finance',
      'Map the quote-to-cash process and identify the manual steps',
      'Define the opportunity stage exit criteria',
      'Model the quota impact of {thing} per segment',
      'Write the partner programme tiers and the payout rules',
      'Collect requirements for {thing} from {cohort}',
      'Plan the phased rollout by region and segment',
    ],
    build: [
      'Configure {thing} in {sys}',
      'Build the pricing rules for {thing} and test the edge cases',
      'Automate the approval routing for {thing}',
      'Migrate the open opportunities to the new territory owners',
      'Create the dashboard for {metric}',
      'Integrate {sys} with the billing system',
      'Build the partner portal page for {thing}',
      'Set up the conversation intelligence alerts for {thing}',
      'Clean up duplicate accounts before the realignment',
      'Create the commission statement for {thing}',
    ],
    verify: [
      'UAT of {thing} with {cohort}',
      'Reconcile the quota and the territory assignments with Finance',
      'Test twenty real quotes through the new flow',
      'Check forecast roll-ups against the manual spreadsheet',
      'Validate the lead routing for the {region} accounts',
      'Pilot {thing} with one region for two weeks',
    ],
    rollout: [
      'Go live with {thing} for {cohort}',
      'Move the {region} team to the new territories on the first of the month',
      'Switch the quoting to {sys} and disable the old template',
      'Onboard the first ten partners',
      'Run the new forecast cadence for the first full quarter',
    ],
    ops: [
      'Review {metric} weekly with {team}',
      'Fix the issues found in the first week of {thing}',
      'Clean up orphaned opportunities after the territory change',
      'Review partner payouts for accuracy',
      'Audit the deal desk exceptions for the month',
    ],
    comms: [
      'Announce the territory changes to {cohort}',
      'Train {cohort} on {thing}',
      'Write the one-page guide to the new quote flow',
      'Share the adoption numbers with sales leadership',
      'Brief the partners on the programme changes',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Programme plan'],
    sprint: ['Sprint {n}', 'Wave {n}'],
    launch: ['Go-live & hypercare', 'Launch readiness'],
    backlog: ['Backlog', 'Requests'],
    risk: ['Controls & compliance'],
    vendor: ['Vendor & implementation partner'],
    discovery: ['Requirements & design'],
    enable: ['Sales enablement', 'Training & adoption'],
  },
  folders: ['Process', 'Territory data', 'Reports', 'Meeting notes', 'Enablement', 'Contracts', 'Partner programme'],
  files: [
    'Process|Quote-to-cash map v{n}.png', 'Process|Approval matrix.xlsx', 'Process|Stage definitions.docx',
    'Territory data|Account assignment file.xlsx', 'Territory data|Quota model {q}.xlsx', 'Reports|Pipeline review.xlsx',
    'Reports|Adoption dashboard export.csv', 'Enablement|Rep training deck.pptx', 'Enablement|Quote quick guide.pdf',
    'Contracts|Implementation partner SOW.pdf', 'Partner programme|Programme guide.pdf', 'Partner programme|Payout calculator.xlsx',
  ],
  notes: {
    meeting: ['Sales operations sync', 'Deal desk review', 'Regional leaders call'],
    rfc: ['Design: territory model', 'Design: approval workflow', 'Design: partner tiers'],
    runbook: ['Quarter-end runbook', 'Go-live runbook'],
    retro: ['Wave retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Sales process handbook'],
  },
  boards: [
    ['flow', 'Quote-to-cash flow'],
    ['journey', 'Rep journey for the new process'],
    ['retro', 'Wave retro board'],
  ],
};
