/** Kind vocabularies, part 1: software, mobile, data, security, infrastructure. */
import type { KindVocab } from './pmo-content-common';

export const SOFTWARE: KindVocab = {
  pools: {
    thing: [
      'the checkout service', 'the identity provider integration', 'the order API', 'the session store', 'the pricing engine',
      'the notification worker', 'the search index', 'the account settings flow', 'the invoice export', 'the webhook dispatcher',
      'the rate limiter', 'the feature flag client', 'the audit log pipeline', 'the tenant configuration service', 'the file upload path',
      'the GraphQL gateway', 'the background job runner', 'the admin console', 'the customer-facing status page', 'the SDK',
    ],
    sys: ['PostgreSQL', 'Kafka', 'Redis', 'Kubernetes', 'the edge gateway', 'Terraform', 'GraphQL', 'OpenTelemetry', 'Argo CD'],
    vendor: ['Auth0', 'Stripe', 'Datadog', 'LaunchDarkly', 'Twilio', 'Sentry', 'PagerDuty'],
    metric: ['p95 latency', 'error rate', 'checkout conversion', 'time to first byte', 'build time', 'deploy frequency'],
    cohort: ['internal dogfood group', 'beta customers', 'the first ten enterprise tenants', 'EU customers', 'free-tier users'],
  },
  titles: {
    plan: [
      'Write the RFC for splitting {thing} out of the monolith',
      'Agree the API versioning policy for {subj} with consumer teams',
      'Draft the threat model for {thing}',
      'Scope the data migration for {thing} and list the irreversible steps',
      'Define SLOs and an error budget for {thing}',
      'Decide build vs. buy for {thing}',
      'Plan the deprecation timeline for the v1 API',
      'Break the epic for {thing} into independently shippable slices',
    ],
    build: [
      'Cut over EU customer cohort to the new gateway',
      'Implement idempotency keys for {thing}',
      'Add cursor-based pagination to {thing}',
      'Replace polling with event-driven updates in {thing}',
      'Introduce circuit breakers around calls to {thing}',
      'Move {thing} behind the feature flag service',
      'Add contract tests between {thing} and {thing2}',
      'Backfill historical records into the new schema',
      'Reduce cold-start time of {thing} by trimming dependencies',
      'Implement role-based access checks in {thing}',
      'Write the migration to drop the deprecated columns',
      'Instrument {thing} with OpenTelemetry traces',
      'Port {thing} to the new design system components',
      'Fix race condition when two requests update {thing} at once',
    ],
    verify: [
      'Load test {thing} at 3x peak traffic',
      'Run the penetration test findings against {thing}',
      'Chaos test: kill a {sys} node during peak and record recovery time',
      'Verify data parity between old and new versions of {thing} for one full billing cycle',
      'Accessibility audit of the new screens for {thing}',
      'Review the dependency scan results and patch anything critical',
      'Exploratory testing session for the {region} locale',
    ],
    rollout: [
      'Enable {thing} for {cohort} behind the flag',
      'Ramp traffic to the new path to 25% and compare {metric}',
      'Run the production cutover rehearsal for {thing}',
      'Roll back plan walk-through for the release train',
      'Switch the {region} tenants to {thing}',
      'Retire the old endpoints after the deprecation window closes',
    ],
    ops: [
      'Write the on-call runbook for {thing}',
      'Tune the paging thresholds for {thing}; too many false alarms last week',
      'Clean up the dead feature flags left behind by the last release',
      'Rotate the credentials used by {thing}',
      'Postmortem follow-up: add a canary check for {thing}',
      'Upgrade {sys} to the current minor version in all environments',
    ],
    comms: [
      'Publish the migration guide for API consumers of {thing}',
      'Announce the deprecation of the v1 endpoints to partner developers',
      'Write the release notes for the {quarter} train',
      'Demo {thing} at the engineering all-hands',
      'Update the public changelog and the developer portal',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Platform roadmap', 'Delivery roadmap'],
    sprint: ['Sprint {n}', 'Sprint {n}', 'Iteration {n}'],
    launch: ['Launch readiness', 'Production cutover', 'GA checklist'],
    backlog: ['Backlog & tech debt', 'Backlog', 'Engineering backlog'],
    risk: ['Security & compliance review', 'Reliability work', 'Risks & dependencies'],
    vendor: ['Vendor & licensing', 'Third-party integrations'],
    discovery: ['Discovery & design', 'Architecture decisions'],
    enable: ['Developer enablement', 'Docs & enablement'],
  },
  folders: ['Design', 'Architecture', 'Runbooks', 'Meeting notes', 'Reports', 'Contracts', 'Test evidence', 'Reference'],
  files: [
    'Architecture|Architecture overview v{n}.pdf', 'Architecture|Sequence diagrams.png', 'Architecture|Data model.png',
    'Design|Wireframes round {n}.pdf', 'Design|Design review notes.docx', 'Design|Component inventory.xlsx',
    'Runbooks|On-call runbook.pdf', 'Runbooks|Rollback procedure.md', 'Runbooks|Incident checklist.pdf',
    'Test evidence|Load test results.csv', 'Test evidence|Pen test summary.pdf', 'Test evidence|Regression report.xlsx',
    'Reports|Weekly status report.pdf', 'Reports|Burndown export.csv', 'Reports|Release metrics {q}.xlsx',
    'Contracts|Vendor order form.pdf', 'Contracts|DPA draft.docx', 'Reference|API reference snapshot.pdf',
  ],
  notes: {
    meeting: ['Weekly sync', 'Architecture review notes', 'Stakeholder check-in', 'Planning session'],
    rfc: ['RFC: service boundaries', 'RFC: API versioning', 'RFC: event schema', 'RFC: authorization model'],
    runbook: ['On-call runbook', 'Release runbook', 'Rollback procedure', 'Incident response notes'],
    retro: ['Sprint retrospective', 'Release retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Engineering working agreements', 'Definition of done'],
  },
  boards: [
    ['architecture', 'Target architecture sketch'],
    ['flow', 'Release pipeline'],
    ['retro', 'Sprint retro board'],
    ['journey', 'Customer journey: first integration'],
  ],
};

export const MOBILE: KindVocab = {
  pools: {
    thing: [
      'the onboarding flow', 'push notification opt-in', 'offline sync', 'the in-app wallet', 'biometric login', 'the deep link router',
      'the camera capture screen', 'the barcode scanner', 'the settings tab', 'the work-order list', 'the signature capture', 'background location tracking',
      'the crash reporter', 'the app update prompt', 'the receipts screen', 'the map view', 'the sync conflict dialog',
    ],
    sys: ['SwiftUI', 'Jetpack Compose', 'Firebase', 'Fastlane', 'GraphQL', 'Detox', 'the CI runners', 'TestFlight'],
    vendor: ['Firebase', 'Apple', 'Google Play', 'Sentry', 'BrowserStack', 'Braze', 'Zebra'],
    metric: ['crash-free sessions', 'cold-start time', 'store rating', 'day-7 retention', 'ANR rate', 'battery drain'],
    cohort: ['TestFlight testers', 'the field pilot crew', '5% staged rollout', 'Android beta channel', 'internal staff devices'],
  },
  titles: {
    plan: [
      'Define the offline-first behaviour for {thing}',
      'Write the release train calendar for the next two quarters',
      'Decide which OS versions we drop in this release',
      'Agree the accessibility acceptance criteria for {thing}',
      'Plan the store listing refresh with Marketing',
      'Prioritise the top 20 crash clusters by user impact',
    ],
    build: [
      'Build {thing} in SwiftUI and Jetpack Compose',
      'Fix crash on {thing} for Android 12 devices',
      'Reduce cold-start time of the app below 1.5 s on mid-range phones',
      'Add retry with backoff to {thing}',
      'Implement conflict resolution when the same record is edited offline twice',
      'Migrate {thing} from the old networking layer to GraphQL',
      'Support dark mode and dynamic type on {thing}',
      'Wire up analytics events for {thing}',
      'Replace the custom keychain wrapper with the platform API',
      'Handle low-storage devices gracefully in {thing}',
      'Add haptic and VoiceOver hints to {thing}',
      'Fix text clipping in {thing} on small devices',
    ],
    verify: [
      'Run the device-lab matrix for {thing} on the ten most common handsets',
      'VoiceOver and TalkBack pass on {thing}',
      'Beta feedback triage for {cohort}',
      'Regression run on the release candidate build',
      'Validate battery usage of {thing} over a full shift',
      'Test {thing} on a throttled 3G connection',
    ],
    rollout: [
      'Submit the release candidate to App Store review',
      'Start the staged rollout at 5% and watch {metric}',
      'Roll out to {cohort}',
      'Pause the rollout if {metric} drops below the threshold',
      'Force-update plan for devices on the unsupported versions',
    ],
    ops: [
      'Triage the new crash clusters in Sentry',
      'Renew the signing certificates before they expire',
      'Clean up unused push notification topics',
      'Update the store metadata and screenshots for {region}',
      'Monitor {metric} daily for the first week after release',
    ],
    comms: [
      'Write the what\'s-new text for the store listing',
      'Brief the support team on {thing} before the release',
      'Record a walkthrough video of {thing} for field supervisors',
      'Publish the release notes in the internal newsletter',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'App roadmap'],
    sprint: ['Release train {n}', 'Sprint {n}'],
    launch: ['Store submission & rollout', 'Launch readiness'],
    backlog: ['Bugs & polish', 'Backlog'],
    risk: ['Quality & stability', 'Accessibility'],
    discovery: ['Research & discovery'],
    enable: ['Field enablement', 'Support enablement'],
  },
  folders: ['Design', 'Store assets', 'Release notes', 'Meeting notes', 'Test reports', 'Research'],
  files: [
    'Design|App flows v{n}.pdf', 'Design|Icon set.png', 'Design|Tablet layouts.png',
    'Store assets|Screenshots iOS.png', 'Store assets|Screenshots Android.png', 'Store assets|Store listing copy.docx',
    'Release notes|Release notes draft.md', 'Test reports|Device lab results.xlsx', 'Test reports|Crash analysis {q}.pdf',
    'Research|Field interviews summary.pdf', 'Research|Usability test findings.pdf', 'Release notes|Rollout checklist.pdf',
  ],
  notes: {
    meeting: ['Release train sync', 'Field feedback session', 'Design handoff review'],
    rfc: ['RFC: offline sync', 'RFC: navigation architecture', 'RFC: analytics events'],
    runbook: ['Release runbook', 'Hotfix procedure'],
    retro: ['Release retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Supported device policy'],
  },
  boards: [
    ['journey', 'Technician journey map'],
    ['flow', 'Release flow'],
    ['retro', 'Release retro'],
  ],
};

export const DATA: KindVocab = {
  pools: {
    thing: [
      'the customer dimension', 'the orders fact table', 'the revenue mart', 'the finance close dashboard', 'the churn feature store',
      'the product usage events', 'the nightly ingestion job', 'the CRM sync', 'the metrics layer', 'the supplier dataset',
      'the lineage graph', 'the data catalog entries', 'the certified datasets', 'the demand forecast', 'the identity resolution model',
      'the clickstream pipeline', 'the reconciliation report', 'the semantic model',
    ],
    sys: ['Snowflake', 'dbt', 'Airflow', 'Kafka', 'Spark', 'Looker', 'Great Expectations', 'the warehouse'],
    vendor: ['Snowflake', 'Fivetran', 'Looker', 'Monte Carlo', 'Collibra', 'Databricks'],
    metric: ['dashboard load time', 'freshness SLA', 'warehouse credits per day', 'null rate', 'match rate', 'MAPE'],
    cohort: ['finance analysts', 'the sales analytics team', 'regional ops managers', 'data stewards', 'executive dashboard users'],
  },
  titles: {
    plan: [
      'Inventory every report still reading from the legacy warehouse',
      'Assign data owners and stewards for the tier-one datasets',
      'Define the metric catalog for {thing} with {team}',
      'Agree freshness and quality SLAs for {thing}',
      'Document the lineage of {thing} end to end',
      'Prioritise which dashboards to migrate first based on usage',
      'Draft the data retention policy for {thing} with Legal',
      'Scope the backfill of three years of history for {thing}',
    ],
    build: [
      'Migrate {thing} from the legacy warehouse to {sys}',
      'Rewrite the models behind {thing} in dbt with tests',
      'Add schema drift detection to {thing}',
      'Build the incremental load for {thing}',
      'Backfill history for {thing} without breaking downstream reports',
      'Create the certified view for {thing} and deprecate the old one',
      'Optimise the slowest 10 queries on {thing}',
      'Implement row-level security for {thing}',
      'Replace the nightly batch with streaming for {thing}',
      'Add data quality checks on null rate and uniqueness for {thing}',
      'Document every column of {thing} in the catalog',
      'Deduplicate customer records using the identity resolution rules',
    ],
    verify: [
      'Reconcile totals between the old and new versions of {thing} for the last 12 months',
      'Parallel-run the old and new dashboards for two close cycles',
      'Validate {thing} with {team} and capture sign-off',
      'Backtest {thing} against the last four quarters',
      'Run the data quality suite against production and triage the failures',
      'Compare row counts and checksums after each migration wave',
    ],
    rollout: [
      'Switch {cohort} to the new dashboards and retire the old ones',
      'Cut over {thing} to read from {sys}',
      'Freeze writes to the legacy warehouse for the final sync',
      'Migrate the {region} reporting packs',
      'Publish the certified dataset and announce it in the catalog',
    ],
    ops: [
      'Set up freshness alerts for {thing} and route them to {team}',
      'Review warehouse spend and right-size the compute for {thing}',
      'Clean up unused tables and views flagged by the usage report',
      'Rotate service account keys for the ingestion jobs',
      'Review access grants on {thing} for the quarterly recertification',
    ],
    comms: [
      'Write the migration guide for {cohort}',
      'Hold office hours for analysts moving to the new platform',
      'Publish the data dictionary for {thing}',
      'Share the weekly data quality scorecard with {team}',
      'Present the cost savings so far to the steering committee',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Platform roadmap', 'Migration waves'],
    sprint: ['Sprint {n}', 'Pipeline sprint {n}'],
    launch: ['Cutover plan', 'Go-live checklist'],
    backlog: ['Backlog', 'Backlog & tech debt'],
    risk: ['Governance & quality', 'Data quality & controls'],
    vendor: ['Vendor & licensing'],
    discovery: ['Requirements & discovery', 'Source system inventory'],
    enable: ['Analyst enablement', 'Training & adoption'],
  },
  folders: ['Data models', 'Reports', 'Meeting notes', 'Specs', 'Quality evidence', 'Vendor docs', 'Training'],
  files: [
    'Data models|ER diagram v{n}.png', 'Data models|Lineage export.csv', 'Data models|Metric definitions.xlsx',
    'Specs|Source-to-target mapping.xlsx', 'Specs|Migration wave plan.pdf', 'Specs|Data contract template.docx',
    'Quality evidence|Reconciliation results.xlsx', 'Quality evidence|Quality scorecard {q}.pdf', 'Reports|Warehouse spend report.csv',
    'Reports|Dashboard usage analysis.xlsx', 'Vendor docs|Platform order form.pdf', 'Training|Analyst onboarding deck.pptx',
  ],
  notes: {
    meeting: ['Data steering sync', 'Source owner workshop', 'Reporting stakeholder review'],
    rfc: ['RFC: metrics layer', 'RFC: incremental loading', 'RFC: data contracts'],
    runbook: ['Pipeline failure runbook', 'Backfill procedure'],
    retro: ['Migration wave retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Dataset certification criteria'],
  },
  boards: [
    ['architecture', 'Target data platform'],
    ['flow', 'Ingestion to dashboard flow'],
    ['retro', 'Wave retro board'],
  ],
};

export const SECURITY: KindVocab = {
  pools: {
    thing: [
      'the access review process', 'the privileged account inventory', 'MFA enforcement', 'the vulnerability management workflow', 'the endpoint detection rollout',
      'the incident response playbook', 'the vendor risk questionnaire', 'the secrets rotation job', 'the SIEM correlation rules', 'the change management control',
      'the offboarding checklist', 'the logging baseline', 'the encryption-at-rest standard', 'the backup restore test', 'the phishing simulation',
      'the data classification scheme', 'the network segmentation policy',
    ],
    sys: ['Okta', 'CrowdStrike', 'Vault', 'Splunk', 'Wiz', 'Terraform', 'the SIEM', 'the identity provider'],
    vendor: ['Okta', 'CrowdStrike', 'Wiz', 'HashiCorp', 'Splunk', 'Vanta', 'Drata'],
    metric: ['mean time to remediate', 'control coverage', 'MFA adoption', 'critical findings open', 'phishing click rate', 'evidence completeness'],
    cohort: ['privileged administrators', 'engineering leads', 'the finance team', 'contractors', 'all employees'],
  },
  titles: {
    plan: [
      'Map {thing} to the SOC 2 trust services criteria',
      'Complete the gap assessment for {thing} and rank the findings',
      'Write the control narrative for {thing}',
      'Agree the auditor sampling approach for {thing}',
      'Define the risk acceptance process for exceptions to {thing}',
      'Update the security policy set and route it for approval',
      'Scope the tabletop exercise with the executive team',
      'Plan the remediation sprint for the open high findings',
    ],
    build: [
      'Enforce phishing-resistant MFA for {cohort}',
      'Automate evidence collection for {thing}',
      'Rotate every long-lived credential found in the secrets scan',
      'Move {thing} from manual tickets to an automated workflow',
      'Deploy the endpoint agent to the remaining unmanaged devices',
      'Write detection rules for the top ten attack techniques against {thing}',
      'Tighten network rules between {sys} and the workloads that do not need it',
      'Enable audit logging for {thing} and ship it to the SIEM',
      'Implement just-in-time access for {cohort}',
      'Remove standing admin rights from service accounts',
      'Patch the critical findings on {thing}',
      'Integrate the vulnerability scanner with the ticketing workflow',
    ],
    verify: [
      'Sample 25 {thing} records and test them against the control',
      'Retest the penetration test findings that were marked as fixed',
      'Run the access recertification and record every exception',
      'Walkthrough with the auditor for {thing}',
      'Validate that alerts for {thing} fire and reach the on-call',
      'Restore test of the production backup with {team} observing',
    ],
    rollout: [
      'Roll out the new policy to {cohort} and collect attestations',
      'Enforce the control for {region} after the grace period',
      'Switch the detection rules from monitor to block mode',
      'Run the phishing simulation for {cohort}',
      'Close the exception window for {thing}',
    ],
    ops: [
      'Review and renew the risk exceptions expiring this month',
      'Triage the weekly vulnerability report with {team}',
      'Upload evidence for {thing} to the audit portal',
      'Reconcile the asset inventory against the CMDB',
      'Update the incident contact list and test the paging path',
    ],
    comms: [
      'Write the security awareness note for {cohort}',
      'Prepare the board risk summary for {quarter}',
      'Brief the auditors on the changes since the last period',
      'Publish the exception request guide on the intranet',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Security roadmap'],
    sprint: ['Remediation sprint {n}', 'Sprint {n}'],
    launch: ['Audit window', 'Rollout checklist'],
    backlog: ['Backlog', 'Findings backlog'],
    risk: ['Compliance evidence', 'Risk register', 'Control testing'],
    vendor: ['Vendor risk reviews', 'Vendor onboarding'],
    discovery: ['Gap assessment'],
    enable: ['Awareness & training'],
  },
  folders: ['Evidence', 'Policies', 'Audit requests', 'Meeting notes', 'Pen test reports', 'Vendor reviews', 'Training'],
  files: [
    'Policies|Information security policy v{n}.pdf', 'Policies|Access control standard.docx', 'Policies|Exception request form.docx',
    'Evidence|Access review export {q}.xlsx', 'Evidence|Change tickets sample.csv', 'Evidence|MFA enrollment screenshot.png',
    'Audit requests|PBC request list.xlsx', 'Audit requests|Auditor walkthrough notes.docx', 'Pen test reports|External pen test summary.pdf',
    'Pen test reports|Remediation tracker.xlsx', 'Vendor reviews|Vendor security questionnaire.xlsx', 'Training|Awareness deck.pptx',
  ],
  notes: {
    meeting: ['Weekly control owners sync', 'Auditor walkthrough notes', 'Tabletop exercise debrief'],
    rfc: ['RFC: access model', 'RFC: secrets management', 'RFC: logging baseline'],
    runbook: ['Incident response runbook', 'Evidence collection runbook'],
    retro: ['Audit readiness retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Risk acceptance log'],
    brief: ['Control owner handbook'],
  },
  boards: [
    ['architecture', 'Network segmentation target state'],
    ['flow', 'Access request flow'],
    ['retro', 'Tabletop retro'],
  ],
};

export const INFRASTRUCTURE: KindVocab = {
  pools: {
    thing: [
      'the primary database cluster', 'the load balancer tier', 'the DNS failover configuration', 'the Kubernetes control plane', 'the CI runners',
      'the object storage buckets', 'the VPN gateways', 'the service mesh', 'the metrics pipeline', 'the log aggregation tier',
      'the backup schedule', 'the on-premises storage array', 'the identity federation', 'the container registry', 'the autoscaling policy',
      'the bastion hosts', 'the disaster recovery runbook', 'the staging environment',
    ],
    sys: ['AWS', 'Terraform', 'Kubernetes', 'Datadog', 'Argo CD', 'Prometheus', 'Ansible', 'Route 53'],
    vendor: ['AWS', 'Datadog', 'HashiCorp', 'Equinix', 'Cloudflare', 'Grafana Labs', 'Red Hat'],
    metric: ['recovery time', 'monthly cloud spend', 'availability', 'deploy lead time', 'cost per request', 'unused capacity'],
    cohort: ['non-production clusters', 'the first three services', 'Tier-2 workloads', 'the EU region', 'the legacy data centre racks'],
  },
  titles: {
    plan: [
      'Draft the failover design for {thing} and review it with {team}',
      'Inventory every workload still running in the data centre',
      'Define the RTO and RPO targets per service tier',
      'Write the capacity plan for {thing} for the next 12 months',
      'Build the cost model for moving {thing} to {sys}',
      'Plan the upgrade path for {thing} with zero downtime',
      'Agree the change freeze calendar with {team}',
      'Assess the commitments and break clauses on the existing hosting contract',
    ],
    build: [
      'Provision the secondary region with Terraform',
      'Automate the failover of {thing} and test it in {env}',
      'Upgrade {thing} to the next supported version',
      'Replace manual changes on {thing} with a pipeline',
      'Right-size the oversized instances behind {thing}',
      'Set up cross-region replication for {thing}',
      'Migrate {thing} off the legacy hardware',
      'Consolidate the three alerting tools into one',
      'Implement tagging standards and enforce them in policy',
      'Move {thing} to spot capacity where the workload allows',
      'Standardise the base images and remove snowflake servers',
      'Add synthetic checks for the customer-critical journeys',
    ],
    verify: [
      'Game day: fail over {thing} to the secondary region',
      'Measure actual recovery time and compare it with the target',
      'Run the restore test of {thing} from the last backup',
      'Soak test the upgraded {thing} for 72 hours',
      'Validate the cost savings against the billing export',
      'Verify no traffic still hits the old endpoints before decommissioning',
    ],
    rollout: [
      'Migrate {cohort} in the next maintenance window',
      'Cut over DNS for {thing} with a low TTL and a tested rollback',
      'Move the {region} workloads to the new platform',
      'Power down and recycle the legacy hardware racks',
      'Switch the CI runners to the new autoscaling pool',
    ],
    ops: [
      'Review the weekly cloud spend anomalies with {team}',
      'Remove orphaned volumes and snapshots flagged by the audit',
      'Renew the TLS certificates expiring in the next 30 days',
      'Update the DR runbook after the last game day',
      'Close the stale firewall rules found in the quarterly review',
    ],
    comms: [
      'Announce the maintenance window to service owners',
      'Publish the savings report for {quarter}',
      'Brief the on-call engineers on the new alert routing',
      'Write the post-migration report for {thing}',
    ],
  },
  lists: {
    roadmap: ['Roadmap', 'Platform roadmap', 'Migration waves'],
    sprint: ['Sprint {n}', 'Infra sprint {n}'],
    launch: ['Cutover plan', 'Maintenance windows'],
    backlog: ['Backlog', 'Toil reduction'],
    risk: ['Resilience & DR testing', 'Risks & compliance'],
    vendor: ['Vendor & contracts', 'Procurement & contracts'],
    discovery: ['Inventory & assessment'],
    enable: ['Runbooks & enablement'],
  },
  folders: ['Architecture', 'Runbooks', 'Cost reports', 'Meeting notes', 'Change records', 'Contracts', 'DR tests'],
  files: [
    'Architecture|Failover design v{n}.pdf', 'Architecture|Network diagram.png', 'Architecture|Capacity model.xlsx',
    'Runbooks|DR runbook.pdf', 'Runbooks|Cutover checklist.md', 'Runbooks|Maintenance window procedure.docx',
    'Cost reports|Cloud spend {q}.xlsx', 'Cost reports|Savings tracker.xlsx', 'Change records|CAB approvals export.csv',
    'DR tests|Game day report.pdf', 'DR tests|Restore test results.csv', 'Contracts|Hosting contract summary.pdf',
  ],
  notes: {
    meeting: ['Change advisory board notes', 'Weekly infra sync', 'Game day debrief'],
    rfc: ['RFC: multi-region strategy', 'RFC: cluster upgrades', 'RFC: tagging standard'],
    runbook: ['Failover runbook', 'Cutover runbook', 'Cluster upgrade runbook'],
    retro: ['Game day retrospective', 'Migration wave retrospective'],
    kickoff: ['Project kickoff brief'],
    decision: ['Decision log'],
    brief: ['Service tier definitions'],
  },
  boards: [
    ['architecture', 'Multi-region target architecture'],
    ['flow', 'Failover sequence'],
    ['retro', 'Game day retro'],
  ],
};
